import {componentResult,COMPONENT_STATUS,explanation} from "./playerIntelligenceFoundation.js";
import {buildExactPercentileContext,exactPercentile} from "./playerIntelligencePercentile.js";
export const UNDERLYING_SKILL_VERSION="5.5B-3",MATERIAL_GAP_THRESHOLD=20;
export const HITTER_WEIGHTS=Object.freeze({xwoba:.25,xslg:.20,xba:.15,barrelRate:.15,hardHitRate:.12,averageExitVelocity:.08,sprintSpeed:.05});
export const PITCHER_WEIGHTS=Object.freeze({xera:.40,xwobaAllowed:.25,barrelRateAllowed:.15,hardHitRateAllowed:.12,averageExitVelocityAllowed:.08});
const LOWER=new Set(Object.keys(PITCHER_WEIGHTS)),num=v=>typeof v==="number"&&Number.isFinite(v),round=v=>Math.round(v*100)/100;
function warn(code,message){return {code,group:"underlyingSkill",severity:"WARNING",message,details:{}}}
export function buildUnderlyingSkillContext(inputs){if(!inputs?.length)throw new Error("Canonical inputs are required.");const leagueId=inputs[0].leagueId;if(inputs.some(x=>x.leagueId!==leagueId))throw new Error("Skill context must be league scoped.");const populations={hitter:{},pitcher:{}},percentileContexts={hitter:{},pitcher:{}};for(const type of ["hitter","pitcher"]){const weights=type==="hitter"?HITTER_WEIGHTS:PITCHER_WEIGHTS,typeInputs=inputs.filter(x=>x.underlyingSkill.playerType===type);for(const key of Object.keys(weights)){populations[type][key]=typeInputs.map(x=>x.underlyingSkill.metrics[key]).filter(num);percentileContexts[type][key]=buildExactPercentileContext(populations[type][key])}}return {leagueId,inputsById:new Map(inputs.map(x=>[x.playerId,x])),populations,percentileContexts}}
export function evaluateUnderlyingSkill(context,playerId){const input=context.inputsById.get(playerId);if(!input)throw new Error("Player not found in skill context.");const type=input.underlyingSkill.playerType,metrics=input.underlyingSkill.metrics||{},weights=type==="hitter"?HITTER_WEIGHTS:PITCHER_WEIGHTS,rows=[];for(const [key,weight] of Object.entries(weights))if(num(metrics[key]))rows.push({metric:key,rawValue:metrics[key],percentile:exactPercentile(metrics[key],context.percentileContexts[type][key],{invert:LOWER.has(key)}),direction:LOWER.has(key)?"LOWER_IS_BETTER":"HIGHER_IS_BETTER",populationSize:context.populations[type][key].length,weight});
  if(!rows.length){const status=input.player.isMinorLeaguer?COMPONENT_STATUS.NOT_APPLICABLE:COMPONENT_STATUS.INSUFFICIENT_DATA;return {component:componentResult({status,warnings:[warn("INSUFFICIENT_STATCAST","No canonical MLB Statcast evidence is available.")],version:UNDERLYING_SKILL_VERSION}),evidence:{playerType:type,metricsUsed:[],metricPercentiles:[],coverageRatio:0,freshness:input.dataFreshness.statcast},signal:null}}
  const availableWeight=rows.reduce((s,x)=>s+x.weight,0),score=round(rows.reduce((s,x)=>s+x.percentile*x.weight,0)/availableWeight),coverage=round(rows.length/Object.keys(weights).length),warnings=[];if(coverage<1)warnings.push(warn("PARTIAL_STATCAST_COVERAGE","Underlying Skill uses partial canonical Statcast coverage."));if(input.underlyingSkill.status==="STALE")warnings.push(warn("STALE_STATCAST","Canonical Statcast evidence is stale."));if(type==="pitcher")warnings.push(warn("LIMITED_PITCHER_SKILL_INPUTS","Current pitcher skill inputs do not include strikeout, walk, whiff, velocity, or role evidence."));const confidence=Math.round(Math.max(20,90*coverage-(input.underlyingSkill.status==="STALE"?25:0)-(type==="pitcher"?10:0))),status=input.underlyingSkill.status==="STALE"?COMPONENT_STATUS.STALE:COMPONENT_STATUS.CALCULATED;
  const eraEvidence=[];if(type==="pitcher"&&num(metrics.era)&&num(metrics.xera)){const gap=round(metrics.era-metrics.xera),code=Math.abs(gap)<.5?"ERA_XERA_ALIGNED":gap<0?"ERA_OUTPERFORMING_XERA":"ERA_UNDERPERFORMING_XERA";eraEvidence.push(explanation({code,data:{era:metrics.era,xera:metrics.xera,gap},source:"Statcast surface vs expected"}))}
  const component=componentResult({status,score:status===COMPONENT_STATUS.CALCULATED?score:null,confidence,inputsUsed:rows.map(x=>`Statcast.${x.metric}`),explanations:[explanation({code:type==="hitter"?(score>=75?"ELITE_EXPECTED_PRODUCTION":score>=60?"STRONG_CONTACT_QUALITY":"WEAK_CONTACT_QUALITY"):(score>=70?"STRONG_EXPECTED_RUN_PREVENTION":"CONTACT_ALLOWED_CONCERN"),data:{playerType:type,score,coverageRatio:coverage,metrics:rows},source:"Statcast"}),...eraEvidence],warnings,version:UNDERLYING_SKILL_VERSION});return {component,evidence:{playerType:type,metricsUsed:rows.map(x=>x.metric),metricPercentiles:rows,coverageRatio:coverage,freshness:input.dataFreshness.statcast,surfaceEvidence:{era:metrics.era??null,xera:metrics.xera??null},score},signal:null}}
export function breakoutRegressionSignal({productionPercentile,skillResult}){const skill=skillResult?.evidence?.score;if(!num(productionPercentile)||!num(skill)||skillResult.component.status!==COMPONENT_STATUS.CALCULATED)return null;const gap=round(skill-productionPercentile);let code="NEUTRAL_PRODUCTION_SKILL_GAP";if(gap>=MATERIAL_GAP_THRESHOLD)code="BREAKOUT_SIGNAL";else if(gap<=-MATERIAL_GAP_THRESHOLD)code="REGRESSION_RISK";else if(productionPercentile>=75&&skill>=75)code="SUPPORTED_PRODUCTION";else if(productionPercentile<=40&&skill<=40)code="WEAK_PRODUCTION_SUPPORTED";return {code,productionPercentile,skillPercentile:skill,gap,confidence:skillResult.component.confidence,supportingMetrics:skillResult.evidence.metricsUsed}}
export function evaluateUnderlyingSkillPopulation(inputs,productionResults=[]){const context=buildUnderlyingSkillContext(inputs),byId=new Map(productionResults.map(x=>[x.playerId,x]));return {context,players:inputs.map(input=>{const result=evaluateUnderlyingSkill(context,input.playerId),prior=byId.get(input.playerId)||null,p=prior?.components?.leagueProduction?.explanations?.[0]?.data?.leaguePercentile??null;result.signal=breakoutRegressionSignal({productionPercentile:p,skillResult:result});const output=prior?{...prior,components:{...prior.components,underlyingSkill:result.component},signals:[...(prior.signals||[]),...(result.signal?[result.signal]:[])]}:null;return {playerId:input.playerId,...result,output}})}}
