import {PROSPECT_OPPORTUNITY_COST_DIRECTION} from "./playerIntelligenceContext.js";
import {buildExactPercentileContext,exactPercentile} from "./playerIntelligencePercentile.js";
export const PLAYER_INTELLIGENCE_COMPOSITE_VERSION="5.5B-5";
export const ARCHETYPES=Object.freeze({MLB_HITTER:"MLB_HITTER",MLB_STARTING_PITCHER:"MLB_STARTING_PITCHER",MLB_RELIEVER:"MLB_RELIEVER",YOUNG_MLB_OR_RECENT_CALLUP:"YOUNG_MLB_OR_RECENT_CALLUP",MLB_VETERAN:"MLB_VETERAN",NEAR_MLB_PROSPECT:"NEAR_MLB_PROSPECT",DISTANT_PROSPECT:"DISTANT_PROSPECT",CONSERVATIVE_UNKNOWN:"CONSERVATIVE_UNKNOWN",TWO_WAY_DEFERRED:"TWO_WAY_DEFERRED"});
export const APPLICABILITY=Object.freeze({REQUIRED:"REQUIRED",OPTIONAL:"OPTIONAL",NOT_APPLICABLE:"NOT_APPLICABLE"});
const C=["leagueProduction","underlyingSkill","replacementAdvantage","positionalScarcityValue","roleStability","ageTrajectory","risk","prospectOpportunityCost","marketSupport"];
const mlb=(weights)=>Object.freeze(Object.fromEntries(C.map(k=>[k,{applicability:["prospectOpportunityCost","marketSupport"].includes(k)?APPLICABILITY.NOT_APPLICABLE:APPLICABILITY.REQUIRED,weight:weights[k]||0}])));
const prospect=(weights,near)=>Object.freeze(Object.fromEntries(C.map(k=>[k,{applicability:["ageTrajectory","risk","prospectOpportunityCost","positionalScarcityValue","roleStability","marketSupport"].includes(k)?APPLICABILITY.REQUIRED:(near&&["leagueProduction","underlyingSkill","replacementAdvantage"].includes(k)?APPLICABILITY.OPTIONAL:APPLICABILITY.NOT_APPLICABLE),weight:weights[k]||0}])));
export const ARCHETYPE_MATRIX=Object.freeze({
  [ARCHETYPES.MLB_HITTER]:mlb({leagueProduction:24,underlyingSkill:20,replacementAdvantage:16,positionalScarcityValue:8,roleStability:12,ageTrajectory:10,risk:10}),
  [ARCHETYPES.MLB_STARTING_PITCHER]:mlb({leagueProduction:24,underlyingSkill:24,replacementAdvantage:14,positionalScarcityValue:5,roleStability:13,ageTrajectory:8,risk:12}),
  [ARCHETYPES.MLB_RELIEVER]:mlb({leagueProduction:27,underlyingSkill:14,replacementAdvantage:17,positionalScarcityValue:6,roleStability:18,ageTrajectory:6,risk:12}),
  [ARCHETYPES.YOUNG_MLB_OR_RECENT_CALLUP]:mlb({leagueProduction:16,underlyingSkill:22,replacementAdvantage:12,positionalScarcityValue:7,roleStability:13,ageTrajectory:18,risk:12}),
  [ARCHETYPES.MLB_VETERAN]:mlb({leagueProduction:28,underlyingSkill:18,replacementAdvantage:16,positionalScarcityValue:7,roleStability:14,ageTrajectory:7,risk:10}),
  [ARCHETYPES.NEAR_MLB_PROSPECT]:prospect({ageTrajectory:24,prospectOpportunityCost:30,risk:18,positionalScarcityValue:10,roleStability:10,marketSupport:8,leagueProduction:0,underlyingSkill:0,replacementAdvantage:0},true),
  [ARCHETYPES.DISTANT_PROSPECT]:prospect({ageTrajectory:20,prospectOpportunityCost:34,risk:24,positionalScarcityValue:8,roleStability:6,marketSupport:8},false),
  [ARCHETYPES.CONSERVATIVE_UNKNOWN]:mlb({leagueProduction:20,underlyingSkill:18,replacementAdvantage:14,positionalScarcityValue:6,roleStability:14,ageTrajectory:14,risk:14})
});
const num=v=>typeof v==="number"&&Number.isFinite(v),round=v=>Math.round(Number(v)*100)/100,clamp=v=>Math.max(0,Math.min(100,round(v))),upper=v=>String(v||"").toUpperCase();
const NEAR_MLB_LEVELS=new Set(["AAA","AA"]),DISTANT_PROSPECT_LEVELS=new Set(["A_PLUS","A","ROOKIE","COMPLEX","DSL"]);
const uncertain=(warning="ARCHETYPE_UNCERTAIN")=>({archetype:ARCHETYPES.CONSERVATIVE_UNKNOWN,confidence:35,warnings:[warning]});
export function classifyPlayerArchetype(input,evidence={}){
  const pos=input.positionEligibility?.eligible||[],pitch=pos.some(x=>["SP","RP"].includes(x)),hit=pos.some(x=>!["SP","RP"].includes(x));
  const prospect=input.prospectContext||{},development=input.ageDevelopment||{},minor=input.player?.isMinorLeaguer,level=upper(prospect.level??development.level),availability=upper(prospect.levelAvailability??development.levelAvailability),mlbStatus=upper(input.role?.mlbStatus),available=availability==="AVAILABLE",minorLevel=NEAR_MLB_LEVELS.has(level)||DISTANT_PROSPECT_LEVELS.has(level);
  if(availability==="CONFLICT")return uncertain("ARCHETYPE_LEVEL_CONFLICT");
  if(available&&((level==="MLB"&&(minor===true||mlbStatus==="MINORS"))||(minorLevel&&(minor===false||mlbStatus==="MLB"))))return uncertain("ARCHETYPE_CONTEXT_CONTRADICTION");
  if(available&&minor===true&&NEAR_MLB_LEVELS.has(level))return {archetype:ARCHETYPES.NEAR_MLB_PROSPECT,confidence:95,warnings:[]};
  if(available&&minor===true&&DISTANT_PROSPECT_LEVELS.has(level))return {archetype:ARCHETYPES.DISTANT_PROSPECT,confidence:95,warnings:[]};
  if(minor===true)return uncertain(level==="INACTIVE"?"ARCHETYPE_INACTIVE":"ARCHETYPE_LEVEL_UNKNOWN");
  const factualMlb=(available&&level==="MLB")||(mlbStatus==="MLB"&&availability!=="CONFLICT"&&!minorLevel);
  if(!factualMlb)return uncertain(level==="INACTIVE"?"ARCHETYPE_INACTIVE":"ARCHETYPE_STATUS_UNKNOWN");
  if(pitch&&hit)return {archetype:ARCHETYPES.TWO_WAY_DEFERRED,confidence:0,warnings:["TWO_WAY_COMPOSITE_DEFERRED"]};
  const rawAge=input.player?.age,age=rawAge===null||rawAge===undefined||rawAge===""?null:Number(rawAge),recent=upper(evidence.recentTransition)==="PROMOTED";
  if(recent||(Number.isFinite(age)&&age<=24))return {archetype:ARCHETYPES.YOUNG_MLB_OR_RECENT_CALLUP,confidence:recent?95:85,warnings:[]};
  if(Number.isFinite(age)&&age>=33)return {archetype:ARCHETYPES.MLB_VETERAN,confidence:90,warnings:[]};
  if(pos.includes("RP")&&!pos.includes("SP"))return {archetype:ARCHETYPES.MLB_RELIEVER,confidence:85,warnings:[]};
  if(pos.includes("SP"))return {archetype:ARCHETYPES.MLB_STARTING_PITCHER,confidence:85,warnings:[]};
  if(hit)return {archetype:ARCHETYPES.MLB_HITTER,confidence:85,warnings:[]};
  return uncertain();
}
function signalCodes(result){return (result.signals||[]).map(x=>x.code)}
export function evaluatePlayerIntelligenceComposite({input,result,marketPercentile=null}={}){if(!input?.playerId||!result?.components)throw new Error("Canonical input and completed component result are required.");const classification=classifyPlayerArchetype(input,result.contextEvidence||result.evidence||{});if(classification.archetype===ARCHETYPES.TWO_WAY_DEFERRED)return {playerId:input.playerId,leagueId:input.leagueId,archetype:classification.archetype,overallPlayerIntelligence:{score:null,confidence:0},floor:null,expected:null,ceiling:null,componentContributions:[],strengths:[],risks:[],warnings:classification.warnings,market:{normalizedMarketValue:marketPercentile,divergence:"MARKET_DATA_UNAVAILABLE",gap:null},dataCoverage:{applicableComponents:[],calculatedComponents:[],missingComponents:[],staleComponents:[]}};
  const matrix=ARCHETYPE_MATRIX[classification.archetype]||ARCHETYPE_MATRIX.CONSERVATIVE_UNKNOWN,rows=[],missing=[],stale=[];let expectedBase=0,confidenceNumerator=0;
  for(const [code,rule] of Object.entries(matrix)){if(rule.applicability===APPLICABILITY.NOT_APPLICABLE||rule.weight<=0)continue;expectedBase+=rule.weight;const component=code==="marketSupport"?{score:marketPercentile,confidence:num(marketPercentile)?70:0,status:num(marketPercentile)?"CALCULATED":"INSUFFICIENT_DATA"}:result.components[code],raw=component?.score,confidence=num(component?.confidence)?clamp(component.confidence):0;if(component?.status==="STALE")stale.push(code);if(!num(raw)){if(rule.applicability===APPLICABILITY.REQUIRED)missing.push(code);continue}const score=code==="risk"?100-raw:raw,effectiveWeight=rule.weight*(confidence/100),direction=code==="risk"?"HIGHER_IS_MORE_RISK_TRANSFORMED_TO_SAFETY":code==="prospectOpportunityCost"?PROSPECT_OPPORTUNITY_COST_DIRECTION:"HIGHER_IS_BETTER";rows.push({component:code,applicability:rule.applicability,direction,rawScore:raw,compositeScore:clamp(score),baseWeight:rule.weight,confidence,effectiveWeight});confidenceNumerator+=rule.weight*confidence}
  const effectiveTotal=rows.reduce((s,x)=>s+x.effectiveWeight,0);if(!effectiveTotal)return {...classification,playerId:input.playerId,leagueId:input.leagueId,overallPlayerIntelligence:{score:null,confidence:0},floor:null,expected:null,ceiling:null,componentContributions:rows,strengths:[],risks:[],warnings:[...classification.warnings,"COMPOSITE_EVIDENCE_INSUFFICIENT"],market:{normalizedMarketValue:marketPercentile,divergence:"MARKET_DATA_UNAVAILABLE",gap:null},dataCoverage:{applicableComponents:Object.keys(matrix).filter(k=>matrix[k].applicability!==APPLICABILITY.NOT_APPLICABLE),calculatedComponents:[],missingComponents:missing,staleComponents:stale}};
  for(const row of rows){row.normalizedWeight=100*row.effectiveWeight/effectiveTotal;row.contribution=row.compositeScore*row.normalizedWeight/100}
  const expected=clamp(rows.reduce((s,x)=>s+x.contribution,0)),requiredPenalty=missing.length*10,stalePenalty=stale.length*5,confidence=clamp(confidenceNumerator/Math.max(1,expectedBase)-(100-classification.confidence)*.25-requiredPenalty-stalePenalty),codes=signalCodes(result),riskRaw=result.components.risk?.score||0,role=result.components.roleStability?.score||50,age=result.components.ageTrajectory?.score||50,prospect=result.components.prospectOpportunityCost?.score;
  const downside=Math.min(30,5+riskRaw*.12+(100-confidence)*.08+(100-role)*.04+(codes.includes("REGRESSION_RISK")?4:0)),upside=Math.min(25,5+age*.05+(codes.includes("BREAKOUT_SIGNAL")?5:0)+(num(prospect)?4:0));const floor=clamp(expected-downside),ceiling=clamp(expected+upside);
  const ranked=[...rows].sort((a,b)=>b.contribution-a.contribution),strengths=ranked.filter(x=>x.compositeScore>=65).slice(0,3).map(x=>({code:`STRONG_${upper(x.component)}`,component:x.component,score:x.compositeScore,contribution:clamp(x.contribution)})),risks=[...ranked.filter(x=>x.compositeScore<45).slice(0,3).map(x=>({code:`WEAK_${upper(x.component)}`,component:x.component,score:x.compositeScore})),...missing.map(component=>({code:"MISSING_REQUIRED_COMPONENT",component}))];
  const gap=num(marketPercentile)?round(expected-marketPercentile):null,divergence=!num(marketPercentile)?"MARKET_DATA_UNAVAILABLE":gap>=15?"UNDERVALUED_BY_MARKET":gap<=-15?"OVERVALUED_BY_MARKET":"ALIGNED_WITH_MARKET";
  return {playerId:input.playerId,leagueId:input.leagueId,archetype:classification.archetype,overallPlayerIntelligence:{score:expected,confidence},floor,expected,ceiling,componentContributions:rows,strengths,risks,warnings:[...classification.warnings,...missing.map(x=>`MISSING_REQUIRED_${upper(x)}`),...stale.map(x=>`STALE_${upper(x)}`)],market:{normalizedMarketValue:marketPercentile,divergence,gap},dataCoverage:{applicableComponents:Object.keys(matrix).filter(k=>matrix[k].applicability!==APPLICABILITY.NOT_APPLICABLE),calculatedComponents:rows.map(x=>x.component),missingComponents:missing,staleComponents:stale}}}
export function buildMarketPercentileContext(inputs){return buildExactPercentileContext(inputs.map(x=>x.market?.value))}
export function evaluatePlayerIntelligenceCompositePopulation(inputs,results){const byId=new Map(results.map(x=>[x.playerId,x.output||x])),marketContext=buildMarketPercentileContext(inputs);return inputs.map(input=>evaluatePlayerIntelligenceComposite({input,result:byId.get(input.playerId),marketPercentile:exactPercentile(input.market?.value,marketContext)}))}
