import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const importService=await readFile(new URL("../js/services/cloudCsvImportService.js",import.meta.url),"utf8");
const cloudStore=await readFile(new URL("../js/services/cloudStore.js",import.meta.url),"utf8");
const authUi=await readFile(new URL("../js/services/authUi.js",import.meta.url),"utf8");

const fantraxStart=importService.indexOf("async function importFantrax");
const hkbStart=importService.indexOf("async function importHkb");
const previewFantraxStart=importService.indexOf("async function previewFantrax");
const backfillStart=importService.indexOf("export async function dryRunFantraxIdBackfill");
assert.ok(fantraxStart>=0,"importFantrax must exist");
assert.ok(hkbStart>fantraxStart,"importHkb must follow importFantrax for scoped inspection");
assert.ok(previewFantraxStart>=0,"previewFantrax must exist");
assert.ok(backfillStart>previewFantraxStart,"backfill should follow previewFantrax for scoped inspection");

const fantraxBody=importService.slice(fantraxStart,hkbStart);
const previewFantraxBody=importService.slice(previewFantraxStart,backfillStart);

assert.match(importService,/import \{ PlayerIdentityResolver \} from "\.\/PlayerIdentityResolver\.js";/);
assert.match(importService,/import \{ InMemoryPlayerIdentityRepository \} from "\.\/identity\/InMemoryPlayerIdentityRepository\.js";/);
assert.match(fantraxBody,/new PlayerIdentityResolver\(\{repository:new InMemoryPlayerIdentityRepository\(maps\.players\)\}\)/);
assert.match(fantraxBody,/classifyFantraxRows\(playerRows,resolver\)/);
assert.match(importService,/function buildFantraxPlayerRows\(rows,ix,leagueId,maps,startRowNumber=2\)/);
assert.match(fantraxBody,/buildFantraxPlayerRows\(batch,ix,leagueId,maps,processed\+2\)/);
assert.match(fantraxBody,/cloudStore\.syncResolvedPlayers/);
assert.match(importService,/function collapseResolvedUpdates\(updates\)/);
assert.match(fantraxBody,/duplicateResolvedUpdatesCollapsed/);
assert.match(importService,/multiple_source_players_resolved_to_same_internal_id/);
assert.match(importService,/sourceRowSummary/);
assert.match(importService,/export function buildFantraxPreviewSummary/);
assert.match(previewFantraxBody,/buildFantraxPreviewSummary\(\{leagueId,file,rows,head,maps\}\)/);
assert.ok(!previewFantraxBody.includes("playerMatch("),"Fantrax preview must not use legacy playerMatch");
assert.match(importService,/existingCloudMatches/);
assert.match(importService,/newPlayersToInsert/);
assert.match(importService,/cloudPlayersLoaded/);
assert.match(importService,/previewPlayerCollectionSource:"cloud players"/);
assert.match(authUi,/previewSchema==="fantrax-identity-v2"/);
assert.match(authUi,/Existing cloud matches/);
assert.match(authUi,/New players to insert/);
assert.match(authUi,/Identity conflicts/);
assert.match(authUi,/Cloud players loaded/);
assert.ok(!fantraxBody.includes("cloudStore.syncPlayers"),"Fantrax import must not use legacy syncPlayers");
assert.match(cloudStore,/export async function syncResolvedPlayers/);
assert.match(cloudStore,/export async function getPlayers\(leagueId,\{pageSize=1000,supabaseClient=null\}=\{\}\)/);
assert.match(cloudStore,/\.order\("id",\{ascending:true\}\)\s*\.range\(from,to\)/);
assert.match(cloudStore,/Player preload failed at range \$\{from\}-\$\{to\}: \$\{result\.error\.message\}/);
assert.match(cloudStore,/Resolved update batch contains duplicate player IDs/);
assert.match(cloudStore,/const duplicateUpdateIds=duplicateIds\(updates\)/);
assert.match(cloudStore,/export function stripPlayerUpdateRow\(row\)/);
assert.match(cloudStore,/if\("fantrax_id" in out\)/);
assert.match(cloudStore,/if\("mlbam_id" in out&&out\.mlbam_id===null\)delete out\.mlbam_id/);
assert.match(cloudStore,/const preparedUpdates=prepareResolvedPlayerUpdateRows\(updates,existingRows\)/);
assert.match(cloudStore,/from\("players"\)\.upsert\(preparedUpdates,\{onConflict:"id"\}\)\.select\("\*"\)/);
assert.match(cloudStore,/from\("players"\)\.insert\(stripPlayerInsertRows\(inserts\)\)\.select\("\*"\)/);
assert.doesNotMatch(cloudStore,/onConflict:"normalized_name"|onConflict:"league_id,normalized_name"/);
assert.doesNotMatch(cloudStore,/localStorage\.setItem\([^)]*players/i);
assert.match(importService,/const BATCH_SIZE=150/);
assert.match(importService,/for\(const batch of chunk\(rows\)\)/);
assert.match(importService,/saved\.forEach\(p=>rememberPlayer\(maps,p\)\)/);
assert.match(importService,/resolver=new PlayerIdentityResolver\(\{repository:new InMemoryPlayerIdentityRepository\(maps\.players\)\}\)/);
assert.match(authUi,/function stageErrorMessage\(stage,error,fallback\)/);
assert.match(authUi,/stageErrorMessage\("Parsing",e,"Preview failed\."\)/);
assert.match(authUi,/const failedStage=importState\.stages\[step\]\|\|"Cloud import"/);
assert.match(authUi,/stageErrorMessage\(failedStage,e,"Cloud import failed\."\)/);
assert.match(authUi,/exceptionDetails:\[detail\]/);
assert.match(authUi,/errors:1/);
assert.match(authUi,/failureReason:message/);
assert.match(authUi,/console\.error\("\[Cloud Import\] Fantrax preview failed",e\)/);
assert.match(authUi,/console\.error\("\[Cloud Import\] Fantrax import failed",e\)/);
assert.ok(!authUi.includes("Parsing failed."),"Fantrax errors must include the underlying exception instead of only Parsing failed.");

console.log("fantraxImportPipeline tests passed");
