import {ARCHETYPE_MATRIX,APPLICABILITY} from "../v5/js/engine/playerIntelligenceComposite.js";

const COMPONENTS=Object.freeze([
  "leagueProduction","underlyingSkill","roleStability","ageTrajectory",
  "prospectOpportunityCost","risk","replacementAdvantage","positionalScarcityValue","marketSupport"
]);
const num=value=>typeof value==="number"&&Number.isFinite(value);
const round=value=>num(value)?Math.round(value*100)/100:null;
const sorted=values=>values.filter(num).sort((a,b)=>a-b);
const percentile=(values,p)=>{const rows=sorted(values);if(!rows.length)return null;const index=(rows.length-1)*p,low=Math.floor(index),high=Math.ceil(index);return round(rows[low]+(rows[high]-rows[low])*(index-low))};
const mean=values=>{const rows=values.filter(num);return rows.length?round(rows.reduce((sum,value)=>sum+value,0)/rows.length):null};
const median=values=>percentile(values,.5);
const correlation=(xs,ys)=>{const pairs=xs.map((x,index)=>[x,ys[index]]).filter(([x,y])=>num(x)&&num(y));if(pairs.length<2)return null;const mx=mean(pairs.map(x=>x[0])),my=mean(pairs.map(x=>x[1])),numerator=pairs.reduce((sum,[x,y])=>sum+(x-mx)*(y-my),0),dx=Math.sqrt(pairs.reduce((sum,[x])=>sum+(x-mx)**2,0)),dy=Math.sqrt(pairs.reduce((sum,[,y])=>sum+(y-my)**2,0));return dx&&dy?round(numerator/(dx*dy)):null};

function summarize(values){return {count:values.filter(num).length,mean:mean(values),median:median(values),p25:percentile(values,.25),p75:percentile(values,.75),p90:percentile(values,.9),max:sorted(values).at(-1)??null}}
function applicable(archetype,component){const rule=ARCHETYPE_MATRIX[archetype]?.[component];return Boolean(rule&&rule.applicability!==APPLICABILITY.NOT_APPLICABLE&&rule.weight>0)}
function componentSummary(records,component){
  const relevant=records.filter(row=>applicable(row.archetype,component)),available=relevant.filter(row=>num(row.components[component]?.compositeScore)),missing=relevant.filter(row=>!num(row.components[component]?.compositeScore));
  return {applicable:relevant.length,available:available.length,missing:missing.length,zeroConfidence:available.filter(row=>(row.components[component]?.confidence??0)===0).length,score:summarize(available.map(row=>row.components[component].compositeScore)),confidence:summarize(available.map(row=>row.components[component].confidence)),effectiveContribution:summarize(available.map(row=>row.components[component].contribution)),normalizedWeight:summarize(available.map(row=>row.components[component].normalizedWeight))};
}
function dominant(row){return Object.values(row.components).filter(component=>num(component?.contribution)).sort((a,b)=>b.contribution-a.contribution||a.component.localeCompare(b.component))[0]?.component??null}
function scoreSummary(records){return {count:records.length,floor:summarize(records.map(row=>row.floor)),expected:summarize(records.map(row=>row.expected)),ceiling:summarize(records.map(row=>row.ceiling)),rangeWidth:summarize(records.map(row=>num(row.ceiling)&&num(row.floor)?row.ceiling-row.floor:null))}}
function compact(row){return {playerId:row.playerId,name:row.identity.name,archetype:row.archetype,evidence:row.overallConfidence,expected:row.expected,floor:row.floor,ceiling:row.ceiling,dominantComponent:dominant(row),components:Object.fromEntries(Object.entries(row.components).map(([code,value])=>[code,{score:value.compositeScore,confidence:value.confidence,normalizedWeight:value.normalizedWeight,contribution:value.contribution}]))}}
function evidenceBucket(value,bounds){if(!num(value))return "VERY_LOW";if(value<=bounds.p25)return "VERY_LOW";if(value<=bounds.p50)return "LOW";if(value<=bounds.p75)return "MEDIUM";return "HIGH"}
function byArchetype(records,inputsById){return Object.fromEntries([...new Set(records.map(row=>row.archetype))].sort().map(archetype=>{const rows=records.filter(row=>row.archetype===archetype),skillApplicable=rows.filter(row=>applicable(archetype,"underlyingSkill")),statcastAccepted=skillApplicable.filter(row=>inputsById.get(row.playerId)?.underlyingSkill?.source==="Statcast"&&["AVAILABLE","STALE"].includes(inputsById.get(row.playerId)?.underlyingSkill?.status));return [archetype,{count:rows.length,percentage:round(100*rows.length/records.length),statcast:{applicable:skillApplicable.length,accepted:statcastAccepted.length,genuineMissing:skillApplicable.length-statcastAccepted.length,falseMissing:statcastAccepted.filter(row=>!num(row.components.underlyingSkill?.compositeScore)).length,notApplicable:rows.length-skillApplicable.length},components:Object.fromEntries(COMPONENTS.map(component=>[component,componentSummary(rows,component)])),dominantComponents:Object.fromEntries(COMPONENTS.map(component=>[component,rows.filter(row=>dominant(row)===component).length])),scores:scoreSummary(rows)}]}))}

export function buildCalibrationDiagnostic({inspection,inputs=[]}={}){
  if(!inspection?.players||!Array.isArray(inputs))throw new Error("Completed inspection and canonical inputs are required.");
  const records=inspection.players,inputsById=new Map(inputs.map(input=>[input.playerId,input])),confidence=records.map(row=>row.overallConfidence).filter(num),bounds={p25:percentile(confidence,.25),p50:percentile(confidence,.5),p75:percentile(confidence,.75)},buckets={};
  for(const code of ["VERY_LOW","LOW","MEDIUM","HIGH"]){const rows=records.filter(row=>evidenceBucket(row.overallConfidence,bounds)===code);buckets[code]={...scoreSummary(rows),ageContribution:summarize(rows.map(row=>row.components.ageTrajectory?.contribution)),riskSafetyContribution:summarize(rows.map(row=>row.components.risk?.contribution)),dominantComponents:Object.fromEntries(COMPONENTS.map(component=>[component,rows.filter(row=>dominant(row)===component).length]))}}
  const meaningfulCount=row=>Object.values(row.components).filter(component=>num(component?.compositeScore)&&Number(component.confidence)>0).length,componentCounts=Object.fromEntries([0,1,2,3,4,5].map(count=>{const rows=records.filter(row=>count===5?meaningfulCount(row)>=5:meaningfulCount(row)===count);return [count===5?"5+":String(count),scoreSummary(rows)]}));
  const lowRows=records.filter(row=>evidenceBucket(row.overallConfidence,bounds)==="VERY_LOW"),rank=(rows,key)=>[...rows].filter(row=>num(row[key])).sort((a,b)=>b[key]-a[key]||a.playerId.localeCompare(b.playerId)).slice(0,25).map(compact),roles={starter:records.filter(row=>row.archetype==="MLB_STARTING_PITCHER"),reliever:records.filter(row=>row.archetype==="MLB_RELIEVER"),mlbHitter:records.filter(row=>["MLB_HITTER","YOUNG_MLB_OR_RECENT_CALLUP","MLB_VETERAN"].includes(row.archetype)),prospect:records.filter(row=>["NEAR_MLB_PROSPECT","DISTANT_PROSPECT"].includes(row.archetype))};
  const roleSummary=rows=>({count:rows.length,scores:scoreSummary(rows),leagueProduction:componentSummary(rows,"leagueProduction"),underlyingSkill:componentSummary(rows,"underlyingSkill"),roleStability:componentSummary(rows,"roleStability"),overallConfidence:summarize(rows.map(row=>row.overallConfidence)),dominantComponents:Object.fromEntries(COMPONENTS.map(component=>[component,rows.filter(row=>dominant(row)===component).length]))});
  const invariantViolations=records.filter(row=>num(row.floor)&&num(row.expected)&&num(row.ceiling)&&!(row.floor<=row.expected&&row.expected<=row.ceiling)).map(row=>row.playerId),zeroEvidence=records.filter(row=>(row.overallConfidence??0)<=0),nearZeroEvidence=records.filter(row=>(row.overallConfidence??0)<=10);
  return {schema:"player-intelligence-calibration-diagnostic-v1",population:{count:records.length},evidence:{measure:"overallPlayerIntelligence.confidence",bucketMethod:"inclusive population quartiles",bounds,buckets,correlation:{expected:correlation(records.map(row=>row.overallConfidence),records.map(row=>row.expected)),ceiling:correlation(records.map(row=>row.overallConfidence),records.map(row=>row.ceiling))},zero:scoreSummary(zeroEvidence),nearZero:scoreSummary(nearZeroEvidence)},byArchetype:byArchetype(records,inputsById),componentCounts,roles:Object.fromEntries(Object.entries(roles).map(([code,rows])=>[code,roleSummary(rows)])),top:{expected:rank(records,"expected"),ceiling:rank(records,"ceiling"),veryLowExpected:rank(lowRows,"expected"),veryLowCeiling:rank(lowRows,"ceiling")},invariants:{floorExpectedCeilingViolations:invariantViolations},renormalization:{formula:"effectiveWeight = baseWeight * confidence / 100; normalizedWeight = 100 * effectiveWeight / sum(effectiveWeight); expected = sum(compositeScore * normalizedWeight / 100)",minimumEvidenceFloor:false},calibrationDecision:inspection.calibrationDecision};
}
