import assert from "node:assert/strict";
import { readdir, readFile } from "node:fs/promises";

const root=new URL("../v5/",import.meta.url);
const html=await readFile(new URL("index.html",root),"utf8");
const main=await readFile(new URL("js/main.js",root),"utf8");
const state=await readFile(new URL("js/state/appState.js",root),"utf8");
const engine=await readFile(new URL("js/engine/playerEngine.js",root),"utf8");
const dynastyEngine=await readFile(new URL("js/engine/dynastyEngine.js",root),"utf8");
const imports=await readFile(new URL("js/imports/cloudImportController.js",root),"utf8");
const dataHealth=await readFile(new URL("js/services/dataHealthService.js",root),"utf8");
const decisionService=await readFile(new URL("js/services/decisionIntelligenceService.js",root),"utf8");
const tradeService=await readFile(new URL("js/services/tradeAnalysisService.js",root),"utf8");
const settingsView=await readFile(new URL("js/views/settingsDataHealthView.js",root),"utf8");
const cloudData=await readFile(new URL("js/services/cloudDataService.js",root),"utf8");
const baseRepository=await readFile(new URL("js/repositories/baseRepository.js",root),"utf8");
const playerRepository=await readFile(new URL("js/repositories/playerRepository.js",root),"utf8");
const playerIntelligenceRepository=await readFile(new URL("js/repositories/playerIntelligenceRepository.js",root),"utf8");
const metricRepository=await readFile(new URL("js/repositories/metricRepository.js",root),"utf8");
const scoreRepository=await readFile(new URL("js/repositories/scoreRepository.js",root),"utf8");
const importsView=await readFile(new URL("js/views/importsView.js",root),"utf8");
const rosterView=await readFile(new URL("js/views/rosterView.js",root),"utf8");
const waiverView=await readFile(new URL("js/views/waiverOpportunitiesView.js",root),"utf8");
const tradeView=await readFile(new URL("js/views/tradeCenterView.js",root),"utf8");
const playersView=await readFile(new URL("js/views/playersView.js",root),"utf8");
const teamRules=await readFile(new URL("js/domain/teamRules.js",root),"utf8");
const rosterStatus=await readFile(new URL("js/domain/rosterStatus.js",root),"utf8");
const repositories=await readdir(new URL("js/repositories/",root));

["css/styles.css","js/main.js"].forEach(path=>assert.match(html,new RegExp(path.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"))));
assert.match(html,/Version 5 is under construction\. The existing application remains available separately\./);
["Dashboard","Players","Waiver Opportunities","Trade Center","My Roster","Teams & Managers","Cloud Imports","Settings & Data Health"].forEach(label=>assert.match(html,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"))));
["Waiver Finder","Waiver Hunter","Market Edges","Decision Engine","Package Builder","Portfolio","Trends","Scout"].forEach(label=>assert.doesNotMatch(html,new RegExp(label)));

["playerRepository.js","teamRepository.js","managerRepository.js","metricRepository.js","scoreRepository.js","tradeRepository.js","importJobRepository.js"].forEach(file=>assert.ok(repositories.includes(file),`${file} must exist`));
assert.match(state,/dataMode:"offline"/);
assert.match(state,/players:\[\]/);
assert.match(state,/teams:\[\]/);
assert.match(state,/managers:\[\]/);
assert.match(state,/const ACTIVE_LEAGUE_KEY="dynasty_active_league_id"/);
assert.doesNotMatch(state,/dynasty_players|dynasty_managers|dynasty_trades/);

assert.match(main,/loadLeagueOverview/);
assert.match(main,/listPlayerIntelligence\(appState\.activeLeague\.id,query\)/);
assert.match(main,/if\(requestId!==playerRequestId\)return null/);
assert.match(main,/pageSize:50/);
assert.match(main,/playerIntelligenceByIds/);
assert.match(main,/selectedRosterTeamId/);
assert.match(main,/data-import-reviewed/);
assert.match(main,/data-health-detail/);
assert.match(main,/renderMyRoster/);
assert.match(main,/renderWaiverOpportunities/);
assert.match(main,/getWaiverRecommendations/);
assert.match(main,/findRosterUpgradeCandidates/);
assert.match(main,/renderTradeCenter/);
assert.match(main,/analyzeTrade/);
assert.match(main,/renderTeamsManagers/);
assert.match(main,/renderImports/);
assert.match(main,/renderSettingsDataHealth/);

assert.match(imports,/previewImport/);
assert.match(imports,/runImport/);
assert.match(imports,/Fantrax Players \/ Rosters/);
assert.match(imports,/HarryKnowsBall/);
assert.match(imports,/Statcast Hitters/);
assert.match(imports,/Statcast Pitchers/);
assert.match(imports,/Trade History/);
assert.match(imports,/Manager Intelligence/);

assert.match(engine,/export async function recalculateLeagueScores\(leagueId,\{onProgress=\(\)=>\{\}\}=\{\}\)/);
assert.match(engine,/calculateLeagueScores/);
assert.match(dynastyEngine,/export async function calculateLeagueScores\(leagueId,options=\{\}\)/);
assert.match(dynastyEngine,/upsertScores/);
assert.match(dynastyEngine,/ENGINE_VERSION="5\.1\.1"/);
assert.match(baseRepository,/export async function selectAllLeagueRows/);
assert.match(baseRepository,/if\(order!==\"id\"\)query=query\.order\(\"id\",\{ascending:true\}\)/);
assert.match(baseRepository,/\.range\(from,from\+pageSize-1\)/);
assert.match(playerRepository,/allPlayers\(leagueId\)\{\s*return selectAllLeagueRows\("players"/);
assert.match(metricRepository,/listMetrics\(leagueId\)\{\s*return selectAllLeagueRows\("player_metrics"/);
assert.match(scoreRepository,/listScores\(leagueId\)\{\s*return selectAllLeagueRows\("calculated_player_scores"/);
assert.match(playerIntelligenceRepository,/calculated_player_scores/);
assert.match(playerIntelligenceRepository,/players!inner/);
assert.match(playerIntelligenceRepository,/order\("player_id",\{ascending:true\}\)/);
assert.match(engine,/BATCH_SIZE=200/);
assert.match(dynastyEngine,/elapsedMs/);
assert.match(dynastyEngine,/updated:upserted/);
["ageCurve","scarcity","championshipImpact","marketAppreciation","tradeLiquidity","risk","ceiling","floor","breakout","portfolioFit","leagueFit","overallScore","playerStage","confidence"].forEach(name=>assert.match(dynastyEngine,new RegExp(name)));
assert.match(dynastyEngine,/metadata:\{/);
assert.match(decisionService,/DECISION_RULE_VERSION="5\.3\.0"/);
assert.match(decisionService,/listPlayerIntelligence/);
assert.doesNotMatch(decisionService,/calculatePlayerScores|calculateLeagueScores/);
assert.match(tradeService,/TRADE_ANALYSIS_VERSION="5\.4\.0"/);
assert.match(tradeService,/playerIntelligenceByIds/);
assert.match(tradeService,/listPlayerIntelligence/);
assert.doesNotMatch(tradeService,/calculatePlayerScores|calculateLeagueScores|dynastyEngine/);
assert.match(settingsView,/id="recalculateEngine"/);
assert.equal((settingsView.match(/recalculateEngine/g)||[]).length,1);
assert.doesNotMatch(playersView,/recalculateEngine|Recalculate Player Engine/);
assert.doesNotMatch(rosterView,/recalculateEngine|Recalculate Player Engine/);

assert.doesNotMatch(cloudData,/players\.allPlayers\(leagueId\)/);
assert.match(cloudData,/playerCount/);
assert.match(cloudData,/rosterSummaryRows/);
assert.match(cloudData,/fantraxIdCount/);
assert.match(cloudData,/mlbamIdCount/);
assert.match(teamRules,/isValidFantasyTeam/);
assert.match(teamRules,/invalidFantasyTeamReason/);
assert.match(rosterStatus,/normalizeRosterStatus/);
assert.match(playersView,/id="playerSort"/);
assert.match(playersView,/Player Intelligence Explorer/);
assert.match(playersView,/data-player-detail/);
assert.match(playersView,/data-compare-player/);
assert.match(playersView,/Raw Diagnostics/);
assert.match(rosterView,/Unclassified/);
assert.match(rosterView,/Refresh Recommendations/);
assert.match(waiverView,/Waiver Opportunities/);
assert.match(waiverView,/data-waiver-upgrade/);
assert.match(tradeView,/Trade Center/);
assert.match(tradeView,/Analyze Trade/);
assert.doesNotMatch(tradeView,/calculatePlayerScores|calculateLeagueScores|dynastyEngine/);
assert.doesNotMatch(rosterView,/status===""\)return"Active"/);
assert.doesNotMatch(rosterView,/teams\[0\]\?\.id/);
assert.match(importsView,/data-import-reviewed/);
assert.match(importsView,/I reviewed this preview/);
assert.match(importsView,/importState\.previews\?\.\[item\.key\]&&importState\.reviewed\?\.\[item\.key\]/);
assert.match(importsView,/import-grid/);
assert.match(importsView,/import-card/);
assert.match(settingsView,/data-health-detail/);
assert.match(settingsView,/healthPrev/);
assert.match(settingsView,/healthNext/);

["league exists","membership exists","player count","Expected valid team count = 10","Excluded invalid team rows","Actual manager count","Teams without managers","Players missing Fantrax ID","Players missing MLBAM ID","Players missing both external IDs","Roster Status Diagnostics","Unknown roster status values","owner_team_id","free agents","Duplicate Fantrax IDs","Duplicate MLBAM IDs","Duplicate normalized names","Orphaned metrics","Orphaned scores","Calculated score coverage","Latest engine version","Latest calculation time","Players needing recalculation","Invalid numeric values","Team-manager links","RLS access"].forEach(text=>assert.match(dataHealth,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i")));
assert.match(dataHealth,/status:[^,\n]+WARNING/);

console.log("v5Architecture tests passed");
