import assert from "node:assert/strict";
import fs from "node:fs";
import {controlledFantraxRosterSelection,fantraxRosterSyncPeriodGuard,fantraxRosterSyncSkipReason,fantraxRosterSyncSummary,reviewedFantraxStatusUpdates,validateControlledFantraxStatusUpdates,validateReviewedFantraxStatusUpdates} from "../v5/js/services/fantraxRosterSyncService.js";
import {renderFantraxPreview} from "../v5/js/views/fantraxPreviewView.js";

const eligible={futureSyncRecommendation:"APPLY_FANTRAX_STATUS",matchedPlayerUuid:"p1",matchedPlayer:{name:"Alpha"},matchedTeamUuid:"team-1",currentOwnerTeamId:"team-1",currentRosterStatus:"RESERVE",normalizedRosterStatus:"ACTIVE",fantraxApiPlayerId:"F1",fantraxTeamId:"T1",playerIdentityResult:"MATCHED",teamIdentityResult:"MATCHED",activeManualOverride:false};
const manual={...eligible,matchedPlayerUuid:"p2",matchedPlayer:{name:"Manual"},futureSyncRecommendation:"PRESERVE_MANUAL_OVERRIDE",activeManualOverride:true};
const unknown={...eligible,matchedPlayerUuid:"p3",matchedPlayer:{name:"Unknown"},futureSyncRecommendation:"REVIEW_CONFLICT",normalizedRosterStatus:"UNCLASSIFIED"};
assert.deepEqual(reviewedFantraxStatusUpdates([eligible,manual,unknown]),[{id:"p1",name:"Alpha",currentRosterStatus:"RESERVE",roster_status:"ACTIVE",expectedOwnerTeamId:"team-1",fantraxApiPlayerId:"F1",fantraxTeamId:"T1"}]);
assert.equal(validateReviewedFantraxStatusUpdates([eligible,manual,unknown]).valid,true);
assert.equal(validateReviewedFantraxStatusUpdates([manual,unknown]).valid,false,"no eligible rows cannot be applied");
assert.match(validateReviewedFantraxStatusUpdates([eligible,{...eligible}]).errors.join(" "),/more than once/);
assert.match(validateReviewedFantraxStatusUpdates([{...eligible,teamIdentityResult:"UNMAPPED"}]).errors.join(" "),/Team identity/);
assert.match(validateReviewedFantraxStatusUpdates([{...eligible,activeManualOverride:true}]).errors.join(" "),/Manual override/);
assert.match(validateReviewedFantraxStatusUpdates([{...eligible,ownershipDifference:true}]).errors.join(" "),/ownership differs/i);
assert.equal(reviewedFantraxStatusUpdates([{...eligible,ownershipDifference:true,futureSyncRecommendation:"REVIEW_CONFLICT"}]).length,0);
assert.match(validateReviewedFantraxStatusUpdates([{...eligible,currentOwnerTeamId:"other-team"}]).errors.join(" "),/Expected cloud owner/);
assert.deepEqual(fantraxRosterSyncPeriodGuard(""),{valid:true,error:""});
assert.equal(fantraxRosterSyncPeriodGuard("131").valid,false);
assert.match(fantraxRosterSyncPeriodGuard("131").error,/historical scoring period 131/);
assert.deepEqual(controlledFantraxRosterSelection([],"p1",true),{selectedIds:["p1"],error:""});
assert.deepEqual(controlledFantraxRosterSelection(["p1","p2","p3"],"p4",true),{selectedIds:["p1","p2","p3"],error:"Controlled acceptance is limited to 3 players."});
assert.deepEqual(controlledFantraxRosterSelection(["p1","p2"],"p1",false),{selectedIds:["p2"],error:""});
assert.equal(validateControlledFantraxStatusUpdates([eligible],["p1"]).valid,true);
assert.equal(validateControlledFantraxStatusUpdates([eligible],[]).valid,false);
assert.match(validateControlledFantraxStatusUpdates([eligible],["p1","p2","p3","p4"]).errors.join(" "),/limited to 3/);
assert.match(validateControlledFantraxStatusUpdates([eligible],["not-eligible"]).errors.join(" "),/not present/);

const manifest=reviewedFantraxStatusUpdates([eligible])[0];
assert.equal(fantraxRosterSyncSkipReason(manifest,{owner_team_id:"team-1",roster_status:"RESERVE",roster_status_source:"MANUAL"}),"MANUAL_OVERRIDE");
assert.equal(fantraxRosterSyncSkipReason(manifest,{owner_team_id:"other-team",roster_status:"RESERVE",roster_status_source:"UNKNOWN"}),"OWNER_CHANGED");
assert.equal(fantraxRosterSyncSkipReason(manifest,{owner_team_id:"team-1",roster_status:"ACTIVE",roster_status_source:"UNKNOWN"}),"STATUS_CHANGED");
assert.equal(fantraxRosterSyncSkipReason(manifest,null),"NOT_FOUND_OR_DENIED");
assert.equal(fantraxRosterSyncSkipReason(manifest,{owner_team_id:"team-1",roster_status:"RESERVE",roster_status_source:"UNKNOWN"},{writeFailed:true}),"WRITE_FAILED_OR_NOT_ATTEMPTED");
assert.deepEqual(fantraxRosterSyncSummary({reviewed:3,updated:[{id:"p1"}],skipped:[{reason:"OWNER_CHANGED"},{reason:"OWNER_CHANGED"}],failures:[{}]}),{reviewed:3,updated:1,skipped:2,failedGroups:1,skipReasons:{OWNER_CHANGED:2}});

const matchingSeason={status:"MATCH",writeAllowed:true,reasons:[],reviewed:{valid:true,externalLeagueId:"1234567890abcdef",seasonYear:2026,leagueHistoryId:null,leagueHistoryAvailable:false},observed:{valid:true,externalLeagueId:"1234567890abcdef",seasonYear:2026,leagueHistoryId:null,leagueHistoryAvailable:false}};
const rendered=renderFantraxPreview({fantraxPreview:{data:{league:{scoringPeriods:[]},seasonContextComparison:matchingSeason,rosterItems:[eligible,manual,unknown],teamRows:[],playerRows:[],matchups:[],standings:[],draftPicks:{currentDraftPicks:[],futureDraftPicks:[]},draftResults:{draftOrder:[],draftResults:[]},endpointHealth:[],diagnostics:{duplicateApiIds:[],invalidWrappedIds:0,unknownStatuses:[],teamMappingBlockers:0,playerMappingBlockers:0}},selectedTab:"rosters",reviewRosterSync:true,rosterSyncReviewed:true,rosterSyncSelectedIds:["p1"],confirmRosterSync:true,filters:{},page:1,pageSize:50}});
assert.match(rendered,/Review 1 Status Updates/);
assert.match(rendered,/Alpha/);
assert.doesNotMatch(rendered,/Manual<\/td><td>RESERVE<\/td><td>ACTIVE/,"manual overrides are not included in the exact apply table");
assert.match(rendered,/Continue to Confirmation/);
assert.match(rendered,/Selected: 1 \/ 3/);
assert.match(rendered,/data-fantrax-roster-select="p1" checked/);
assert.match(rendered,/Selected players: Alpha/);
const historicalRendered=renderFantraxPreview({fantraxPreview:{data:{league:{scoringPeriods:[]},seasonContextComparison:matchingSeason,rosterItems:[eligible],teamRows:[],playerRows:[],matchups:[],standings:[],draftPicks:{currentDraftPicks:[],futureDraftPicks:[]},draftResults:{draftOrder:[],draftResults:[]},endpointHealth:[],diagnostics:{duplicateApiIds:[],invalidWrappedIds:0,unknownStatuses:[],teamMappingBlockers:0,playerMappingBlockers:0}},selectedTab:"rosters",period:"131",reviewRosterSync:true,rosterSyncSelectedIds:["p1"],filters:{},page:1,pageSize:50}});
assert.match(historicalRendered,/blocked for historical scoring period 131/);
assert.match(historicalRendered,/id="reviewFantraxRosterSync"[^>]*disabled/);
assert.doesNotMatch(historicalRendered,/data-fantrax-roster-select/);

const repository=fs.readFileSync(new URL("../v5/js/repositories/playerRepository.js",import.meta.url),"utf8");
const main=fs.readFileSync(new URL("../v5/js/main.js",import.meta.url),"utf8");
const view=fs.readFileSync(new URL("../v5/js/views/fantraxPreviewView.js",import.meta.url),"utf8");
assert.match(repository,/applyFantraxRosterStatuses/);
assert.match(repository,/roster_status_source:"FANTRAX"/);
assert.match(repository,/\.in\("id",group\.ids\)/,"status writes remain grouped rather than one request per player");
assert.match(repository,/\.eq\("roster_status",group\.currentRosterStatus\)/,"stale previews are guarded");
assert.match(repository,/\.eq\("owner_team_id",group\.expectedOwnerTeamId\)/,"ownership changes are guarded at write time");
assert.match(repository,/roster_status_source\.is\.null,roster_status_source\.neq\.MANUAL/,"manual overrides are guarded at write time");
assert.doesNotMatch(repository,/applyFantraxRosterStatuses[\s\S]*owner_team_id:/,"sync payload must not write ownership");
assert.match(main,/rosterSyncReviewed/);
assert.match(main,/validateControlledFantraxStatusUpdates/);
assert.match(main,/fantraxRosterSyncPeriodGuard\(preview\.period\)/);
assert.match(main,/rosterSyncSelectedIds/);
assert.match(main,/fetchFantraxPublicPreview[\s\S]*lastRosterSync/,"preview is refreshed after apply");
assert.match(main,/Fantrax roster-status apply was incomplete/);
assert.match(view,/Nothing is selected by default/);
assert.match(view,/I reviewed these \$\{selectedRows\.length\} exact status-only updates/);
assert.match(view,/Confirm Status-Only Apply/);
assert.match(view,/Expected cloud owner/);
assert.match(view,/Skip reasons/);
assert.match(view,/Ownership, free-agent state, UUIDs, identities, scores, HKB values, and metrics will not change/);

console.log("V5 reviewed Fantrax roster sync tests passed");
