import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { applyFantraxProductionImport, fantraxProductionHealth, previewFantraxProductionImport } from "../v5/js/services/fantraxPlayerProductionImportService.js";
import { FANTRAX_PLAYERS_HEADER } from "../v5/js/services/fantraxPlayerProductionService.js";
import { buildCanonicalPlayerIntelligenceInput } from "../v5/js/services/playerIntelligenceInputService.js";
import { ENGINE_VERSION } from "../v5/js/engine/dynastyEngine.js";

const leagueId="11111111-1111-4111-8111-111111111111",playerId="22222222-2222-4222-8222-222222222222",file={name:"Fantrax-Players-Reddit Phanatics (17).csv",size:123,lastModified:99};
const league={id:leagueId,name:"Reddit Phanatics",settings:{fantraxSeasonContext:{externalLeagueId:"1234567890abcdef",seasonYear:2026,leagueHistoryId:"history-1"}}},player={id:playerId,league_id:leagueId,name:"Matt Olson",fantrax_id:"*02mwm*",fantrax_api_player_id:"02mwm",positions:["1B"],owner_team_id:"owner-1",roster_status:"ACTIVE",is_free_agent:false};
const row=(points="662.5",rate="5.48",id="*02mwm*",name="Matt Olson")=>[id,name,"ATL","1B","1","Rhys","32","",points,rate,"100","32.9","100%","0%","91%","-8%","100%","99%"];
const repositories=(rows=[row()],metrics=[])=>({parseFile:async()=>[[...FANTRAX_PLAYERS_HEADER],...rows],league:async()=>league,players:async()=>[player],metrics:async()=>metrics});

const preview=await previewFantraxProductionImport({leagueId,file,repositories:repositories()});
assert.equal(preview.writePerformed,false);assert.equal(preview.status,"READY");assert.equal(preview.counts.total,1);assert.equal(preview.counts.matched,1);assert.equal(preview.productionCounts.rowsWithFantasyPoints,1);assert.equal(preview.productionCounts.rowsWithFantasyPointsPerGame,1);assert.equal(preview.productionCounts.zeroFantasyPoints,0);assert.equal(preview.productionCounts.missingFantasyPoints,0);assert.equal(preview.plan.inserted.length,1);assert.equal(preview.plan.updated.length,0);assert.equal(preview.plan.unchanged.length,0);assert.equal(preview.plan.writeRows[0].metrics.fantasyPoints,662.5);assert.equal(preview.plan.writeRows[0].metrics.fantasyPointsPerGame,5.48);
const zero=await previewFantraxProductionImport({leagueId,file,repositories:repositories([row("0","0")])});assert.equal(zero.plan.writeRows[0].metrics.fantasyPoints,0);assert.equal(zero.plan.writeRows[0].metrics.fantasyPointsPerGame,0);assert.equal(zero.productionCounts.zeroFantasyPoints,1);
const missing=await previewFantraxProductionImport({leagueId,file,repositories:repositories([row("","")])});assert.equal(missing.productionCounts.missingFantasyPoints,1);assert.equal(missing.plan.writeRows.length,0);assert.equal(missing.plan.nonWritable[0].fantasyPoints,null);
const noSeason=await previewFantraxProductionImport({leagueId,file,repositories:{...repositories(),league:async()=>({...league,settings:{}})}});assert.equal(noSeason.status,"BLOCKED");assert.ok(noSeason.errors.some(error=>error.code==="SEASON_CONTEXT_UNAVAILABLE"));
const nameOnly=await previewFantraxProductionImport({leagueId,file,repositories:repositories([row("1","1","","Matt Olson")])});assert.equal(nameOnly.plan.writeRows.length,0);assert.equal(nameOnly.identityFailures[0].identityResult,"MISSING_API_ID");

const existing={id:"metric-1",league_id:leagueId,player_id:playerId,source:"Fantrax",season:2026,metric_type:"fantrax_league_production",imported_at:"2026-08-13T00:00:00Z",metrics:{fantasyPoints:662.5,fantasyPointsPerGame:5.48,fantraxId:"02mwm",positionEligibility:["1B"],statusEvidence:{raw:"Rhys",classification:"ROSTERED_TEAM_TOKEN",ownerTeamId:null},_fantraxProduction:{importedAt:"2026-08-13T00:00:00Z"}}};
const repeat=await previewFantraxProductionImport({leagueId,file,repositories:repositories([row()], [existing])});assert.equal(repeat.plan.writeRows.length,0);assert.equal(repeat.plan.unchanged.length,1,"identical repeat is a no-op");
const changed=await previewFantraxProductionImport({leagueId,file,repositories:repositories([row("663.25","5.49")],[existing])});assert.equal(changed.plan.inserted.length,0);assert.equal(changed.plan.updated.length,1);assert.equal(changed.plan.updated[0].player_id,playerId);assert.equal(changed.plan.updated[0].metrics.fantasyPoints,663.25);
const preserveBlankRate=await previewFantraxProductionImport({leagueId,file,repositories:repositories([row("663.25","")],[existing])});assert.equal(preserveBlankRate.plan.updated[0].metrics.fantasyPointsPerGame,5.48,"blank does not erase existing FP/G");

let writes=0,jobStarts=0,finished=null;const applyRepos={...repositories(),upsert:async(id,rows,options)=>{writes++;assert.equal(id,leagueId);assert.equal(options.batchSize,250);assert.equal(rows.length,1);return rows},startJob:async(id,input)=>{jobStarts++;assert.equal(input.fileName,file.name);return {id:"job-1"}},finishJob:async(id,jobId,result)=>{finished=result;return {id:jobId}}};
const applied=await applyFantraxProductionImport({leagueId,file,reviewedPreview:preview,reviewed:true,repositories:applyRepos});assert.equal(applied.status,"COMPLETED");assert.equal(applied.inserted,1);assert.equal(writes,1);assert.equal(jobStarts,1);assert.equal(finished.sourceMetadata.schemaSignature,"fantrax-players-16-header-18-row-v1");assert.equal("owner_team_id" in applied.sourceMetadata,false);assert.equal(player.owner_team_id,"owner-1");assert.equal(player.fantrax_id,"*02mwm*");
await assert.rejects(applyFantraxProductionImport({leagueId,file,reviewedPreview:preview,reviewed:false,repositories:applyRepos}),/Explicit/);
await assert.rejects(applyFantraxProductionImport({leagueId,file,reviewedPreview:preview,reviewed:true,repositories:{...applyRepos,league:async()=>({...league,settings:{fantraxSeasonContext:{...league.settings.fantraxSeasonContext,externalLeagueId:"fedcba0987654321"}}})}}),/season, identity, file, or write plan changed/);

let partialFinished=null;const partialRepos={...repositories([row(),row("647","5.39","*second*","Second")]),players:async()=>[player,{...player,id:"second-id",name:"Second",fantrax_id:"*second*",fantrax_api_player_id:"second"}],upsert:async()=>{const error=new Error("batch two failed");error.fantraxProductionBatchResult={savedCount:1,savedPlayerIds:[playerId],remainingCount:1,failedPlayerIds:["second-id"]};throw error},startJob:async()=>({id:"job-partial"}),finishJob:async(id,jobId,result)=>{partialFinished=result}};
const partialPreview=await previewFantraxProductionImport({leagueId,file,repositories:partialRepos}),partial=await applyFantraxProductionImport({leagueId,file,reviewedPreview:partialPreview,reviewed:true,repositories:partialRepos});assert.equal(partial.status,"PARTIAL");assert.equal(partial.saved,1);assert.equal(partial.failed,1);assert.equal(partialFinished.status,"partial");assert.deepEqual(partial.sourceMetadata.outcome.savedPlayerIds,[playerId]);

const job={id:"job-1",import_type:"fantrax_player_production",status:"completed",rows_processed:1,rows_matched:1,rows_unmatched:0,rows_inserted:1,rows_updated:0,rows_failed:0,completed_at:"2026-08-13T12:00:00Z",source_metadata:{provider:"Fantrax",season:2026,sourceRows:1,matched:1,unmatched:0,conflicts:0,schemaSignature:"fantrax-players-16-header-18-row-v1",schema:{headerCount:16,rowValueCount:18},outcome:{unchanged:0,nonWritable:0}}};
const health=fantraxProductionHealth({metricRows:[existing],importJobs:[job],playerRows:[player,{id:"missing"}],league,now:Date.parse("2026-08-13T13:00:00Z")});assert.equal(health.status,"COMPLETED");assert.equal(health.playersWithProduction,1);assert.equal(health.playersMissingProduction,1);assert.equal(health.seasonContextStatus,"MATCH");assert.equal(health.schema.headerCount,16);
const input=buildCanonicalPlayerIntelligenceInput({player,league,metricRows:[existing],season:2026,asOfDate:"2026-08-13T01:00:00Z"});assert.equal(input.production.status,"AVAILABLE");assert.equal(input.production.fantasyPoints,662.5);assert.equal(input.production.fantasyPointsPerGame,5.48);
assert.equal(ENGINE_VERSION,"5.1.1");
const root=new URL("../",import.meta.url),metricSource=await readFile(new URL("v5/js/repositories/metricRepository.js",root),"utf8"),serviceSource=await readFile(new URL("v5/js/services/fantraxPlayerProductionImportService.js",root),"utf8"),controllerSource=await readFile(new URL("v5/js/imports/cloudImportController.js",root),"utf8");assert.match(metricSource,/batchSize>250/);assert.match(metricSource,/slice\(index,index\+batchSize\)/);assert.match(metricSource,/player_id,source,season,metric_type/);assert.doesNotMatch(serviceSource,/calculated_player_scores|owner_team_id|roster_status|is_free_agent|createPlayer|updatePlayer/);assert.match(controllerSource,/fantraxProduction/);
console.log("v5FantraxProductionImport tests passed");
