import assert from "node:assert/strict";
import fs from "node:fs";
import {canonicalFantraxSyncManifest,fantraxSyncAttemptStatus,fantraxSyncAuditHealth,fantraxSyncManifestDigest,fantraxSyncOutcomeRows,pendingFantraxSyncUpdates,serializeFantraxSyncManifest,validateFantraxSyncManifest} from "../v5/js/services/fantraxSyncAuditService.js";
import {renderFantraxSyncAudit} from "../v5/js/views/fantraxSyncAuditView.js";

const seasonContext={externalLeagueId:"1234567890abcdef",seasonYear:2026,leagueHistoryId:"fedcba0987654321",leagueHistoryAvailable:true};
const a={id:"00000000-0000-4000-8000-000000000001",expectedOwnerTeamId:"10000000-0000-4000-8000-000000000001",currentRosterStatus:"RESERVE",roster_status:"ACTIVE",fantraxApiPlayerId:"A1",fantraxTeamId:"aaaaaaaaaaaaaaaa"};
const b={...a,id:"00000000-0000-4000-8000-000000000002",fantraxApiPlayerId:"B1"};
const input={leagueId:"20000000-0000-4000-8000-000000000001",period:"",seasonContext,updates:[b,a]};
const manifest=canonicalFantraxSyncManifest(input);
assert.equal(manifest.rows[0].playerId,a.id,"manifest order is deterministic by permanent player UUID");
assert.equal(validateFantraxSyncManifest(manifest).valid,true);
assert.equal(validateFantraxSyncManifest({...manifest,period:"13"}).valid,false);
assert.equal(serializeFantraxSyncManifest(input),serializeFantraxSyncManifest({...input,updates:[a,b]}));
assert.equal(await fantraxSyncManifestDigest(input),await fantraxSyncManifestDigest({...input,updates:[a,b]}));
assert.notEqual(await fantraxSyncManifestDigest(input),await fantraxSyncManifestDigest({...input,updates:[{...a,roster_status:"IL"},b]}));

const audited=[{player_id:a.id,outcome:"APPLIED"},{player_id:b.id,outcome:"PENDING"}];
assert.deepEqual(pendingFantraxSyncUpdates(manifest,audited).map(row=>row.id),[b.id],"recovery never replays a terminal row");
assert.deepEqual(pendingFantraxSyncUpdates(manifest,[{player_id:a.id,outcome:"APPLIED"},{player_id:b.id,outcome:"FAILED"}]).map(row=>row.id),[b.id],"failed rows remain retryable");
assert.equal(fantraxSyncAttemptStatus(audited),"PARTIAL");
assert.equal(fantraxSyncAttemptStatus([{outcome:"APPLIED"},{outcome:"APPLIED"}]),"COMPLETED");
assert.equal(fantraxSyncAttemptStatus([{outcome:"APPLIED"},{outcome:"SKIPPED"}]),"PARTIAL");
const outcomes=fantraxSyncOutcomeRows("attempt-1",{updated:[{id:a.id,roster_status:"ACTIVE",updated_at:"2026-08-08T00:00:00Z"}],skipped:[{id:b.id,reason:"MANUAL_OVERRIDE",currentRow:{roster_status_source:"MANUAL"}}]});
assert.deepEqual(outcomes.map(row=>row.outcome),["APPLIED","SKIPPED"]);
assert.equal(fantraxSyncAuditHealth([{status:"APPLYING",manifest_digest:"abc",actor_user_id:"u",season_context:{}}]).status,"WARNING");
assert.equal(fantraxSyncAuditHealth([{status:"COMPLETED",manifest_digest:"",actor_user_id:"u",season_context:{}}]).status,"FAIL");
assert.match(renderFantraxSyncAudit([{id:"attempt-1",status:"PARTIAL",reviewed_count:2,manifest_digest:"abcdef1234567890",created_at:"now"}]),/Synchronization audit and recovery|Fantrax Synchronization Audit/i);
assert.match(renderFantraxSyncAudit([]),/No durable synchronization attempts recorded/);

const migration=fs.readFileSync(new URL("../supabase/migrations/009_fantrax_sync_audit.sql",import.meta.url),"utf8");
const repository=fs.readFileSync(new URL("../v5/js/repositories/fantraxSyncAuditRepository.js",import.meta.url),"utf8");
const playerRepository=fs.readFileSync(new URL("../v5/js/repositories/playerRepository.js",import.meta.url),"utf8");
const main=fs.readFileSync(new URL("../v5/js/main.js",import.meta.url),"utf8");
assert.match(migration,/unique \(league_id, manifest_digest\)/i);
assert.match(migration,/actor_user_id uuid not null[^\n]*default auth\.uid\(\)/i);
assert.match(migration,/new\.started_at := null|new\.started_at:=null/i);
assert.match(migration,/new\.started_at:=clock_timestamp\(\)/i,"attempt start time is database controlled");
assert.match(migration,/new\.completed_at:=clock_timestamp\(\)/i,"attempt completion time is database controlled");
assert.match(migration,/new\.applied_at:=clock_timestamp\(\)/i,"applied row time is database controlled");
assert.match(migration,/Fantrax synchronization attempt identity and manifest are immutable/i);
assert.match(migration,/Successful and skipped Fantrax synchronization outcomes are terminal/i);
assert.match(migration,/p\.id=new\.player_id and p\.league_id=new\.league_id/i,"player references cannot cross leagues");
assert.match(migration,/t\.id=new\.expected_owner_team_id and t\.league_id=new\.league_id and t\.fantrax_team_id=new\.fantrax_team_id/i,"team identity cannot cross leagues");
assert.match(migration,/a\.id=new\.attempt_id and a\.league_id=new\.league_id and a\.actor_user_id=\(select auth\.uid\(\)\)/i,"manifest items belong to the actor attempt and league");
assert.doesNotMatch(migration,/security definer/i,"new audit triggers must not bypass caller RLS");
assert.match(migration,/security invoker set search_path=public,pg_temp/gi);
assert.match(migration,/enable row level security/gi);
assert.doesNotMatch(migration,/service_role|password|cookie|private_key/i);
assert.match(repository,/\.eq\("manifest_digest",digest\)/,"same manifest resolves to one durable attempt");
assert.match(repository,/\.in\("outcome",\["PENDING","FAILED"\]\)/,"only pending or failed rows can receive a recovery outcome");
assert.doesNotMatch(repository,/\.delete\(/,"audit evidence is not deleted by the browser repository");
assert.match(playerRepository,/await beforeGroup\(group\)/,"every write group repeats caller guards");
assert.match(main,/pendingFantraxSyncUpdates/);
assert.match(main,/fantraxSeasonWriteGuard\(currentPreview\.data\?\.seasonContextComparison\)/);
assert.match(main,/fantraxRosterSyncPeriodGuard\(currentPreview\.period\)/);
assert.match(main,/recordFantraxSyncOutcomes/);
assert.match(main,/finalizeFantraxSyncAttempt/);
console.log("V5 Fantrax synchronization audit tests passed");
