import assert from "node:assert/strict";
import fs from "node:fs";
import { createFantraxGate4AcceptanceController, GATE4_CONTROLLER_STATES } from "../v5/js/services/fantraxGate4AcceptanceController.js";
import { fantraxPreviewHealthChecks } from "../v5/js/services/dataHealthService.js";
import { renderFantraxGate4Acceptance } from "../v5/js/views/fantraxGate4AcceptanceView.js";

const leagueId="6573ac24-f433-48c7-a834-ffe6b58726bc",externalLeagueId="xryuc2ewmhi0d2vm",teamUuid="10000000-0000-4000-8000-000000000001";
const league={id:leagueId,name:"Reddit Phanatics",settings:{fantraxSeasonContext:{externalLeagueId,seasonYear:2026,leagueHistoryId:"8mifq27zmhi0d2vm",leagueHistoryAvailable:true},fantraxRosterSyncRelease:{enabled:false,leagueId,reviewed:true,releaseId:"V5.4.6E_OPT_IN_10"}}};
const comparison={status:"MATCH",writeAllowed:true,reasons:[],observed:league.settings.fantraxSeasonContext,reviewed:league.settings.fantraxSeasonContext};
const playerId=index=>`00000000-0000-4000-8000-${String(index).padStart(12,"0")}`;
const eligible=index=>({matchedPlayerUuid:playerId(index),matchedPlayer:{name:`Exact ${index}`},fantraxApiPlayerId:`api${index}`,fantraxTeamId:"team000000000001",fantraxTeamName:"Exact Team",matchedTeamUuid:teamUuid,currentOwnerTeamId:teamUuid,currentRosterStatus:"UNCLASSIFIED",normalizedRosterStatus:"ACTIVE",futureSyncRecommendation:"APPLY_FANTRAX_STATUS",playerIdentityResult:"MATCHED",teamIdentityResult:"MATCHED",ownershipDifference:false,rosterStatusDifference:true,fantraxConflict:true,activeManualOverride:false});
const rosterItems=Array.from({length:11},(_,index)=>eligible(index+1));
rosterItems.push({...eligible(12),matchedPlayer:{name:"Jared Jones"},playerIdentityResult:"DUPLICATE"});
rosterItems.push({...eligible(13),activeManualOverride:true,futureSyncRecommendation:"PRESERVE_MANUAL_OVERRIDE"});
rosterItems.push({...eligible(14),normalizedRosterStatus:"UNCLASSIFIED",futureSyncRecommendation:"REVIEW_CONFLICT"});
rosterItems.push({...eligible(15),futureSyncRecommendation:"REVIEW_CONFLICT"});
rosterItems.push({...eligible(16),ownershipDifference:true,futureSyncRecommendation:"REVIEW_CONFLICT"});
rosterItems.push({...eligible(17),teamIdentityResult:"UNMAPPED",futureSyncRecommendation:"REVIEW_CONFLICT"});
rosterItems.push({...eligible(18),futureSyncRecommendation:"RELEASE"});
const previewData={fetchedAt:"preview-a",seasonContextComparison:comparison,rosterItems};
const canonicalPreviewState={data:previewData,loading:false,error:"",status:"READY"};
const fakeState={authUser:{id:"user-1",email:"owner@example.com"},activeLeague:league,teams:[{id:teamUuid,name:"Exact Team",fantrax_team_id:"team000000000001"}],fantraxSyncAttempts:[]};
let persistenceCalls=0,previewCalls=0,auditCalls=0;
const baseline={players:{count:11,digest:"players"},teams:{count:1,digest:"teams"},managers:{count:1,digest:"managers"},metrics:{count:0,digest:"metrics"},scores:{count:0,digest:"scores"},auditAttempts:{count:0,digest:"attempts"},auditItems:{count:0,digest:"items"}};
const controller=createFantraxGate4AcceptanceController({artifactCommit:"exact",dependencies:{appState:fakeState,allPlayers:async()=>rosterItems.map(row=>row.matchedPlayer),captureFantraxProtectedBaseline:async()=>baseline,harnessDependencies:{appState:fakeState,currentUser:async()=>fakeState.authUser,listFantraxSyncAttempts:async()=>{auditCalls++;return []},fetchFantraxPublicPreview:async()=>{previewCalls++;return canonicalPreviewState},executeReviewedFantraxSync:async()=>{persistenceCalls++;throw new Error("must remain unreachable")}}}});

assert.deepEqual(controller.state.stage,"NOT_STARTED");
assert.equal(controller.state.persistenceEnabled,false);
assert.equal(controller.state.armed,false);
await controller.start();
assert.equal(controller.state.stage,"Gate A");
assert.equal(controller.state.status,"PASS");
assert.equal(controller.state.artifact.checkpoints.authenticatedUser.status,"PASS","normal authenticated state reaches the actual harness");
assert.equal(controller.state.artifact.checkpoints.auditBaseline.evidence.attemptCount,0,"an authoritative genuine zero remains a successful zero");
assert.equal(auditCalls,1,"audit baseline uses the harness authenticated repository path");
await controller.fetchPreviewA();
assert.equal(previewCalls,1,"Preview A uses the harness production preview dependency");
assert.equal(controller.state.previewAGateB.status,"PASS","Preview A runs canonical season and Current-period Gate B checks");
assert.equal(controller.state.eligibleRows.length,11);
assert.equal(fakeState.fantraxPreview.data,previewData,"Preview A publishes the canonical observation to shared application state");
assert.equal(fakeState.fantraxPreview.data.seasonContextComparison.status,"MATCH","Data Health can consume the same current season observation without another fetch");
assert.equal(fantraxPreviewHealthChecks(fakeState.fantraxPreview).find(row=>row.name==="Fantrax Season Context Review").status,"PASS","Data Health sees the controller's shared valid Preview A context");
assert.equal(previewCalls,1,"sharing Preview A does not fetch a second Fantrax preview for Data Health");
assert.equal(controller.state.eligibleRows[0].fantraxConflict,true,"an aggregate status-difference flag alone does not block canonical APPLY eligibility");
assert.match(controller.state.excludedRows.find(row=>row.matchedPlayer?.name==="Jared Jones").gate4ExclusionReason,/identity is not exact/i);
assert.match(controller.state.excludedRows.find(row=>row.activeManualOverride).gate4ExclusionReason,/Manual/);
assert.match(controller.state.excludedRows.find(row=>row.normalizedRosterStatus==="UNCLASSIFIED").gate4ExclusionReason,/Unsupported/);
assert.ok(controller.state.excludedRows.some(row=>row.futureSyncRecommendation==="REVIEW_CONFLICT"),"canonical REVIEW_CONFLICT rows remain excluded");
assert.ok(controller.state.excludedRows.some(row=>row.futureSyncRecommendation==="RELEASE"),"release/removal rows remain excluded");
assert.ok(controller.state.excludedRows.some(row=>row.ownershipDifference),"ownership contradictions remain excluded");
assert.ok(controller.state.excludedRows.some(row=>row.teamIdentityResult==="UNMAPPED"),"unresolved team identity remains excluded");
for(const row of controller.state.eligibleRows.slice(0,10))controller.toggleCandidate(row.matchedPlayerUuid,true);
assert.equal(controller.state.selectedIds.length,10,"exactly ten explicit UUIDs can be selected");
controller.toggleCandidate(controller.state.eligibleRows[10].matchedPlayerUuid,true);
assert.equal(controller.state.selectedIds.length,10,"the 11th candidate is blocked without substitution");
assert.match(controller.state.error,/limited to 10/);
controller.toggleCandidate(controller.state.selectedIds[0],true);
assert.equal(controller.state.selectedIds.length,10,"duplicate UUID selection cannot change the reviewed set");
assert.match(controller.state.error,/Duplicate/);
await controller.captureProtectedBaseline();
assert.equal(controller.state.stage,"Ready for Next Gate");
assert.equal(controller.state.status,"PASS");
assert.deepEqual(controller.state.protectedBaseline,baseline);
assert.equal(controller.state.artifact.checkpoints.candidates.status,"PASS");
assert.equal(controller.state.artifact.checkpoints.protectedBaseline.status,"PASS");
assert.equal(controller.state.artifact.manifest,null,"the read-only controller stops before manifest construction");
assert.equal(controller.state.artifact.persistenceEnabled,false);
assert.equal(controller.state.artifact.persistenceCalled,false);
assert.equal(controller.state.armed,false);
assert.equal(persistenceCalls,0,"no sync coordinator persistence call occurs");
const rendered=renderFantraxGate4Acceptance({gate4Acceptance:controller.state});
assert.match(rendered,/Ready for Next Gate/);
assert.match(rendered,/DISABLED \/ UNARMED/);
assert.doesNotMatch(rendered,/data-action|type="submit"|confirmGate4|persistGate4/i,"rendering exposes no persistence affordance");

controller.reset("Active league changed.");
assert.equal(controller.state.stage,"NOT_STARTED","league change/logout/reload reset to a safe session-only state");
assert.equal(controller.state.armed,false);
assert.equal(controller.state.artifact,null);
assert.equal(fakeState.fantraxPreview.data,null,"controller invalidation removes the shared current observation");
const denied=createFantraxGate4AcceptanceController({dependencies:{appState:fakeState,harnessDependencies:{appState:fakeState,currentUser:async()=>fakeState.authUser,listFantraxSyncAttempts:async()=>{throw new Error("permission denied")}}}});
await denied.start();
assert.equal(denied.state.status,"PERMISSION_BLOCKED","permission failures do not become a zero audit baseline or success");
assert.ok(GATE4_CONTROLLER_STATES.includes(denied.state.status));

const malformedState={...fakeState,fantraxPreview:{data:null}};
const malformed=createFantraxGate4AcceptanceController({dependencies:{appState:malformedState,allPlayers:async()=>[],harnessDependencies:{appState:malformedState,currentUser:async()=>malformedState.authUser,listFantraxSyncAttempts:async()=>[],fetchFantraxPublicPreview:async()=>({data:{missing:"canonical preview"},error:"query failed"})}}});
await malformed.start();
await malformed.fetchPreviewA();
assert.equal(malformed.state.status,"UNAVAILABLE","malformed Preview A fails closed as unavailable");
assert.equal(malformedState.fantraxPreview.data,null,"malformed/query-failed Preview A cannot populate shared context");
const failedTransportState={...fakeState,fantraxPreview:{data:null}};
const failedTransport=createFantraxGate4AcceptanceController({dependencies:{appState:failedTransportState,allPlayers:async()=>[],harnessDependencies:{appState:failedTransportState,currentUser:async()=>failedTransportState.authUser,listFantraxSyncAttempts:async()=>[],fetchFantraxPublicPreview:async()=>({...canonicalPreviewState,error:"Fantrax preview query failed."})}}});
await failedTransport.start();
await failedTransport.fetchPreviewA();
assert.equal(failedTransport.state.status,"QUERY_FAILED","transport error metadata blocks an otherwise well-shaped Preview A");
assert.equal(failedTransportState.fantraxPreview.data,null,"query-failed preview data cannot become the authoritative shared observation");

const main=fs.readFileSync(new URL("../v5/js/main.js",import.meta.url),"utf8");
assert.match(main,/createFantraxGate4AcceptanceController/);
assert.match(main,/startGate4Acceptance/);
assert.match(main,/resetGate4Acceptance\("Authentication ended\."\)/);
assert.match(main,/resetGate4Acceptance\("Active league changed\."\)/);
assert.match(main,/id==="signOut"[\s\S]{0,300}fantraxPreview:clearFantraxPendingReviews\(fantraxPreviewState\(\{data:null/,"logout invalidates the shared Preview A observation");
assert.match(main,/id==="leagueSelect"[\s\S]{0,300}fantraxPreview:clearFantraxPendingReviews\(fantraxPreviewState\(\{data:null/,"active-league change invalidates the shared Preview A observation");
assert.match(main,/previousReleaseSignature!==nextReleaseSignature[\s\S]{0,180}resetGate4Acceptance/,"release configuration drift invalidates controller review state");
assert.doesNotMatch(main,/gate4Controller\?\.persist|gate4Controller\.persist/);
console.log("v5FantraxGate4AcceptanceController tests passed");
