import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {buildUnderlyingSkillContext,evaluateUnderlyingSkill,evaluateUnderlyingSkillPopulation,breakoutRegressionSignal,MATERIAL_GAP_THRESHOLD} from "../v5/js/engine/playerIntelligenceUnderlyingSkill.js";import {calculatePlayerScores,ENGINE_VERSION} from "../v5/js/engine/dynastyEngine.js";
const L="league",fresh={status:"AVAILABLE",source:"Statcast",fetchedAt:"2026-08-13"};
function input(id,type,metrics,{age=25,pos=type==="pitcher"?["SP"]:["OF"],hkb=1,fp=100,minor=false,status="AVAILABLE"}={}){return {schema:"player-intelligence-input-v1",inputVersion:"5.5B-1",playerId:id,leagueId:L,asOfDate:"2026-08-13",season:2026,player:{id,age,isMinorLeaguer:minor},positionEligibility:{eligible:pos},production:{fantasyPoints:fp},underlyingSkill:{playerType:type,metrics,status},market:{value:hkb},dataFreshness:{statcast:{...fresh,status}},warnings:[]}}
const hitters=Array.from({length:11},(_,i)=>input(`h${i}`,"hitter",{xwoba:.25+i*.015,xslg:.35+i*.025,xba:.20+i*.01,barrelRate:3+i,hardHitRate:25+i*2,averageExitVelocity:82+i,sprintSpeed:24+i*.4}));const pitchers=Array.from({length:11},(_,i)=>input(`p${i}`,"pitcher",{xera:2+i*.3,era:2.2+i*.3,xwobaAllowed:.25+i*.012,barrelRateAllowed:3+i,hardHitRateAllowed:25+i*2,averageExitVelocityAllowed:82+i}));let c=buildUnderlyingSkillContext([...hitters,...pitchers]);const elite=evaluateUnderlyingSkill(c,"h10"),weak=evaluateUnderlyingSkill(c,"h0");assert.ok(elite.component.score>weak.component.score);assert.equal(elite.evidence.playerType,"hitter");assert.equal(elite.evidence.metricPercentiles[0].populationSize,11);
const pa=evaluateUnderlyingSkill(c,"p0"),pb=evaluateUnderlyingSkill(c,"p10");assert.ok(pa.component.score>pb.component.score,"lower pitcher contact/run metrics are better");assert.ok(pa.component.warnings.some(x=>x.code==="LIMITED_PITCHER_SKILL_INPUTS"));
const underlying={xera:3,xwobaAllowed:.29,barrelRateAllowed:6,hardHitRateAllowed:32,averageExitVelocityAllowed:87},eraRows=[...pitchers,input("era-low","pitcher",{...underlying,era:2}),input("era-high","pitcher",{...underlying,era:5}),input("era-aligned","pitcher",{...underlying,era:3.2}),input("era-missing","pitcher",underlying)];c=buildUnderlyingSkillContext(eraRows);const eraLow=evaluateUnderlyingSkill(c,"era-low"),eraHigh=evaluateUnderlyingSkill(c,"era-high"),eraAligned=evaluateUnderlyingSkill(c,"era-aligned"),eraMissing=evaluateUnderlyingSkill(c,"era-missing");assert.equal(eraLow.component.score,eraHigh.component.score,"ERA has zero raw-skill weight");assert.equal(eraLow.evidence.coverageRatio,eraMissing.evidence.coverageRatio,"missing ERA does not reduce coverage");assert.ok(eraLow.component.explanations.some(x=>x.code==="ERA_OUTPERFORMING_XERA"));assert.ok(eraHigh.component.explanations.some(x=>x.code==="ERA_UNDERPERFORMING_XERA"));assert.ok(eraAligned.component.explanations.some(x=>x.code==="ERA_XERA_ALIGNED"));assert.ok(!eraLow.component.inputsUsed.includes("Statcast.era"));
const noXeraRows=[...pitchers,input("no-xera","pitcher",{xwobaAllowed:.29,barrelRateAllowed:6,hardHitRateAllowed:32,averageExitVelocityAllowed:87})];const noXera=evaluateUnderlyingSkill(buildUnderlyingSkillContext(noXeraRows),"no-xera");assert.ok(noXera.evidence.coverageRatio<eraMissing.evidence.coverageRatio);assert.ok(noXera.component.confidence<eraMissing.component.confidence);
const partialInputs=[...hitters,input("partial","hitter",{barrelRate:20,hardHitRate:55,averageExitVelocity:94})];c=buildUnderlyingSkillContext(partialInputs);const partial=evaluateUnderlyingSkill(c,"partial");assert.equal(partial.component.status,"CALCULATED");assert.ok(partial.component.warnings.some(x=>x.code==="PARTIAL_STATCAST_COVERAGE"));assert.ok(partial.component.confidence<elite.component.confidence);
const slowInputs=[...hitters,input("slow","hitter",{xwoba:.44,xslg:.65,xba:.32,barrelRate:20,hardHitRate:55,averageExitVelocity:94,sprintSpeed:20})];const slow=evaluateUnderlyingSkill(buildUnderlyingSkillContext(slowInputs),"slow");assert.ok(slow.component.score>75,"sprint speed cannot overpower elite hitting evidence");
for(const [field,a,b] of [["age",22,32],["pos",["SS"],["OF"]],["hkb",9999,1],["fp",900,10]]){const rows=[...hitters,input("iso-a","hitter",hitters[5].underlyingSkill.metrics,{[field]:a}),input("iso-b","hitter",hitters[5].underlyingSkill.metrics,{[field]:b})],ctx=buildUnderlyingSkillContext(rows);assert.equal(evaluateUnderlyingSkill(ctx,"iso-a").component.score,evaluateUnderlyingSkill(ctx,"iso-b").component.score,`${field} is isolated`)}
const none=input("none","hitter",{},{}),pros=input("pros","hitter",{},{minor:true});c=buildUnderlyingSkillContext([...hitters,none,pros]);assert.equal(evaluateUnderlyingSkill(c,"none").component.status,"INSUFFICIENT_DATA");assert.equal(evaluateUnderlyingSkill(c,"pros").component.status,"NOT_APPLICABLE");const stale=evaluateUnderlyingSkill(buildUnderlyingSkillContext([...hitters,input("stale","hitter",hitters[8].underlyingSkill.metrics,{status:"STALE"})]),"stale");assert.equal(stale.component.status,"STALE");assert.ok(stale.component.warnings.some(x=>x.code==="STALE_STATCAST"));
const fake=skill=>({component:{status:"CALCULATED",confidence:80},evidence:{score:skill,metricsUsed:["xwoba"]}});assert.equal(breakoutRegressionSignal({productionPercentile:35,skillResult:fake(80)}).code,"BREAKOUT_SIGNAL");assert.equal(breakoutRegressionSignal({productionPercentile:90,skillResult:fake(55)}).code,"REGRESSION_RISK");assert.equal(breakoutRegressionSignal({productionPercentile:92,skillResult:fake(94)}).code,"SUPPORTED_PRODUCTION");assert.equal(breakoutRegressionSignal({productionPercentile:72,skillResult:fake(74)}).code,"NEUTRAL_PRODUCTION_SKILL_GAP");assert.equal(MATERIAL_GAP_THRESHOLD,20);
const prior={playerId:"h0",components:{leagueProduction:{explanations:[{data:{leaguePercentile:35}}]},underlyingSkill:{status:"INSUFFICIENT_DATA"}},signals:[]},population=evaluateUnderlyingSkillPopulation(hitters,[prior]);assert.equal(population.players.length,hitters.length);assert.equal(population.players[0].output.components.underlyingSkill.status,"CALCULATED","existing component envelope is populated");const legacy=calculatePlayerScores({player:{id:"x",positions:["SS"],age:25,hkb_value:1},metrics:{},leagueSettings:{}});assert.equal(ENGINE_VERSION,"5.1.1");assert.equal(legacy.overall_score_version,"5.1.1");const engine=await readFile(new URL("../v5/js/engine/playerIntelligenceUnderlyingSkill.js",import.meta.url),"utf8"),service=await readFile(new URL("../v5/js/services/playerIntelligenceUnderlyingSkillService.js",import.meta.url),"utf8");assert.doesNotMatch(engine,/repositories|supabase|fetch\(/);assert.doesNotMatch(service,/upsert|insert\(|update\(|delete\(|calculated_player_scores/);console.log("v5PlayerIntelligenceUnderlyingSkill tests passed");
