import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { buildCanonicalPlayerIntelligenceInput } from "../v5/js/services/playerIntelligenceInputService.js";
import { AVAILABILITY, buildLeagueProductionContext, evaluateLeagueProductionPlayer, evaluateLeagueProductionPopulation, REPLACEMENT_POSITIONS } from "../v5/js/engine/playerIntelligenceLeagueProduction.js";
import { loadLeagueProductionEvaluation } from "../v5/js/services/playerIntelligenceLeagueProductionService.js";
import { calculatePlayerScores, ENGINE_VERSION } from "../v5/js/engine/dynastyEngine.js";

const leagueId="11111111-1111-4111-8111-111111111111",otherLeagueId="99999999-9999-4999-8999-999999999999",season=2026,asOfDate="2026-08-13T12:00:00.000Z";
const league={id:leagueId,name:"Reddit Phanatics",team_count:10,settings:{lineupSlots:{C:1,"1B":1,"2B":1,"3B":1,SS:1,OF:5,UT:1,SP:5,RP:3,P:2}}};
const metric=(id,points,rate=points===null?null:5,overrides={})=>({id:`m-${id}`,league_id:overrides.league_id||leagueId,player_id:id,source:"Fantrax",season,metric_type:"fantrax_league_production",imported_at:overrides.imported_at||"2026-08-13T10:00:00.000Z",metrics:{fantasyPoints:points,fantasyPointsPerGame:rate,_fantraxProduction:{importedAt:overrides.imported_at||"2026-08-13T10:00:00.000Z"}}});
const player=(id,positions,points,{free=false,owner=free?null:"team-1",minor=false,status=free?"FREE_AGENT":"ACTIVE",hkb=999,league_id=leagueId,imported_at}={})=>({player:{id,league_id,name:`Player ${id}`,positions,owner_team_id:owner,is_free_agent:free,is_minor_leaguer:minor,roster_status:status,hkb_value:hkb},metric:metric(id,points,points===null?null:5,{league_id,imported_at})});
function inputs(rows,leagueRow=league){const metrics=rows.map(row=>row.metric);return rows.map(row=>buildCanonicalPlayerIntelligenceInput({player:row.player,league:leagueRow,metricRows:metrics,season,asOfDate}))}
function basePools(){return REPLACEMENT_POSITIONS.flatMap(position=>[player(`r-${position}`, [position],500),...Array.from({length:5},(_,i)=>player(`fa-${position}-${i}`,[position],300-i*10,{free:true}))])}

const zeroRows=[player("zero",["SS"],0),...basePools()],zeroContext=buildLeagueProductionContext(inputs(zeroRows));
const zero=evaluateLeagueProductionPlayer(zeroContext,"zero");assert.equal(zero.components.leagueProduction.status,"CALCULATED");assert.equal(zero.replacementContext.playerProduction,0,"numeric zero remains real production");
const missingRows=[player("missing",["SS"],null),...basePools()],missing=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs(missingRows)),"missing");assert.equal(missing.components.leagueProduction.status,"INSUFFICIENT_DATA");assert.equal(missing.components.leagueProduction.score,null,"missing FPts is not zero");
const prospectRows=[player("prospect",["SS"],null,{minor:true,status:"MINORS"}),...basePools()],prospect=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs(prospectRows)),"prospect");assert.equal(prospect.components.leagueProduction.status,"NOT_APPLICABLE");

const multiRows=[player("multi",["2B","SS"],600),...basePools()],multi=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs(multiRows)),"multi");assert.deepEqual(multi.replacementContext.positions.map(row=>row.position),["2B","SS"]);assert.ok(multi.components.positionalScarcityValue.explanations.some(row=>row.code==="MULTI_POSITION_FLEXIBILITY"));assert.ok(multi.components.positionalScarcityValue.score<=100,"flexibility stays bounded");
for(const position of REPLACEMENT_POSITIONS){assert.equal(zeroContext.pools[position].position,position);assert.equal(zeroContext.pools[position].availableCount,5,`${position} replacement pool works`)}
assert.equal(zeroContext.demand.utility,10);assert.equal(zeroContext.demand.pitcherFlex,20,"UT and P are demand, not synthetic positions");

const deepOfShallowSs=[player("of-star",["OF"],500),player("ss-star",["SS"],500),...Array.from({length:10},(_,i)=>player(`of-fa-${i}`,["OF"],470-i*3,{free:true})),player("ss-fa",["SS"],150,{free:true}),...basePools().filter(row=>!["OF","SS"].some(pos=>row.player.positions.includes(pos)))];
let comparison=evaluateLeagueProductionPopulation(inputs(deepOfShallowSs));let ofResult=comparison.players.find(row=>row.playerId==="of-star"),ssResult=comparison.players.find(row=>row.playerId==="ss-star");assert.ok(ssResult.components.positionalScarcityValue.score>ofResult.components.positionalScarcityValue.score,"shallow SS is empirically scarcer than deep OF");assert.ok(ssResult.replacementContext.rawReplacementGap>ofResult.replacementContext.rawReplacementGap);
const reverse=[player("of-star",["OF"],500),player("ss-star",["SS"],500),player("of-fa",["OF"],100,{free:true}),...Array.from({length:10},(_,i)=>player(`ss-fa-${i}`,["SS"],470-i*3,{free:true})),...basePools().filter(row=>!["OF","SS"].some(pos=>row.player.positions.includes(pos)))];
comparison=evaluateLeagueProductionPopulation(inputs(reverse));ofResult=comparison.players.find(row=>row.playerId==="of-star");ssResult=comparison.players.find(row=>row.playerId==="ss-star");assert.ok(ofResult.components.positionalScarcityValue.score>ssResult.components.positionalScarcityValue.score,"reverse depth reverses scarcity");

const freeAgentRows=[player("fa-elite",["SS"],500,{free:true}),player("fa-a",["SS"],300,{free:true}),player("fa-b",["SS"],280,{free:true}),player("fa-c",["SS"],250,{free:true}),player("ss-rostered",["SS"],450)];
const faResult=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs(freeAgentRows)),"fa-elite");assert.equal(faResult.replacementContext.availability,AVAILABILITY.FREE_AGENT);assert.equal(faResult.replacementContext.replacementProduction,280,"free agent is excluded from his own benchmark");assert.equal(faResult.replacementContext.rawReplacementGap,220);assert.ok(faResult.components.replacementAdvantage.explanations.some(row=>row.code==="REPLACEMENT_ADVANTAGE_STRONG"));
const belowRows=[player("weak",["SS"],220),player("fa-1",["SS"],350,{free:true}),player("fa-2",["SS"],330,{free:true}),player("fa-3",["SS"],310,{free:true})],below=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs(belowRows)),"weak");assert.equal(below.replacementContext.rawReplacementGap,-110);assert.ok(below.components.replacementAdvantage.explanations.some(row=>row.code==="BELOW_REPLACEMENT"));

const transitional=inputs([player("waiver",["SS"],400,{free:false,owner:null,status:"WAIVER"}),...basePools()]);const transitionalContext=buildLeagueProductionContext(transitional);assert.equal(transitionalContext.rows.find(row=>row.id==="waiver").availability,AVAILABILITY.WAIVER);assert.equal(transitionalContext.pools.SS.availableCount,5,"waiver/unknown is not silently available");
const unknownRows=[player("unknown",["SS"],400,{free:false,owner:null,status:"UNKNOWN"}),...basePools()],unknownContext=buildLeagueProductionContext(inputs(unknownRows)),unknown=evaluateLeagueProductionPlayer(unknownContext,"unknown");assert.equal(unknownContext.rows.find(row=>row.id==="unknown").availability,AVAILABILITY.UNKNOWN);assert.equal(unknownContext.pools.SS.availableCount,5);assert.ok(unknown.components.leagueProduction.warnings.some(row=>row.code==="OWNERSHIP_STATE_UNKNOWN"));
assert.throws(()=>buildLeagueProductionContext([...inputs(basePools()),...inputs([player("cross",["SS"],1,{league_id:otherLeagueId})],{...league,id:otherLeagueId})]),/one league/);

const staleRows=[player("stale",["SS"],500,{imported_at:"2026-07-01T00:00:00.000Z"}),...basePools()],stale=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs(staleRows)),"stale");assert.equal(stale.components.leagueProduction.status,"STALE");assert.ok(stale.components.leagueProduction.warnings.some(row=>row.code==="STALE_FANTRAX_PRODUCTION"));assert.ok(stale.components.leagueProduction.warnings.some(row=>row.code==="SAMPLE_SIZE_UNAVAILABLE"),"sample size is not inferred from FPts/FP-G");
const noLineup={...league,settings:{}},noLineupResult=evaluateLeagueProductionPlayer(buildLeagueProductionContext(inputs([player("target",["SS"],500),...basePools()],noLineup)),"target");assert.ok(noLineupResult.components.positionalScarcityValue.warnings.some(row=>row.code==="LINEUP_CONFIGURATION_INCOMPLETE"));

const productionOnly=inputs([player("source",["SS"],600,{hkb:999}),...basePools()]);productionOnly[0].underlyingSkill.metrics={xwoba:.5};productionOnly[0].market.value=99999;const sourceResult=evaluateLeagueProductionPlayer(buildLeagueProductionContext(productionOnly),"source");assert.equal(sourceResult.replacementContext.playerProduction,600);assert.deepEqual(sourceResult.components.leagueProduction.inputsUsed,["Fantrax.fantasyPoints","Fantrax.fantasyPointsPerGame","Fantrax.importedAt"],"HKB and Statcast are excluded");

let reads={players:0,metrics:0,leagues:0};const loaded=await loadLeagueProductionEvaluation({leagueId,season,asOfDate,repositories:{players:{allPlayers:async()=>{reads.players++;return freeAgentRows.map(row=>row.player)}},metrics:{listMetrics:async()=>{reads.metrics++;return freeAgentRows.map(row=>row.metric)}},leagues:{leagueById:async()=>{reads.leagues++;return league}}}});assert.deepEqual(reads,{players:1,metrics:1,leagues:1},"league population is loaded once");assert.equal(loaded.players.length,freeAgentRows.length);

const legacyPlayer={id:"legacy",age:25,positions:["SS"],hkb_value:50,owner_team_id:"team-1",roster_status:"ACTIVE"},legacyBefore=calculatePlayerScores({player:legacyPlayer,metrics:{},leagueSettings:{}}),legacyAfter=calculatePlayerScores({player:legacyPlayer,metrics:{},leagueSettings:{}});assert.equal(ENGINE_VERSION,"5.1.1");assert.deepEqual(legacyAfter,legacyBefore,"Engine 5.1.1 remains unchanged");
const engineSource=await readFile(new URL("../v5/js/engine/playerIntelligenceLeagueProduction.js",import.meta.url),"utf8"),serviceSource=await readFile(new URL("../v5/js/services/playerIntelligenceLeagueProductionService.js",import.meta.url),"utf8");assert.doesNotMatch(engineSource,/repositories|supabase|fetch\(/);assert.match(engineSource,/context\.availableByPosition\[position\]/,"replacement evaluation uses the precomputed positional pool");assert.doesNotMatch(serviceSource,/upsert|insert\(|update\(|delete\(|calculated_player_scores/,"read-only service exposes no write path");
console.log("v5PlayerIntelligenceLeagueProduction tests passed");
