import assert from "node:assert/strict";import {readFile} from "node:fs/promises";import {ARCHETYPES,ARCHETYPE_MATRIX,APPLICABILITY,classifyPlayerArchetype,evaluatePlayerIntelligenceComposite,evaluatePlayerIntelligenceCompositePopulation} from "../v5/js/engine/playerIntelligenceComposite.js";import {ENGINE_VERSION,calculatePlayerScores} from "../v5/js/engine/dynastyEngine.js";
const L="league",component=(score,confidence=90,status="CALCULATED")=>({score,confidence,status,warnings:[],explanations:[]});
function input(id,{age=28,minor=false,pos=["SS"],level=minor?"AAA":"MLB",hkb=500,transition=null}={}){return {schema:"player-intelligence-input-v1",playerId:id,leagueId:L,player:{id,age,isMinorLeaguer:minor},positionEligibility:{eligible:pos},market:{value:hkb},role:{recentTransition:transition,mlbStatus:level==="MLB"?"MLB":minor?"MINORS":"UNKNOWN"},prospectContext:{level,levelAvailability:level?"AVAILABLE":"UNKNOWN"}}}
function maybe(value,fallback){return value===null?component(null,null,"NOT_APPLICABLE"):component(value??fallback)}function result(id,o={}){return {playerId:id,components:{leagueProduction:maybe(o.production,80),underlyingSkill:maybe(o.skill,80),replacementAdvantage:maybe(o.replacement,70),positionalScarcityValue:component(o.scarcity??60),roleStability:component(o.role??75),ageTrajectory:component(o.age??70),risk:component(o.risk??25),prospectOpportunityCost:maybe(o.prospect,70)},signals:o.signals||[],contextEvidence:{distanceStage:o.distance??null,recentTransition:o.transition??null}}}
assert.equal(ARCHETYPE_MATRIX[ARCHETYPES.MLB_HITTER].leagueProduction.weight,24);assert.equal(ARCHETYPE_MATRIX[ARCHETYPES.MLB_RELIEVER].roleStability.weight,18);assert.equal(ARCHETYPE_MATRIX[ARCHETYPES.MLB_HITTER].prospectOpportunityCost.applicability,APPLICABILITY.NOT_APPLICABLE);assert.equal(ARCHETYPE_MATRIX[ARCHETYPES.NEAR_MLB_PROSPECT].marketSupport.weight,8);
const a=evaluatePlayerIntelligenceComposite({input:input("a"),result:result("a",{replacement:90,scarcity:85,prospect:null}),marketPercentile:55}),b=evaluatePlayerIntelligenceComposite({input:input("b",{pos:["OF"]}),result:result("b",{replacement:55,scarcity:40,prospect:null}),marketPercentile:90});assert.ok(a.expected>b.expected,"league-specific positional advantage separates equal production/skill");assert.equal(a.market.divergence,a.expected-55>=15?"UNDERVALUED_BY_MARKET":"ALIGNED_WITH_MARKET");assert.equal(b.market.divergence,b.expected-90<=-15?"OVERVALUED_BY_MARKET":"ALIGNED_WITH_MARKET");
for(const x of [a,b]){assert.ok(x.floor<=x.expected&&x.expected<=x.ceiling);assert.ok(Math.abs(x.componentContributions.reduce((s,r)=>s+r.normalizedWeight,0)-100)<1e-8)}
const extreme=evaluatePlayerIntelligenceComposite({input:input("x"),result:result("x",{production:20,skill:20,replacement:100,scarcity:100,prospect:null})});assert.ok(extreme.expected<60,"scarcity plus replacement cannot erase weak production/skill");
const near=evaluatePlayerIntelligenceComposite({input:input("near",{age:21,minor:true,level:"AAA",hkb:1000}),result:result("near",{production:null,skill:null,replacement:null,scarcity:80,role:35,age:88,risk:35,prospect:85,distance:1}),marketPercentile:75}),far=evaluatePlayerIntelligenceComposite({input:input("far",{age:21,minor:true,level:"A",pos:["OF"],hkb:1000}),result:result("far",{production:null,skill:null,replacement:null,scarcity:30,role:20,age:78,risk:75,prospect:35,distance:3}),marketPercentile:75});assert.equal(near.archetype,ARCHETYPES.NEAR_MLB_PROSPECT);assert.equal(far.archetype,ARCHETYPES.DISTANT_PROSPECT);assert.ok(near.expected>far.expected);assert.ok(!near.componentContributions.some(x=>x.component==="leagueProduction"),"missing MLB production is not zero");
assert.equal(near.componentContributions.find(x=>x.component==="prospectOpportunityCost").direction,"HIGHER_IS_BETTER_LOWER_COST");
const vetInput=input("vet",{age:35}),vetResult=result("vet",{production:90,role:90,age:30,prospect:null}),vet=evaluatePlayerIntelligenceComposite({input:vetInput,result:vetResult});const young=evaluatePlayerIntelligenceComposite({input:input("young",{age:24}),result:result("young",{production:90,role:90,age:90,prospect:null})});assert.equal(vet.archetype,ARCHETYPES.MLB_VETERAN);assert.ok(vet.expected>65);assert.ok(vet.ceiling<young.ceiling);assert.ok(!vet.componentContributions.some(x=>x.component==="prospectOpportunityCost"));
const callResult=result("call",{production:55,skill:85,role:35,age:90,risk:55,prospect:null,transition:"PROMOTED"});callResult.components.leagueProduction.confidence=45;callResult.components.roleStability.confidence=45;const call=evaluatePlayerIntelligenceComposite({input:input("call",{age:23,transition:"PROMOTED"}),result:callResult}),est=evaluatePlayerIntelligenceComposite({input:input("est",{age:28}),result:result("est",{production:55,skill:85,role:85,age:70,risk:25,prospect:null})});assert.equal(call.archetype,ARCHETYPES.YOUNG_MLB_OR_RECENT_CALLUP);assert.ok(call.overallPlayerIntelligence.confidence<=est.overallPlayerIntelligence.confidence);assert.ok(call.expected-call.floor>est.expected-est.floor);
const rpResult=result("rp",{production:90,replacement:90,role:40,risk:50,prospect:null});rpResult.components.roleStability.confidence=45;const rp=evaluatePlayerIntelligenceComposite({input:input("rp",{pos:["RP"]}),result:rpResult}),closer=evaluatePlayerIntelligenceComposite({input:input("cl",{pos:["RP"]}),result:result("cl",{production:90,replacement:90,role:90,risk:25,prospect:null})});assert.equal(rp.archetype,ARCHETYPES.MLB_RELIEVER);assert.ok(rp.expected>55);assert.ok(rp.overallPlayerIntelligence.confidence<closer.overallPlayerIntelligence.confidence);
const missingSkill=result("ms",{production:90,replacement:85,role:85,prospect:null});missingSkill.components.underlyingSkill=component(null,null,"INSUFFICIENT_DATA");const ms=evaluatePlayerIntelligenceComposite({input:input("ms"),result:missingSkill});assert.ok(ms.expected>60);assert.ok(!ms.componentContributions.some(x=>x.component==="underlyingSkill"));assert.ok(ms.dataCoverage.missingComponents.includes("underlyingSkill"));
const low=evaluatePlayerIntelligenceComposite({input:input("lo"),result:result("lo",{risk:10,prospect:null})}),high=evaluatePlayerIntelligenceComposite({input:input("hi"),result:result("hi",{risk:80,prospect:null})});assert.ok(low.expected>=high.expected);assert.ok(low.floor>high.floor);assert.equal(low.componentContributions.find(x=>x.component==="risk").compositeScore,90);
const pop=evaluatePlayerIntelligenceCompositePopulation([input("m1",{hkb:100}),input("m2",{hkb:1000})],[result("m1",{prospect:null}),result("m2",{prospect:null})]);assert.equal(pop.length,2);assert.notEqual(pop[0].market.normalizedMarketValue,pop[1].market.normalizedMarketValue);
assert.equal(classifyPlayerArchetype(input("tw",{pos:["SP","OF"]})).archetype,ARCHETYPES.TWO_WAY_DEFERRED);const legacy=calculatePlayerScores({player:{id:"z",age:30,positions:["SS"]},metrics:{},leagueSettings:{}});assert.equal(ENGINE_VERSION,"5.1.1");assert.equal(legacy.overall_score_version,"5.1.1");const engine=await readFile(new URL("../v5/js/engine/playerIntelligenceComposite.js",import.meta.url),"utf8"),service=await readFile(new URL("../v5/js/services/playerIntelligenceCompositeService.js",import.meta.url),"utf8");assert.doesNotMatch(engine,/repositories|supabase|fetch\(/);assert.doesNotMatch(service,/upsert|insert\(|update\(|delete\(|calculated_player_scores/);
const unknownInput=input("u",{age:null,pos:[]});unknownInput.player.age=null;const unknown=evaluatePlayerIntelligenceComposite({input:unknownInput,result:result("u",{prospect:null})}),known=evaluatePlayerIntelligenceComposite({input:input("known"),result:result("known",{prospect:null})});assert.equal(unknown.archetype,ARCHETYPES.CONSERVATIVE_UNKNOWN);assert.ok(unknown.warnings.includes("ARCHETYPE_UNCERTAIN"));assert.ok(unknown.overallPlayerIntelligence.confidence<known.overallPlayerIntelligence.confidence);console.log("v5PlayerIntelligenceComposite tests passed");
