import assert from "node:assert/strict";
import {performance} from "node:perf_hooks";
import {readFile} from "node:fs/promises";
import {loadPlayerIntelligenceInspection} from "../v5/js/services/playerIntelligenceInspectionService.js";
import {buildCalibrationDiagnostic} from "./playerIntelligenceCalibrationDiagnosticSupport.mjs";

const count=10326,league={id:"league",name:"Deterministic Calibration League",team_count:10,settings:{currentSeason:2026}},levels=["MLB","MLB","MLB","MLB","MLB","AAA","AA","A","ROOKIE","UNKNOWN"];
const positions=[["OF"],["SP"],["RP"],["SS"],["1B"],["SS"],["SP"],["OF"],["C"],["OF"]];
const players=Array.from({length:count},(_,index)=>{const cohort=index%10,level=levels[cohort],minor=cohort>=5&&cohort<=8,unknown=cohort===9,free=index%4===0;return {id:`player-${String(index).padStart(5,"0")}`,league_id:"league",name:`Diagnostic Player ${index}`,positions:positions[cohort],age:unknown&&index%3===0?null:cohort===3?23:cohort===4?35:minor?18+cohort:28,is_minor_leaguer:unknown?null:minor,current_level:unknown?null:level,level_source:unknown?null:"MLB_STATS_API",level_availability:unknown?"UNKNOWN":"AVAILABLE",level_observed_at:"2026-08-14T00:00:00Z",level_raw_evidence:unknown?null:{level},mlb_team:unknown?null:"ORG",roster_status:free?"FREE_AGENT":minor?"MINORS":"ACTIVE",owner_team_id:free?null:`team-${index%10}`,is_free_agent:free,hkb_value:index%3===0?null:100+index%900,fantrax_id:`*fx-${index}*`,mlbam_id:600000+index}});
const metrics=[];
for(let index=0;index<count;index++){
  const player=players[index],cohort=index%10,isMlb=cohort<=4,hasProduction=(isMlb&&index%5!==0)||(cohort===5&&index%7===0),hasStatcast=isMlb&&index%4!==0;
  if(hasProduction)metrics.push({id:`prod-${index}`,player_id:player.id,source:"Fantrax",season:2026,metric_type:"fantrax_league_production",imported_at:"2026-08-14T00:00:00Z",metrics:{fantasyPoints:50+index%650,fantasyPointsPerGame:1+index%80/10,_fantraxProduction:{importedAt:"2026-08-14T00:00:00Z"}}});
  if(hasStatcast){const pitcher=cohort===1||cohort===2;metrics.push({id:`skill-${index}`,player_id:player.id,source:"Statcast",season:2026,metric_type:pitcher?"statcast_pitching":"statcast_hitting",imported_at:"2026-08-14T00:00:00Z",metrics:pitcher?{xera:2.5+index%25/10,xwobaAllowed:.25+index%60/1000,barrelRateAllowed:4+index%12,hardHitRateAllowed:25+index%20,averageExitVelocityAllowed:84+index%10,_statcast:{fetchedAt:"2026-08-14T00:00:00Z"}}:{xwoba:.27+index%80/1000,xslg:.38+index%150/1000,xba:.22+index%70/1000,barrelRate:5+index%15,hardHitRate:30+index%25,averageExitVelocity:85+index%10,sprintSpeed:24+index%6,_statcast:{fetchedAt:"2026-08-14T00:00:00Z"}}});metrics.push({id:`collision-${index}`,player_id:player.id,source:"Fantrax",season:2026,metric_type:pitcher?"statcast_pitching":"statcast_hitting",imported_at:"2026-08-15T00:00:00Z",metrics:{}})}
}
const performanceMetrics={},started=performance.now(),pipeline=await loadPlayerIntelligenceInspection({leagueId:"league",season:2026,asOfDate:"2026-08-14T01:00:00Z",chunkSize:80,yieldFn:async()=>{},performanceMetrics,repositories:{players:{allPlayers:async()=>players},metrics:{listMetrics:async()=>metrics},leagues:{leagueById:async()=>league}}}),evaluationMs=Math.round(performance.now()-started),inputs=[...pipeline.prior.prior.production.context.inputsById.values()],aggregationStarted=performance.now(),diagnostic=buildCalibrationDiagnostic({inspection:pipeline.inspection,inputs}),diagnosticMs=Math.round((performance.now()-aggregationStarted)*100)/100;

assert.equal(diagnostic.population.count,count);assert.equal(diagnostic.calibrationDecision,"REAL_PLAYER_ACCEPTANCE_REQUIRED");assert.equal(diagnostic.invariants.floorExpectedCeilingViolations.length,0);
assert.ok(diagnostic.byArchetype.NEAR_MLB_PROSPECT.count>0);assert.ok(diagnostic.byArchetype.DISTANT_PROSPECT.count>0);assert.equal(diagnostic.byArchetype.NEAR_MLB_PROSPECT.statcast.falseMissing,0);assert.equal(diagnostic.byArchetype.DISTANT_PROSPECT.statcast.falseMissing,0);
assert.equal(diagnostic.byArchetype.YOUNG_MLB_OR_RECENT_CALLUP.count,Math.ceil((count-3)/10),"only factual young MLB rows enter the young-MLB cohort");
assert.ok(diagnostic.byArchetype.MLB_HITTER.statcast.accepted>0);assert.equal(diagnostic.byArchetype.MLB_HITTER.statcast.falseMissing,0,"newer wrong-source collisions cannot shadow canonical Statcast");
assert.equal(diagnostic.byArchetype.NEAR_MLB_PROSPECT.components.prospectOpportunityCost.missing,0);assert.equal(diagnostic.byArchetype.DISTANT_PROSPECT.components.prospectOpportunityCost.missing,0);assert.equal(diagnostic.byArchetype.MLB_HITTER.components.prospectOpportunityCost.applicable,0);
assert.ok(diagnostic.evidence.zero.count>0,"the diagnostic preserves and measures zero-confidence composite outcomes");assert.ok(diagnostic.evidence.buckets.VERY_LOW.count>0);assert.ok(diagnostic.top.veryLowExpected.length<=25);assert.ok(diagnostic.top.expected.length<=25);assert.equal(diagnostic.renormalization.minimumEvidenceFloor,false);
assert.ok(diagnostic.roles.starter.count>0);assert.ok(diagnostic.roles.reliever.count>0);assert.ok(performanceMetrics.yieldCount>400);assert.ok(evaluationMs<15000,`10,326-player diagnostic pipeline took ${evaluationMs} ms`);
for(const row of diagnostic.top.expected)assert.ok(row.playerId&&row.archetype&&row.dominantComponent);

const compositeSource=await readFile(new URL("../v5/js/engine/playerIntelligenceComposite.js",import.meta.url),"utf8"),contextSource=await readFile(new URL("../v5/js/engine/playerIntelligenceContext.js",import.meta.url),"utf8"),supportSource=await readFile(new URL("./playerIntelligenceCalibrationDiagnosticSupport.mjs",import.meta.url),"utf8");
assert.match(compositeSource,/normalizedWeight=100\*row\.effectiveWeight\/effectiveTotal/);assert.doesNotMatch(compositeSource,/minimumEvidence|evidenceFloor/i);assert.doesNotMatch(supportSource,/insert\(|update\(|upsert|delete\(|\.from\(|fetch\(/);assert.doesNotMatch(contextSource,/underlyingSkill[^\n]*HKB|leagueProduction[^\n]*HKB/i,"HKB stays bounded away from skill and production evidence");

const briefScore=value=>({count:value.count,medianExpected:value.expected.median,p90Expected:value.expected.p90,medianCeiling:value.ceiling.median,p90Ceiling:value.ceiling.p90}),briefTop=row=>({playerId:row.playerId,archetype:row.archetype,evidence:row.evidence,expected:row.expected,ceiling:row.ceiling,dominantComponent:row.dominantComponent}),distribution=rows=>Object.fromEntries([...new Set(rows.map(row=>row.archetype))].sort().map(code=>[code,rows.filter(row=>row.archetype===code).length]));
console.log(JSON.stringify({diagnostic:"V5.5B-6G3",players:count,evaluationMs,diagnosticMs,yieldCount:performanceMetrics.yieldCount,performanceMetrics,archetypes:Object.fromEntries(Object.entries(diagnostic.byArchetype).map(([code,value])=>[code,{count:value.count,percentage:value.percentage,statcast:value.statcast,ageDominant:value.dominantComponents.ageTrajectory,poc:{available:value.components.prospectOpportunityCost.available,medianScore:value.components.prospectOpportunityCost.score.median,medianConfidence:value.components.prospectOpportunityCost.confidence.median,medianWeight:value.components.prospectOpportunityCost.normalizedWeight.median}}])),evidence:{bounds:diagnostic.evidence.bounds,buckets:Object.fromEntries(Object.entries(diagnostic.evidence.buckets).map(([code,value])=>[code,briefScore(value)])),correlation:diagnostic.evidence.correlation,zero:briefScore(diagnostic.evidence.zero),nearZero:briefScore(diagnostic.evidence.nearZero)},componentCounts:Object.fromEntries(Object.entries(diagnostic.componentCounts).map(([code,value])=>[code,briefScore(value)])),roles:{starter:{count:diagnostic.roles.starter.count,confidence:diagnostic.roles.starter.overallConfidence,skillConfidence:diagnostic.roles.starter.underlyingSkill.confidence,roleConfidence:diagnostic.roles.starter.roleStability.confidence},reliever:{count:diagnostic.roles.reliever.count,confidence:diagnostic.roles.reliever.overallConfidence,skillConfidence:diagnostic.roles.reliever.underlyingSkill.confidence,roleConfidence:diagnostic.roles.reliever.roleStability.confidence}},top25:{expected:distribution(diagnostic.top.expected),ceiling:distribution(diagnostic.top.ceiling),veryLowExpected:distribution(diagnostic.top.veryLowExpected),veryLowCeiling:distribution(diagnostic.top.veryLowCeiling)},topExpected:diagnostic.top.expected.slice(0,3).map(briefTop),topVeryLow:diagnostic.top.veryLowExpected.slice(0,3).map(briefTop),invariants:diagnostic.invariants}));
