import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {applyProspectLevelPopulation,areProspectLevelEvidenceEqual,buildProspectLevelPlan,canonicalProspectLevelTimestamp,createProspectLevelPopulationUiState,previewProspectLevelPopulation,prospectLevelDifferenceReasons,PROSPECT_LEVEL_IMMUTABLE_GUARD_FIELDS,PROSPECT_LEVEL_MUTATION_FIELDS,serializeProspectLevelRawEvidence} from "../v5/js/services/prospectLevelPopulationService.js";
import {applyProspectLevelBatches} from "../v5/js/repositories/prospectLevelRepository.js";

const level=(currentLevel="AA",observed="2026-08-15T00:00:00.000Z",extra={})=>({currentLevel,levelSource:"MLB_STATS_API",levelAvailability:"AVAILABLE",levelObservedAt:observed,rawEvidence:{sportId:12,active:true},...extra});
const uuid=index=>`00000000-0000-4000-8000-${String(index).padStart(12,"0")}`;
const player=(overrides={})=>({id:uuid(1),name:"Display Name",mlbam_id:101,current_level:null,level_source:null,level_availability:null,level_observed_at:null,level_raw_evidence:null,...overrides});
const person=(overrides={})=>({mlbamId:"101",fullName:"Different Name",sportIds:[12],active:true,currentTeam:{id:5},levelEvidence:level(),...overrides});
const catalog={provider:"MLB Stats API",season:2026,fetchedAt:"2026-08-15T00:00:00.000Z",sportIds:[1,11,12],people:[person()],warnings:[]};
const baseline={status:"AVAILABLE",profile:"PROSPECT_LEVEL_POPULATION",contractVersion:"1",domains:{players:{hash:"protected"},prospectLevelEvidence:{schemaState:"PRESENT",hash:"mutable"}}};

let plan=buildProspectLevelPlan([player()],catalog);assert.equal(plan.updates.length,1);assert.equal(plan.rows[0].playerId,player().id,"MLBAM maps to the existing UUID even when names differ");
assert.equal(buildProspectLevelPlan([player({mlbam_id:null,name:"Different Name"})],catalog).unmatched.length,1,"name is never identity authority");
assert.equal(buildProspectLevelPlan([player(),player({id:"00000000-0000-4000-8000-000000000002"})],catalog).conflicts.length,1,"duplicate MLBAM identity fails closed");
const canonicalRaw=serializeProspectLevelRawEvidence(person(),person().levelEvidence),identical=player({current_level:"AA",level_source:"MLB_STATS_API",level_availability:"AVAILABLE",level_observed_at:"2026-08-15T00:00:00.000Z",level_raw_evidence:canonicalRaw});assert.equal(buildProspectLevelPlan([identical],catalog).noOps.length,1);
const productionSymptom=buildProspectLevelPlan([identical],{...catalog,people:[person({levelEvidence:level("AA","2026-08-15T00:05:00.000Z")})]});assert.deepEqual(productionSymptom.updates[0].changeReasons,["LEVEL_OBSERVED_AT_CHANGED"],"a regenerated collection timestamp reproduces the false update cause");
const noProviderObservation={...catalog,people:[person({levelEvidence:level("AA",null)})]},firstWithoutObservation=buildProspectLevelPlan([player()],noProviderObservation);assert.equal(firstWithoutObservation.updates[0].next.level_observed_at,null,"first-time evidence without a factual provider timestamp remains null");const repairedRoundTrip=buildProspectLevelPlan([structuredClone(identical)],noProviderObservation);assert.equal(repairedRoundTrip.noOps.length,1,"a new collection without factual observation time preserves stored factual freshness");assert.equal(repairedRoundTrip.noOps[0].next.level_observed_at,identical.level_observed_at);assert.deepEqual(repairedRoundTrip.changeReasonCounts,{});
assert.equal(canonicalProspectLevelTimestamp("2026-08-24T12:34:56Z"),"2026-08-24T12:34:56.000Z");assert.ok(areProspectLevelEvidenceEqual({...identical,level_observed_at:"2026-08-15T00:00:00Z"},{...identical,level_observed_at:"2026-08-15T00:00:00.000Z"}));
const databaseRaw={observations:[...canonicalRaw.observations].reverse(),normalization:{truncatedSportIdCount:0,inputSportIdCount:1},currentTeamId:5,active:true,sportIds:[...canonicalRaw.sportIds].reverse(),mlbamId:"101",schema:canonicalRaw.schema};assert.ok(areProspectLevelEvidenceEqual({...identical,level_raw_evidence:canonicalRaw},{...identical,level_raw_evidence:databaseRaw}),"JSONB key and non-semantic observation order survive database round trip");
const noTeamRaw={...canonicalRaw,currentTeamId:null};assert.deepEqual(prospectLevelDifferenceReasons({...identical,level_raw_evidence:{...noTeamRaw,currentTeamId:undefined}},{...identical,level_raw_evidence:noTeamRaw}),[],"missing optional value and database null canonicalize equally");
assert.equal(buildProspectLevelPlan([player({level_observed_at:"2026-08-16T00:00:00.000Z"})],catalog).invalid[0].reason,"STALE_PROVIDER_EVIDENCE");

const reorderedPerson=person({sportIds:[12,11,12],levelEvidence:level("AA","2026-08-15T00:00:00.000Z",{rawEvidence:[{active:true,sportId:12,unsupported:{secret:"drop"}},{sportId:11,active:true},{active:true,sportId:12}]})}),reorderedPerson2=person({sportIds:[11,12],levelEvidence:level("AA","2026-08-15T00:00:00.000Z",{rawEvidence:[{active:true,sportId:12},{active:true,sportId:11}]})});
assert.deepEqual(serializeProspectLevelRawEvidence(reorderedPerson,reorderedPerson.levelEvidence),serializeProspectLevelRawEvidence(reorderedPerson2,reorderedPerson2.levelEvidence),"semantically equal evidence canonicalizes identically");
assert.equal(JSON.stringify(serializeProspectLevelRawEvidence(reorderedPerson,reorderedPerson.levelEvidence)).includes("unsupported"),false,"unsupported provider keys never persist");
const oversized=serializeProspectLevelRawEvidence(person({sportIds:Array.from({length:30},(_,i)=>i+1)}),level("AA",undefined,{rawEvidence:Array.from({length:30},(_,i)=>({sportId:i+1,active:true}))}));assert.equal(oversized.sportIds.length,16);assert.equal(oversized.normalization.truncatedSportIdCount,14);

let reads=0,writes=0;const preview=await previewProspectLevelPopulation({leagueId:"league-1",season:2026,baseline,provider:async()=>structuredClone(catalog),repositories:{user:async()=>({id:"user-1"}),players:async()=>(reads++,[player()])}});assert.equal(writes,0);assert.equal(reads,1);assert.equal(preview.counts.updates,1);assert.match(preview.digest,/^[a-f0-9]{64}$/);
const deterministic=await previewProspectLevelPopulation({leagueId:"league-1",season:2026,baseline,provider:async()=>({...structuredClone(catalog),sportIds:[12,1,11],people:[reorderedPerson]}),repositories:{user:async()=>({id:"user-1"}),players:async()=>[player()]}}),deterministic2=await previewProspectLevelPopulation({leagueId:"league-1",season:2026,baseline,provider:async()=>({...structuredClone(catalog),people:[reorderedPerson2]}),repositories:{user:async()=>({id:"user-1"}),players:async()=>[player()]}});assert.equal(deterministic.digest,deterministic2.digest);
await assert.rejects(()=>applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:false}),/explicitly review/);
const result=await applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:{user:async()=>({id:"user-1"}),players:async()=>[player()],baseline:async()=>baseline,startJob:async()=>({id:"job-1"}),finishJob:async()=>{},apply:async(_league,rows,options)=>{writes++;assert.equal(options.batchSize,250);assert.deepEqual(Object.keys(rows[0]).sort(),[...PROSPECT_LEVEL_MUTATION_FIELDS,...PROSPECT_LEVEL_IMMUTABLE_GUARD_FIELDS].sort());assert.equal("updated_at" in rows[0],false);return [{player_id:rows[0].player_id}]}}});assert.equal(result.status,"COMPLETED");assert.equal(result.playerWrites.status,"COMPLETED");assert.equal(result.auditFinalization.status,"COMPLETED");assert.equal(writes,1);
await assert.rejects(()=>applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:{user:async()=>({id:"other"}),players:async()=>[player()],baseline:async()=>baseline,apply:async()=>[]}}),/user changed/);
await assert.rejects(()=>applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:{user:async()=>({id:"user-1"}),players:async()=>[player()],baseline:async()=>({...baseline,domains:{...baseline.domains,prospectLevelEvidence:{schemaState:"SCHEMA_ABSENT"}}}),apply:async()=>[]}}),/schema is not safely available/);

const standardRepositories=overrides=>({user:async()=>({id:"user-1"}),players:async()=>[player()],baseline:async()=>baseline,startJob:async()=>({id:"job-1"}),finishJob:async()=>{},apply:async(_league,rows)=>rows.map(row=>({player_id:row.player_id})),...overrides});
const auditFailure=await applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:standardRepositories({finishJob:async()=>{throw new Error("audit unavailable")}})});assert.equal(auditFailure.status,"AUDIT_FINALIZATION_FAILURE");assert.equal(auditFailure.playerWrites.status,"COMPLETED");assert.equal(auditFailure.successful.length,1);assert.deepEqual(auditFailure.failed,[]);assert.equal(auditFailure.auditFinalization.status,"FAILED");
const concurrencyFailure=await applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:standardRepositories({apply:async()=>[]})});assert.equal(concurrencyFailure.status,"PARTIAL_WRITE_FAILURE");assert.equal(concurrencyFailure.successful.length,0);assert.deepEqual(concurrencyFailure.failed,[uuid(1)]);
let calledAfterAuditStartFailure=false;await assert.rejects(()=>applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:standardRepositories({startJob:async()=>{throw new Error("audit start failed")},apply:async()=>{calledAfterAuditStartFailure=true;return[]}})}),/audit start failed/);assert.equal(calledAfterAuditStartFailure,false,"audit start failure stops before player writes");
const failedWrite=new Error("write failed");failedWrite.prospectLevelBatchResult={savedCount:0,savedPlayerIds:[],failedPlayerIds:[uuid(1)],unattemptedPlayerIds:[]};const writeFailure=await applyProspectLevelPopulation({leagueId:"league-1",reviewedPreview:preview,reviewed:true,repositories:standardRepositories({apply:async()=>{throw failedWrite}})});assert.equal(writeFailure.status,"FAILED_BEFORE_WRITES");assert.equal(writeFailure.playerWrites.status,"FAILED");assert.deepEqual(writeFailure.failed,[uuid(1)]);

const rows601=Array.from({length:601},(_,i)=>({player_id:uuid(i+1)})),calls=[];
const saved601=await applyProspectLevelBatches("league-1",rows601,{batchSize:250,dependencies:{client:async()=>({rpc:(name,args)=>({name,args})}),request:async query=>{calls.push(query.args.p_rows);return {data:query.args.p_rows}}}});assert.deepEqual(calls.map(batch=>batch.length),[250,250,101]);assert.equal(saved601.length,601);assert.equal(new Set(calls.flat().map(row=>row.player_id)).size,601);
let partialCalls=0,partialError;try{await applyProspectLevelBatches("league-1",rows601,{batchSize:250,dependencies:{client:async()=>({rpc:(name,args)=>({name,args})}),request:async query=>{partialCalls++;if(partialCalls===2)throw new Error("batch two failed");return {data:query.args.p_rows}}}})}catch(error){partialError=error}assert.equal(partialError.prospectLevelBatchResult.savedCount,250);assert.equal(partialError.prospectLevelBatchResult.failedPlayerIds.length,250);assert.equal(partialError.prospectLevelBatchResult.unattemptedPlayerIds.length,101);assert.equal(partialCalls,2);
const batchPlayers=Array.from({length:501},(_,i)=>player({id:uuid(i+1),mlbam_id:i+1,name:`P${i+1}`})),batchCatalog={...catalog,people:batchPlayers.map((row,i)=>person({mlbamId:String(i+1),fullName:row.name}))},initialPlan=buildProspectLevelPlan(batchPlayers,batchCatalog),partiallyStored=batchPlayers.map((row,i)=>i<250?{...row,...initialPlan.rows[i].next}:row),retryPlan=buildProspectLevelPlan(partiallyStored,batchCatalog);assert.equal(retryPlan.noOps.length,250,"successful prior rows are no-op on retry");assert.equal(retryPlan.updates.length,251,"unwritten rows remain writable on retry");

const conflictEvidence=level(null,"2026-08-17T00:00:00.000Z",{levelAvailability:"CONFLICT",rawEvidence:[{sportId:11,active:true},{sportId:12,active:true}]}),conflictCatalog={...catalog,people:[person({sportIds:[11,12],levelEvidence:conflictEvidence})]},newConflict=buildProspectLevelPlan([player()],conflictCatalog);assert.equal(newConflict.updates.length,1);assert.equal(newConflict.updates[0].next.current_level,null);assert.equal(newConflict.updates[0].next.level_availability,"CONFLICT");assert.equal(newConflict.providerConflictCount,1);assert.equal(newConflict.distribution.CONFLICT,1);
const existingGood=player({current_level:"AA",level_source:"MLB_STATS_API",level_availability:"AVAILABLE",level_observed_at:"2026-08-16T00:00:00.000Z",level_raw_evidence:canonicalRaw}),newerConflict=buildProspectLevelPlan([existingGood],conflictCatalog);assert.equal(newerConflict.updates.length,0);assert.equal(newerConflict.conflicts[0].reason,"NON_WRITABLE_PROVIDER_CONFLICT_PRESERVES_VALID_LEVEL");assert.equal(buildProspectLevelPlan([{...existingGood,level_observed_at:"2026-08-18T00:00:00.000Z"}],conflictCatalog).invalid[0].reason,"STALE_PROVIDER_EVIDENCE");
const unknownPlan=buildProspectLevelPlan([player()],{...catalog,people:[person({levelEvidence:level(null,"2026-08-17T00:00:00.000Z",{levelAvailability:"UNKNOWN",rawEvidence:{sportId:99,active:true}})})]});assert.equal(unknownPlan.updates[0].next.level_availability,"UNKNOWN");assert.equal(unknownPlan.distribution.UNKNOWN,1);assert.notEqual(unknownPlan.updates[0].next.level_availability,"CONFLICT");
for(const code of ["MLB","AAA","AA","A_PLUS","A","ROOKIE"]){const fixturePerson=person({sportIds:[12],levelEvidence:level(code,null)}),first=buildProspectLevelPlan([player()],{...catalog,people:[fixturePerson]}),stored={...player(),...first.updates[0].next},second=buildProspectLevelPlan([structuredClone(stored)],{...catalog,fetchedAt:"2026-08-16T00:00:00.000Z",people:[structuredClone(fixturePerson)]});assert.equal(second.noOps.length,1,`${code} is idempotent after persistence/readback`)}
const storedConflict={...player(),...newConflict.updates[0].next},conflictRetry=buildProspectLevelPlan([structuredClone(storedConflict)],conflictCatalog);assert.equal(conflictRetry.noOps.length,1,"identical CONFLICT evidence is idempotent");assert.equal(conflictRetry.noOps[0].next.current_level,null);
const storedUnknown={...player(),...unknownPlan.updates[0].next},unknownRetry=buildProspectLevelPlan([structuredClone(storedUnknown)],{...catalog,people:[person({levelEvidence:level(null,null,{levelAvailability:"UNKNOWN",rawEvidence:{sportId:99,active:true}})})]});assert.equal(unknownRetry.noOps.length,1,"existing writable UNKNOWN policy is idempotent");
const promoted=buildProspectLevelPlan([{...identical,current_level:"AA"}],{...catalog,people:[person({levelEvidence:level("AAA","2026-08-16T00:00:00.000Z")})]});assert.equal(promoted.updates.length,1);assert.ok(promoted.updates[0].changeReasons.includes("CURRENT_LEVEL_CHANGED"));
assert.deepEqual(prospectLevelDifferenceReasons(identical,{...identical,level_source:"REVIEWED_SOURCE"}),["LEVEL_SOURCE_CHANGED"]);assert.deepEqual(prospectLevelDifferenceReasons(identical,{...identical,level_availability:"UNKNOWN"}),["LEVEL_AVAILABILITY_CHANGED"]);assert.deepEqual(prospectLevelDifferenceReasons(identical,{...identical,level_raw_evidence:{...canonicalRaw,active:false}}),["LEVEL_RAW_EVIDENCE_CHANGED"]);
assert.ok(areProspectLevelEvidenceEqual({...identical,level_observed_at:"2026-08-15T00:00:00.123000Z"},{...identical,level_observed_at:"2026-08-15T00:00:00.123Z"}),"equivalent database timestamp precision is equal");
assert.deepEqual(createProspectLevelPopulationUiState({season:2026}),{season:2026,status:"NOT_PREVIEWED",invalidationReason:"",preview:null,reviewed:false,running:false,result:null,error:""},"reload starts unreviewed and without a persisted preview");

await assert.rejects(()=>applyProspectLevelBatches("league-1",[{}],{batchSize:251}),/1 through 250/);
const root=new URL("../",import.meta.url),migration=await readFile(new URL("supabase/migrations/015_prospect_level_population_boundary.sql",root),"utf8"),repository=await readFile(new URL("v5/js/repositories/prospectLevelRepository.js",root),"utf8"),main=await readFile(new URL("v5/js/main.js",root),"utf8"),view=await readFile(new URL("v5/js/views/importsView.js",root),"utf8");
const setClause=migration.match(/update public\.players p set([\s\S]*?)from requested r/i)?.[1]||"",whereClause=migration.match(/where p\.id[\s\S]*?returning/i)?.[0]||"";for(const field of PROSPECT_LEVEL_MUTATION_FIELDS)assert.match(setClause,new RegExp(`\\b${field}\\s*=`));for(const guard of PROSPECT_LEVEL_IMMUTABLE_GUARD_FIELDS)assert.doesNotMatch(setClause,new RegExp(`\\b${guard}\\s*=`));assert.match(whereClause,/p\.id=r\.player_id/);assert.match(whereClause,/p\.mlbam_id=r\.mlbam_id/);assert.match(migration,/private\.can_edit_league/);assert.match(migration,/security invoker/i);assert.match(migration,/set search_path = ''/);assert.match(migration,/jsonb_array_length\(p_rows\) > 250/);assert.doesNotMatch(migration,/security definer|insert into public\.players|upsert/i);assert.doesNotMatch(repository,/\.upsert\(|\.insert\(/);assert.match(main,/function resetProspectLevelPopulationState/);assert.match(main,/signOut[^\n]*resetProspectLevelPopulationState/);assert.match(main,/leagueSelect[\s\S]{0,250}resetProspectLevelPopulationState/);assert.match(main,/prospectLevelContextSignature/);assert.doesNotMatch(main,/localStorage[\s\S]{0,200}prospectLevelPopulation|prospectLevelPopulation[\s\S]{0,200}localStorage/);assert.match(view,/audit finalization/i);assert.match(view,/Provider conflicts/);assert.match(view,/names never authorize/i);
assert.match(view,/INVALIDATED/);
console.log("v5 prospect level population tests passed");
