import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { canonicalProtectedRows, captureProtectedBaseline, compareProtectedBaselines, protectedDigest } from "../v5/js/services/protectedBaselineService.js";
import { readProtectedBaselineDomains } from "../v5/js/repositories/protectedBaselineRepository.js";
import { renderImports } from "../v5/js/views/importsView.js";

const base={players:[{id:"p1",fantrax_id:"fx",fantrax_api_player_id:"api",mlbam_id:null,owner_team_id:"t1",roster_status:"ACTIVE",is_free_agent:false,positions:["SS"],updated_at:"a",hkb_value:3}],scores:[{id:"s1",player_id:"p1",score:10}],metrics:[{id:"m1",player_id:"p1",value:1}],teams:[{id:"t1",name:"Team"}],managers:[{id:"g1",team_name:"Team"}]};
const capture=rows=>captureProtectedBaseline({leagueId:"league-1",dependencies:{readProtectedBaselineDomains:async()=>structuredClone(rows)}});
const one=await capture(base),reordered=await capture({...base,players:[Object.fromEntries(Object.entries(base.players[0]).reverse())]});
assert.equal(one.status,"AVAILABLE");assert.equal(one.domains.players.hash,reordered.domains.players.hash,"field order is deterministic");
assert.equal(one.domains.players.hash,(await capture({...base,players:[...base.players].reverse()})).domains.players.hash,"row order is deterministic");
assert.equal(await protectedDigest(canonicalProtectedRows([{a:null,b:undefined}])),await protectedDigest(canonicalProtectedRows([{b:null,a:undefined}])));
for(const field of ["mlbam_id","updated_at"]){const changed=structuredClone(base);changed.players[0][field]=field==="mlbam_id"?123:"b";assert.equal((await capture(changed)).domains.players.hash,one.domains.players.hash,`${field} is allowed`)}
for(const [field,value] of [["id","p2"],["fantrax_id","other"],["fantrax_api_player_id","other-api"],["owner_team_id","t2"],["roster_status","RESERVE"],["is_free_agent",true],["positions",["OF"]],["hkb_value",9],["other_provider_identity","provider-value"]]){const changed=structuredClone(base);changed.players[0][field]=value;assert.notEqual((await capture(changed)).domains.players.hash,one.domains.players.hash,`${field} is protected`)}
const strict=await captureProtectedBaseline({leagueId:"league-1",profile:"STRICT",dependencies:{readProtectedBaselineDomains:async()=>structuredClone(base)}}),strictMlbam=structuredClone(base);strictMlbam.players[0].mlbam_id=123;assert.notEqual((await captureProtectedBaseline({leagueId:"league-1",profile:"STRICT",dependencies:{readProtectedBaselineDomains:async()=>strictMlbam}})).domains.players.hash,strict.domains.players.hash,"STRICT does not inherit MLBAM exclusions");
for(const [domain,field] of [["scores","score"],["metrics","value"],["teams","name"],["managers","team_name"]]){const changed=structuredClone(base);changed[domain][0][field]="changed";assert.notEqual((await capture(changed)).domains[domain].hash,one.domains[domain].hash,`${domain} is protected`)}
assert.equal(compareProtectedBaselines(one,await capture(base)).status,"UNCHANGED");
assert.notEqual(one.capturedAt,undefined);assert.equal(compareProtectedBaselines(one,{...(await capture(base)),capturedAt:"different-clock"}).status,"UNCHANGED","capture clock is transient evidence metadata, not hashed state");
assert.equal(compareProtectedBaselines(one,{...(await capture(base)),leagueId:"league-2"}).status,"CHANGED","league evidence cannot be compared across scopes");
const unavailable=await captureProtectedBaseline({leagueId:"league-1",dependencies:{readProtectedBaselineDomains:async()=>{throw new Error("service unavailable")}}});assert.equal(unavailable.status,"UNAVAILABLE");assert.notEqual(compareProtectedBaselines(one,unavailable).status,"UNCHANGED");
const permission=await captureProtectedBaseline({leagueId:"league-1",dependencies:{readProtectedBaselineDomains:async()=>{const error=new Error("permission denied");error.code="PERMISSION_BLOCKED";throw error}}});assert.equal(permission.status,"PERMISSION_BLOCKED");
const query=await captureProtectedBaseline({leagueId:"league-1",dependencies:{readProtectedBaselineDomains:async()=>{throw new Error("bad query")}}});assert.equal(query.status,"QUERY_FAILED");
assert.equal(one.leagueId,"league-1");assert(Object.isFrozen(one));for(const domain of Object.values(one.domains)){assert.equal(domain.capturedAt,one.capturedAt);assert.equal(domain.profile,"MLBAM_BACKFILL");assert.equal(domain.contractVersion,"1")}
const ui=renderImports({}, {mlbamBackfill:{protectedBaseline:{evidence:one}},statcast:{}});assert.match(ui,/Capture Protected Baseline/);assert.match(ui,/MLBAM_BACKFILL/);assert.match(ui,/mlbam_id, updated_at/);assert.match(ui,/SHA-256/);assert.match(ui,/Warnings: None/);
const main=await readFile(new URL("../v5/js/main.js",import.meta.url),"utf8");assert.match(main,/captureProtectedBaseline/);assert.doesNotMatch(main,/captureMlbamProtectedBaseline[\s\S]{0,600}applyMlbamIdentityBackfill/);
const repository=await readFile(new URL("../v5/js/repositories/protectedBaselineRepository.js",import.meta.url),"utf8");assert.doesNotMatch(repository,/insert\(|update\(|upsert\(|delete\(/);assert.match(repository,/auth\.getUser/);
const observed=[];const repositoryRows=await readProtectedBaselineDomains("league-1",{dependencies:{client:async()=>({auth:{getUser:async()=>({data:{user:{id:"user-1"}},error:null})}}),allPlayers:async id=>(observed.push(["players",id]),[]),listScores:async id=>(observed.push(["scores",id]),[]),listMetrics:async id=>(observed.push(["metrics",id]),[]),allTeams:async id=>(observed.push(["teams",id]),[]),listManagers:async id=>(observed.push(["managers",id]),[])}});assert.deepEqual(Object.keys(repositoryRows).sort(),["managers","metrics","players","scores","teams"]);assert.deepEqual(new Set(observed.map(([,id])=>id)),new Set(["league-1"]),"every repository read uses the active league");
await assert.rejects(()=>readProtectedBaselineDomains("league-1",{dependencies:{client:async()=>({auth:{getUser:async()=>({data:{user:null},error:null})}})}}),/Sign in/);
const service=await readFile(new URL("../v5/js/services/protectedBaselineService.js",import.meta.url),"utf8");assert.doesNotMatch(service,/fantraxGate4|Gate4|gate4/);
console.log("v5 protected baseline tests passed");
