import {loadPlayerIntelligenceComposite} from "./playerIntelligenceCompositeService.js";

export const PLAYER_INTELLIGENCE_INSPECTION_VERSION="5.5B-6";
export const INSPECTION_THRESHOLDS=Object.freeze({eliteProduction:80,strongProduction:65,lowConfidence:60,dominantContributionShare:45,overlapContributionShare:45});
export const INSPECTION_GROUPS=Object.freeze({
  ELITE_MLB_HITTERS:"ELITE_MLB_HITTERS",MIDDLE_INFIELDERS:"MIDDLE_INFIELDERS",OUTFIELDERS:"OUTFIELDERS",CATCHERS:"CATCHERS",STARTING_PITCHERS:"STARTING_PITCHERS",RELIEVERS_CLOSERS:"RELIEVERS_CLOSERS",YOUNG_MLB_PLAYERS:"YOUNG_MLB_PLAYERS",AGING_PRODUCTIVE_VETERANS:"AGING_PRODUCTIVE_VETERANS",NEAR_MLB_PROSPECTS:"NEAR_MLB_PROSPECTS",DISTANT_PROSPECTS:"DISTANT_PROSPECTS",FREE_AGENTS:"FREE_AGENTS",BELOW_REPLACEMENT_ROSTERED:"BELOW_REPLACEMENT_ROSTERED"});
const num=value=>typeof value==="number"&&Number.isFinite(value),round=value=>Math.round(Number(value)*100)/100;
const median=values=>{const rows=values.filter(num).sort((a,b)=>a-b);if(!rows.length)return null;const middle=Math.floor(rows.length/2);return rows.length%2?rows[middle]:round((rows[middle-1]+rows[middle])/2)};
const componentMap=rows=>Object.fromEntries((rows||[]).map(row=>[row.component,row]));
const hasPosition=(input,position)=>(input.positionEligibility?.eligible||[]).includes(position);
const authoritativeAvailability=input=>{const player=input.player||{},status=String(player.rosterStatus||"").toUpperCase();if(["WAIVER","WAIVERS","CLAIMED","PENDING"].includes(status))return "WAIVER";if(player.isFreeAgent===true&&player.ownerTeamId==null)return "FREE_AGENT";if(player.ownerTeamId&&player.isFreeAgent!==true)return "ROSTERED";return "UNKNOWN"};
function rawReplacementGap(result){const direct=result?.replacementContext?.rawReplacementGap;if(num(direct))return direct;const explanation=result?.components?.replacementAdvantage?.explanations?.find(row=>num(row?.data?.rawReplacementGap));return explanation?.data?.rawReplacementGap??null}
function groupMembership(input,composite,result){const groups=[],archetype=composite.archetype,production=result?.components?.leagueProduction?.score,availability=authoritativeAvailability(input),replacementGap=rawReplacementGap(result),hitter=["MLB_HITTER","YOUNG_MLB_OR_RECENT_CALLUP","MLB_VETERAN"].includes(archetype)&&!(input.positionEligibility?.eligible||[]).some(position=>["SP","RP"].includes(position));
  if(hitter&&num(production)&&production>=INSPECTION_THRESHOLDS.eliteProduction)groups.push(INSPECTION_GROUPS.ELITE_MLB_HITTERS);
  if(hasPosition(input,"2B")||hasPosition(input,"SS"))groups.push(INSPECTION_GROUPS.MIDDLE_INFIELDERS);
  if(hasPosition(input,"OF"))groups.push(INSPECTION_GROUPS.OUTFIELDERS);
  if(hasPosition(input,"C"))groups.push(INSPECTION_GROUPS.CATCHERS);
  if(archetype==="MLB_STARTING_PITCHER")groups.push(INSPECTION_GROUPS.STARTING_PITCHERS);
  if(archetype==="MLB_RELIEVER")groups.push(INSPECTION_GROUPS.RELIEVERS_CLOSERS);
  if(archetype==="YOUNG_MLB_OR_RECENT_CALLUP")groups.push(INSPECTION_GROUPS.YOUNG_MLB_PLAYERS);
  if(archetype==="MLB_VETERAN"&&num(production)&&production>=INSPECTION_THRESHOLDS.strongProduction)groups.push(INSPECTION_GROUPS.AGING_PRODUCTIVE_VETERANS);
  if(archetype==="NEAR_MLB_PROSPECT")groups.push(INSPECTION_GROUPS.NEAR_MLB_PROSPECTS);
  if(archetype==="DISTANT_PROSPECT")groups.push(INSPECTION_GROUPS.DISTANT_PROSPECTS);
  if(availability==="FREE_AGENT")groups.push(INSPECTION_GROUPS.FREE_AGENTS);
  if(availability==="ROSTERED"&&num(replacementGap)&&replacementGap<0)groups.push(INSPECTION_GROUPS.BELOW_REPLACEMENT_ROSTERED);
  return groups}
function diagnosticFlags(record){const flags=[],components=record.components,contributions=Object.values(components).filter(Boolean),top=[...contributions].sort((a,b)=>(b.normalizedWeight||0)-(a.normalizedWeight||0))[0];
  if((top?.normalizedWeight||0)>=INSPECTION_THRESHOLDS.dominantContributionShare)flags.push({code:"COMPONENT_DOMINANCE",details:{component:top.component,normalizedWeight:top.normalizedWeight}});
  if(record.archetypeConfidence<INSPECTION_THRESHOLDS.lowConfidence)flags.push({code:"LOW_ARCHETYPE_CONFIDENCE"});
  if(record.missingStatcast)flags.push({code:"MISSING_STATCAST_HIGH_PREVALENCE"});
  const overlap=(codes,code)=>{const share=codes.reduce((sum,key)=>sum+(components[key]?.normalizedWeight||0),0);if(share>=INSPECTION_THRESHOLDS.overlapContributionShare)flags.push({code,details:{normalizedWeight:round(share)}})};
  overlap(["positionalScarcityValue","replacementAdvantage"],"SCARCITY_REPLACEMENT_OVERLAP");overlap(["roleStability","leagueProduction"],"ROLE_PRODUCTION_OVERLAP");overlap(["ageTrajectory","prospectOpportunityCost"],"AGE_PROSPECT_OVERLAP");
  if(record.archetype==="MLB_RELIEVER"&&(components.roleStability?.confidence??100)<INSPECTION_THRESHOLDS.lowConfidence)flags.push({code:"RELIEVER_CONFIDENCE_SUPPRESSION"});
  if(["NEAR_MLB_PROSPECT","DISTANT_PROSPECT"].includes(record.archetype)&&(components.marketSupport?.normalizedWeight||0)>10)flags.push({code:"MARKET_SUPPORT_DOMINANCE"});
  if(record.availability==="FREE_AGENT"&&num(record.rawReplacementGap)&&record.rawReplacementGap>0)flags.push({code:"AVAILABLE_ABOVE_REPLACEMENT"});
  if(record.availability==="ROSTERED"&&num(record.rawReplacementGap)&&record.rawReplacementGap<0)flags.push({code:"ROSTERED_BELOW_REPLACEMENT"});return flags}
function inspectPlayer(input,composite,result){const components=componentMap(composite.componentContributions),archetypeWarning=(composite.warnings||[]).includes("ARCHETYPE_UNCERTAIN"),archetypeConfidence=archetypeWarning?Math.min(59,composite.overallPlayerIntelligence?.confidence||0):composite.overallPlayerIntelligence?.confidence??null,missingStatcast=(composite.dataCoverage?.missingComponents||[]).includes("underlyingSkill")||["MISSING","UNAVAILABLE","QUERY_FAILED"].includes(input.underlyingSkill?.status),availability=authoritativeAvailability(input),record={playerId:input.playerId,leagueId:input.leagueId,identity:{name:input.player?.name??null,fantraxId:input.player?.fantraxId??null,mlbamId:input.player?.mlbamId??null,organization:input.player?.organization??null,eligibility:[...(input.positionEligibility?.eligible||[])]},availability,archetype:composite.archetype,archetypeConfidence,expected:composite.expected,floor:composite.floor,ceiling:composite.ceiling,overallConfidence:composite.overallPlayerIntelligence?.confidence??null,components,market:{rawHkb:input.market?.value??null,percentile:composite.market?.normalizedMarketValue??null,divergence:composite.market?.divergence??null,signedGap:composite.market?.gap??null},strongestPositiveContributors:[...(composite.strengths||[])],strongestNegativeContributors:[...(composite.risks||[])],warnings:[...(composite.warnings||[])],missingRequiredEvidence:[...(composite.dataCoverage?.missingComponents||[])],staleEvidence:[...(composite.dataCoverage?.staleComponents||[])],missingStatcast,rawReplacementGap:rawReplacementGap(result)};record.groups=groupMembership(input,composite,result);record.diagnosticFlags=diagnosticFlags(record);return record}
function divergenceDistribution(records){return Object.fromEntries(["UNDERVALUED_BY_MARKET","ALIGNED_WITH_MARKET","OVERVALUED_BY_MARKET","MARKET_DATA_UNAVAILABLE"].map(code=>[code,records.filter(row=>row.market.divergence===code).length]))}
function summarize(records){const values=key=>records.map(row=>key(row)).filter(num),component=code=>records.map(row=>row.components[code]?.compositeScore).filter(num);return {count:records.length,medianExpected:median(values(row=>row.expected)),medianConfidence:median(values(row=>row.overallConfidence)),medianFloor:median(values(row=>row.floor)),medianCeiling:median(values(row=>row.ceiling)),medianLeagueProduction:median(component("leagueProduction")),medianUnderlyingSkill:median(component("underlyingSkill")),medianReplacementAdvantage:median(component("replacementAdvantage")),medianPositionalScarcity:median(component("positionalScarcityValue")),medianRoleStability:median(component("roleStability")),medianRiskSafety:median(component("risk")),percentageMissingStatcast:records.length?round(100*records.filter(row=>row.missingStatcast).length/records.length):0,percentageLowConfidence:records.length?round(100*records.filter(row=>(row.overallConfidence??0)<INSPECTION_THRESHOLDS.lowConfidence).length/records.length):0,marketDivergenceDistribution:divergenceDistribution(records)}}
function contributionShares(records){const codes=[...new Set(records.flatMap(row=>Object.keys(row.components)))];return Object.fromEntries(codes.map(code=>[code,median(records.map(row=>row.components[code]?.normalizedWeight))]))}
export function buildPlayerIntelligenceInspection({inputs=[],composites=[],componentResults=[]}={}){if(!Array.isArray(inputs)||!Array.isArray(composites))throw new Error("Canonical inputs and composite results are required.");const byComposite=new Map(composites.map(row=>[row.playerId,row])),byResult=new Map(componentResults.map(row=>[row.playerId,row.output||row]));const players=inputs.map(input=>{const composite=byComposite.get(input.playerId);if(!composite)throw new Error(`Composite result missing for player ${input.playerId}.`);return inspectPlayer(input,composite,byResult.get(input.playerId))});const byArchetype=Object.fromEntries([...new Set(players.map(row=>row.archetype))].map(code=>{const records=players.filter(row=>row.archetype===code);return [code,{...summarize(records),medianContributionShares:contributionShares(records)}]})),byGroup=Object.fromEntries(Object.values(INSPECTION_GROUPS).map(code=>{const records=players.filter(row=>row.groups.includes(code));return [code,{...summarize(records),medianContributionShares:contributionShares(records)}]}));return {schema:"player-intelligence-inspection-v1",version:PLAYER_INTELLIGENCE_INSPECTION_VERSION,leagueId:inputs[0]?.leagueId??null,players,diagnostics:{byArchetype,byGroup,flags:players.flatMap(row=>row.diagnosticFlags.map(flag=>({...flag,playerId:row.playerId})))},calibrationDecision:"REAL_PLAYER_ACCEPTANCE_REQUIRED"}}
export function rankInspectionPlayers(inspection,{dimension="expected",direction="desc"}={}){const componentDimensions=new Set(["leagueProduction","underlyingSkill","replacementAdvantage","positionalScarcityValue","roleStability","ageTrajectory","riskSafety","prospectOpportunityCost"]),value=row=>dimension==="confidence"?row.overallConfidence:dimension==="marketDivergenceGap"?row.market.signedGap:componentDimensions.has(dimension)?row.components[dimension==="riskSafety"?"risk":dimension]?.compositeScore:row[dimension];return [...inspection.players].sort((a,b)=>{const av=value(a),bv=value(b);if(!num(av)&&!num(bv))return a.playerId.localeCompare(b.playerId);if(!num(av))return 1;if(!num(bv))return -1;return direction==="asc"?av-bv:bv-av})}
export function filterInspectionPlayers(inspection,{archetype,mlbStatus,position,availability,confidenceBand,missingStatcast,marketDivergence}={}){return inspection.players.filter(row=>(!archetype||row.archetype===archetype)&&(!mlbStatus||(mlbStatus==="PROSPECT"?["NEAR_MLB_PROSPECT","DISTANT_PROSPECT"].includes(row.archetype):!["NEAR_MLB_PROSPECT","DISTANT_PROSPECT"].includes(row.archetype)))&&(!position||row.identity.eligibility.includes(position))&&(!availability||row.availability===availability)&&(!confidenceBand||(confidenceBand==="LOW"?(row.overallConfidence??0)<INSPECTION_THRESHOLDS.lowConfidence:(row.overallConfidence??0)>=INSPECTION_THRESHOLDS.lowConfidence))&&(missingStatcast===undefined||row.missingStatcast===missingStatcast)&&(!marketDivergence||row.market.divergence===marketDivergence))}
export function compareInspectionPlayers(inspection,playerAId,playerBId){const a=inspection.players.find(row=>row.playerId===playerAId),b=inspection.players.find(row=>row.playerId===playerBId);if(!a||!b)throw new Error("Both player UUIDs must exist in the inspection.");const codes=[...new Set([...Object.keys(a.components),...Object.keys(b.components)])],componentDifferences=codes.map(component=>({component,contributionDifference:round((a.components[component]?.contribution||0)-(b.components[component]?.contribution||0))})).sort((x,y)=>Math.abs(y.contributionDifference)-Math.abs(x.contributionDifference));return {playerAId,playerBId,expectedDifference:round((a.expected||0)-(b.expected||0)),floorDifference:round((a.floor||0)-(b.floor||0)),ceilingDifference:round((a.ceiling||0)-(b.ceiling||0)),confidenceDifference:round((a.overallConfidence||0)-(b.overallConfidence||0)),marketPercentileDifference:round((a.market.percentile||0)-(b.market.percentile||0)),marketDivergenceDifference:round((a.market.signedGap||0)-(b.market.signedGap||0)),componentDifferences,topReasonsA:componentDifferences.filter(row=>row.contributionDifference>0).slice(0,3),topReasonsB:componentDifferences.filter(row=>row.contributionDifference<0).slice(0,3)}}
export async function loadPlayerIntelligenceInspection(options={},dependencies={}){const loadComposite=dependencies.loadComposite||loadPlayerIntelligenceComposite,evaluation=await loadComposite(options),inputs=[...evaluation.prior.prior.production.context.inputsById.values()],componentResults=evaluation.prior.context.players;return {...evaluation,inspection:buildPlayerIntelligenceInspection({inputs,composites:evaluation.composite,componentResults})}}
