import {fetchMlbIdentityCatalog} from "../providers/mlbStatsApiProvider.js";
import {allPlayers} from "../repositories/playerRepository.js";
import {applyProspectLevelBatches,authenticatedProspectLevelUser} from "../repositories/prospectLevelRepository.js";
import {finishProspectLevelPopulationJob,startProspectLevelPopulationJob} from "../repositories/importJobRepository.js";
import {captureProtectedBaseline,protectedDigest} from "./protectedBaselineService.js";

const SCHEMA="prospect-level-population-preview-v1",MAX_AGE=15*60*1000,RAW_SCHEMA="mlb-stats-prospect-level-evidence-v1",MAX_RAW_OBSERVATIONS=16;
export const PROSPECT_LEVEL_MUTATION_FIELDS=Object.freeze(["current_level","level_source","level_availability","level_observed_at","level_raw_evidence"]);
export const PROSPECT_LEVEL_IMMUTABLE_GUARD_FIELDS=Object.freeze(["player_id","mlbam_id","expected_current_level","expected_level_source","expected_level_availability","expected_level_observed_at","expected_level_raw_evidence"]);
export const PROSPECT_LEVEL_CHANGE_REASONS=Object.freeze({current_level:"CURRENT_LEVEL_CHANGED",level_source:"LEVEL_SOURCE_CHANGED",level_availability:"LEVEL_AVAILABILITY_CHANGED",level_observed_at:"LEVEL_OBSERVED_AT_CHANGED",level_raw_evidence:"LEVEL_RAW_EVIDENCE_CHANGED"});
export const PROSPECT_LEVEL_DIAGNOSTIC_PAGE_SIZE=25;
const clean=value=>String(value??"").trim();
const canon=value=>value&&typeof value==="object"?Array.isArray(value)?value.map(canon):Object.fromEntries(Object.keys(value).sort().map(key=>[key,canon(value[key])])):value??null;
export function canonicalProspectLevelTimestamp(value){const text=clean(value);if(!text)return null;const parsed=Date.parse(text);return Number.isFinite(parsed)?new Date(parsed).toISOString():text}
function canonicalRawEvidence(value){
  if(!value||typeof value!=="object"||Array.isArray(value)||value.schema!==RAW_SCHEMA)return canon(value);
  const ids=[...new Set((value.sportIds||[]).map(Number).filter(id=>Number.isInteger(id)&&id>0))].sort((a,b)=>a-b).slice(0,MAX_RAW_OBSERVATIONS);
  const observations=[...new Map((value.observations||[]).map(row=>[Number(row?.sportId),{sportId:Number(row?.sportId),active:row?.active!==false}]).filter(([id])=>Number.isInteger(id)&&id>0)).values()].sort((a,b)=>a.sportId-b.sportId).slice(0,MAX_RAW_OBSERVATIONS);
  const currentTeamId=Number(value.currentTeamId);return {schema:RAW_SCHEMA,mlbamId:clean(value.mlbamId).slice(0,20),sportIds:ids,observations,active:value.active!==false,currentTeamId:Number.isInteger(currentTeamId)&&currentTeamId>0?currentTeamId:null,normalization:{inputSportIdCount:Number(value.normalization?.inputSportIdCount)||ids.length,truncatedSportIdCount:Number(value.normalization?.truncatedSportIdCount)||0}};
}
export function normalizeProspectLevelPersistedEvidence(value={}){return {current_level:value.current_level??null,level_source:value.level_source==null?null:clean(value.level_source),level_availability:value.level_availability??null,level_observed_at:canonicalProspectLevelTimestamp(value.level_observed_at),level_raw_evidence:canonicalRawEvidence(value.level_raw_evidence)}}
export function prospectLevelDifferenceReasons(current={},next={}){const before=normalizeProspectLevelPersistedEvidence(current),after=normalizeProspectLevelPersistedEvidence(next);return PROSPECT_LEVEL_MUTATION_FIELDS.filter(field=>JSON.stringify(before[field])!==JSON.stringify(after[field])).map(field=>PROSPECT_LEVEL_CHANGE_REASONS[field])}
export const areProspectLevelEvidenceEqual=(current,next)=>prospectLevelDifferenceReasons(current,next).length===0;
function rawEvidenceSummary(value){const evidence=canonicalRawEvidence(value);if(!evidence||typeof evidence!=="object"||Array.isArray(evidence)||evidence.schema!==RAW_SCHEMA)return {schema:null,observations:[],active:null,currentTeamId:null,truncatedSportIdCount:0};return {schema:RAW_SCHEMA,observations:(evidence.observations||[]).slice(0,MAX_RAW_OBSERVATIONS).map(row=>({sportId:row.sportId,active:row.active})),active:evidence.active,currentTeamId:evidence.currentTeamId,truncatedSportIdCount:evidence.normalization?.truncatedSportIdCount||0}}
export function prospectLevelRawEvidenceDiagnostic(current,next){const stored=rawEvidenceSummary(current),incoming=rawEvidenceSummary(next),before=new Map(stored.observations.map(row=>[row.sportId,row])),after=new Map(incoming.observations.map(row=>[row.sportId,row])),observationsAdded=[],observationsRemoved=[],observationsChanged=[];for(const [sportId,row] of after)if(!before.has(sportId))observationsAdded.push(row);else if(JSON.stringify(before.get(sportId))!==JSON.stringify(row))observationsChanged.push({sportId,stored:before.get(sportId),incoming:row});for(const [sportId,row] of before)if(!after.has(sportId))observationsRemoved.push(row);return {stored,incoming,observationsAdded,observationsRemoved,observationsChanged,factualFieldsChanged:["active","currentTeamId","truncatedSportIdCount"].filter(field=>stored[field]!==incoming[field])}}
export function prospectLevelDiagnosticRow(row={}){const stored=normalizeProspectLevelPersistedEvidence(row.current),incoming=normalizeProspectLevelPersistedEvidence(row.next);return {playerId:row.playerId||"",mlbamId:clean(row.mlbamId),playerName:row.playerName||"",action:row.action||"",changeReasons:[...(row.changeReasons||[])],stored:{currentLevel:stored.current_level,source:stored.level_source,availability:stored.level_availability,observedAt:stored.level_observed_at},incoming:{currentLevel:incoming.current_level,source:incoming.level_source,availability:incoming.level_availability,observedAt:incoming.level_observed_at},rawEvidence:prospectLevelRawEvidenceDiagnostic(stored.level_raw_evidence,incoming.level_raw_evidence)}}
export function queryProspectLevelDiagnostics(preview,{action="UPDATE",reason="ALL",availability="ALL",page=1,pageSize=PROSPECT_LEVEL_DIAGNOSTIC_PAGE_SIZE}={}){const allowedAction=["UPDATE","NO_OP"].includes(action)?action:"UPDATE",allowedReasons=new Set(Object.values(PROSPECT_LEVEL_CHANGE_REASONS)),allowedReason=allowedReasons.has(reason)?reason:"ALL",allowedAvailability=["ALL","CONFLICT","UNKNOWN"].includes(availability)?availability:"ALL",size=[25,50].includes(Number(pageSize))?Number(pageSize):PROSPECT_LEVEL_DIAGNOSTIC_PAGE_SIZE,source=preview?.plan?.rows||[],filtered=source.filter(row=>row.action===allowedAction&&(allowedReason==="ALL"||row.changeReasons?.includes(allowedReason))&&(allowedAvailability==="ALL"||row.next?.level_availability===allowedAvailability)),total=filtered.length,pageCount=Math.max(1,Math.ceil(total/size)),safePage=Math.min(Math.max(1,Number(page)||1),pageCount),start=(safePage-1)*size,reasonCounts=Object.fromEntries(Object.values(PROSPECT_LEVEL_CHANGE_REASONS).map(code=>[code,Number(preview?.plan?.changeReasonCounts?.[code]||0)]));return {action:allowedAction,reason:allowedReason,availability:allowedAvailability,page:safePage,pageSize:size,pageCount,total,reasonCounts,reasonTotal:Object.values(reasonCounts).reduce((sum,count)=>sum+count,0),rows:filtered.slice(start,start+size).map(prospectLevelDiagnosticRow)}}
function numericSportIds(person,evidence){
  const raw=Array.isArray(evidence.rawEvidence)?evidence.rawEvidence:[evidence.rawEvidence],values=[...(person.sportIds||[]),person.sportId,...raw.map(row=>row?.sportId)];
  return [...new Set(values.map(Number).filter(value=>Number.isInteger(value)&&value>0))].sort((a,b)=>a-b);
}
export function serializeProspectLevelRawEvidence(person={},evidence={}){
  const allSportIds=numericSportIds(person,evidence),sportIds=allSportIds.slice(0,MAX_RAW_OBSERVATIONS),raw=Array.isArray(evidence.rawEvidence)?evidence.rawEvidence:[evidence.rawEvidence],observations=[];
  for(const sportId of sportIds){const entries=raw.filter(row=>Number(row?.sportId)===sportId),active=entries.some(row=>row?.active===false)?false:person.active!==false;observations.push({sportId,active})}
  return {schema:RAW_SCHEMA,mlbamId:clean(person.mlbamId).slice(0,20),sportIds,observations,active:person.active!==false,currentTeamId:Number.isInteger(Number(person.currentTeam?.id))?Number(person.currentTeam.id):null,normalization:{inputSportIdCount:allSportIds.length,truncatedSportIdCount:Math.max(0,allSportIds.length-sportIds.length)}};
}
function payload(player,person){const evidence=person.levelEvidence||{},availability=evidence.levelAvailability||"UNKNOWN",conflict=availability==="CONFLICT";return {current_level:conflict?null:evidence.currentLevel??null,level_source:evidence.levelSource||"MLB_STATS_API",level_availability:availability,level_observed_at:canonicalProspectLevelTimestamp(evidence.levelObservedAt)||canonicalProspectLevelTimestamp(player.level_observed_at),level_raw_evidence:serializeProspectLevelRawEvidence(person,evidence)}}
export function buildProspectLevelPlan(players=[],catalog={}){
  const groups=new Map();for(const player of players){const id=clean(player.mlbam_id);if(id){if(!groups.has(id))groups.set(id,[]);groups.get(id).push(player)}}
  const rows=[],unmatched=[],conflicts=[],invalid=[];
  for(const person of catalog.people||[]){const id=clean(person.mlbamId),matches=groups.get(id)||[];
    if(!id||!person.levelEvidence){invalid.push({mlbamId:id||null,reason:"INVALID_LEVEL_EVIDENCE"});continue}
    if(matches.length===0){unmatched.push({mlbamId:id,reason:"NO_EXISTING_PLAYER_UUID"});continue}
    if(matches.length!==1){conflicts.push({mlbamId:id,playerIds:matches.map(row=>row.id),reason:"AMBIGUOUS_MLBAM_IDENTITY"});continue}
    const player=matches[0],next=payload(player,person),current=Object.fromEntries(PROSPECT_LEVEL_MUTATION_FIELDS.map(field=>[field,player[field]??null]));
    if(next.level_observed_at&&current.level_observed_at&&Date.parse(next.level_observed_at)<Date.parse(current.level_observed_at)){invalid.push({mlbamId:id,playerId:player.id,reason:"STALE_PROVIDER_EVIDENCE"});continue}
    if(next.level_availability==="CONFLICT"&&current.current_level&&["AVAILABLE","STALE"].includes(current.level_availability)){conflicts.push({mlbamId:id,playerId:player.id,reason:"NON_WRITABLE_PROVIDER_CONFLICT_PRESERVES_VALID_LEVEL",incoming:next});continue}
    const changeReasons=prospectLevelDifferenceReasons(current,next);rows.push({playerId:player.id,mlbamId:id,playerName:player.name||"",current,next,changeReasons,action:changeReasons.length?"UPDATE":"NO_OP"});
  }
  const updates=rows.filter(row=>row.action==="UPDATE"),noOps=rows.filter(row=>row.action==="NO_OP"),distribution={};for(const row of rows){const key=row.next.level_availability==="CONFLICT"?"CONFLICT":row.next.level_availability==="UNKNOWN"?"UNKNOWN":row.next.current_level||"UNKNOWN";distribution[key]=(distribution[key]||0)+1}
  const changeReasonCounts={};for(const row of updates)for(const reason of row.changeReasons)changeReasonCounts[reason]=(changeReasonCounts[reason]||0)+1;
  return {rows,updates,noOps,unmatched,conflicts,invalid,distribution,changeReasonCounts,providerConflictCount:rows.filter(row=>row.next.level_availability==="CONFLICT").length+conflicts.filter(row=>row.reason?.includes("PROVIDER_CONFLICT")).length};
}
function writeRow(row){return {player_id:row.playerId,mlbam_id:Number(row.mlbamId),...row.next,expected_current_level:row.current.current_level,expected_level_source:row.current.level_source,expected_level_availability:row.current.level_availability,expected_level_observed_at:row.current.level_observed_at,expected_level_raw_evidence:row.current.level_raw_evidence}}
async function manifestDigest(preview){return protectedDigest({schema:SCHEMA,leagueId:preview.leagueId,userId:preview.userId,snapshot:{provider:preview.provider,season:preview.season,fetchedAt:preview.fetchedAt,sportIds:preview.sportIds},baseline:{profile:preview.baseline.profile,contractVersion:preview.baseline.contractVersion,protectedHash:preview.baseline.domains?.players?.hash,schemaState:preview.baseline.domains?.prospectLevelEvidence?.schemaState},writePlan:preview.plan.updates.map(writeRow)})}
export async function previewProspectLevelPopulation({leagueId,season,baseline,provider=fetchMlbIdentityCatalog,repositories={players:allPlayers,user:authenticatedProspectLevelUser}}={}){
  if(!leagueId)throw new Error("Active league is required.");if(baseline?.profile!=="PROSPECT_LEVEL_POPULATION"||baseline.status!=="AVAILABLE")throw new Error("Capture the PROSPECT_LEVEL_POPULATION protected baseline first.");
  const [user,catalog,players]=await Promise.all([repositories.user(),provider({season}),repositories.players(leagueId)]),plan=buildProspectLevelPlan(players,catalog);
  const preview={schema:SCHEMA,status:"READY",leagueId,userId:user.id,provider:catalog.provider,season:catalog.season,fetchedAt:catalog.fetchedAt,sportIds:[...new Set((catalog.sportIds||[]).map(Number).filter(Number.isInteger))].sort((a,b)=>a-b),createdAt:new Date().toISOString(),baseline,plan,counts:{provider:(catalog.people||[]).length,matched:plan.rows.length,updates:plan.updates.length,noOps:plan.noOps.length,unmatched:plan.unmatched.length,conflicts:plan.conflicts.length,providerConflicts:plan.providerConflictCount,invalid:plan.invalid.length},warnings:[...(catalog.warnings||[])],errors:[]};preview.digest=await manifestDigest(preview);return preview;
}
export async function applyProspectLevelPopulation({leagueId,reviewedPreview,reviewed=false,repositories={players:allPlayers,user:authenticatedProspectLevelUser,baseline:captureProtectedBaseline,apply:applyProspectLevelBatches,startJob:startProspectLevelPopulationJob,finishJob:finishProspectLevelPopulationJob}}={}){
  if(!reviewed||reviewedPreview?.schema!==SCHEMA)throw new Error("Preview and explicitly review prospect-level population first.");
  if(reviewedPreview.leagueId!==leagueId||reviewedPreview.status!=="READY")throw new Error("Reviewed prospect-level context changed.");
  if(Date.now()-Date.parse(reviewedPreview.createdAt)>MAX_AGE)throw new Error("Reviewed prospect-level preview is stale.");
  const [user,players,baseline]=await Promise.all([repositories.user(),repositories.players(leagueId),repositories.baseline({leagueId,profile:"PROSPECT_LEVEL_POPULATION"})]);
  if(user.id!==reviewedPreview.userId)throw new Error("Authenticated user changed after review.");
  if(baseline.status!=="AVAILABLE"||baseline.domains?.prospectLevelEvidence?.schemaState!=="PRESENT")throw new Error("Prospect-level schema is not safely available for apply.");
  if(baseline.domains?.players?.hash!==reviewedPreview.baseline.domains?.players?.hash)throw new Error("Protected player or identity evidence changed after review.");
  const freshPlan=buildProspectLevelPlan(players,{people:reviewedPreview.plan.rows.map(row=>({mlbamId:row.mlbamId,levelEvidence:{currentLevel:row.next.current_level,levelSource:row.next.level_source,levelAvailability:row.next.level_availability,levelObservedAt:row.next.level_observed_at,rawEvidence:row.next.level_raw_evidence?.observations},sportIds:row.next.level_raw_evidence?.sportIds,active:row.next.level_raw_evidence?.active,currentTeam:{id:row.next.level_raw_evidence?.currentTeamId}}))}),check={...reviewedPreview,baseline,plan:freshPlan};
  if(await manifestDigest(check)!==reviewedPreview.digest)throw new Error("Prospect-level identity or write plan changed after review.");
  const rows=freshPlan.updates.map(writeRow);if(!rows.length)return {status:"COMPLETED",attempted:0,successful:[],failed:[],skipped:freshPlan.noOps.map(row=>row.playerId),noOps:freshPlan.noOps.map(row=>row.playerId)};
  const metadata={schema:SCHEMA,digest:reviewedPreview.digest,provider:reviewedPreview.provider,season:reviewedPreview.season,fetchedAt:reviewedPreview.fetchedAt,distribution:freshPlan.distribution,plannedUpdates:rows.length,noOps:freshPlan.noOps.length,warnings:reviewedPreview.warnings||[]},job=await repositories.startJob(leagueId,{sourceMetadata:metadata});
  let saved=[],writeError=null,failed=[],unattempted=[];
  try{saved=await repositories.apply(leagueId,rows,{batchSize:250})}catch(error){writeError=error;const partial=error.prospectLevelBatchResult||{};saved=(partial.savedPlayerIds||[]).map(player_id=>({player_id}));failed=partial.failedPlayerIds||rows.map(row=>row.player_id);unattempted=partial.unattemptedPlayerIds||[]}
  const savedIds=new Set(saved.map(row=>row.player_id));if(!writeError)failed=rows.filter(row=>!savedIds.has(row.player_id)).map(row=>row.player_id);
  const playerWriteStatus=writeError?(savedIds.size?"PARTIAL":"FAILED"):failed.length?"PARTIAL":"COMPLETED",auditPayload={status:playerWriteStatus.toLowerCase(),processed:rows.length-unattempted.length,matched:rows.length,updated:savedIds.size,failed:failed.length,errors:writeError?[{message:String(writeError?.message||writeError)}]:[],errorMessage:writeError?String(writeError?.message||writeError):null,sourceMetadata:{...metadata,successfulPlayerIds:[...savedIds],failedPlayerIds:failed,unattemptedPlayerIds:unattempted}},auditError=await repositories.finishJob(leagueId,job.id,auditPayload).then(()=>null).catch(error=>error);
  const status=auditError?"AUDIT_FINALIZATION_FAILURE":playerWriteStatus==="COMPLETED"?"COMPLETED":playerWriteStatus==="PARTIAL"?"PARTIAL_WRITE_FAILURE":"FAILED_BEFORE_WRITES";
  return {status,jobId:job.id,attempted:rows.length,successful:[...savedIds],failed,unattempted,skipped:[],noOps:freshPlan.noOps.map(row=>row.playerId),playerWrites:{status:playerWriteStatus,error:writeError?String(writeError?.message||writeError):null},auditFinalization:{status:auditError?"FAILED":"COMPLETED",error:auditError?String(auditError?.message||auditError):null},errors:[writeError,auditError].filter(Boolean).map(error=>String(error?.message||error))};
}
export function createProspectLevelPopulationUiState({season=new Date().getUTCFullYear(),status="NOT_PREVIEWED",invalidationReason=""}={}){return {season,status,invalidationReason,preview:null,reviewed:false,running:false,result:null,error:"",diagnostics:{action:"UPDATE",reason:"ALL",availability:"ALL",page:1,pageSize:PROSPECT_LEVEL_DIAGNOSTIC_PAGE_SIZE}}}
export const PROSPECT_LEVEL_POPULATION_SCHEMA=SCHEMA;
