import { escapeHtml } from "../utils/dom.js";

const stages=["Not Started","Gate A","Preview A","Candidate Review","Protected Baseline","Ready for Next Gate","EXPANDED OPT-IN REQUIRED","PREVIEW B REQUIRED","PREVIEW B PASSED","MANIFEST REVIEW","UNARMED","ARMED FOR EXACT DIGEST","PERSISTENCE USED","COMPLETED / FAILED"];
const text=value=>escapeHtml(value??"—");
function metric(label,value){return `<div class="metric"><span>${text(label)}</span><b>${text(value)}</b></div>`}
function statusClass(status){return status==="PASS"?"status-pass":status==="RUNNING"?"status-warning":"status-fail"}
function candidateRow(row,selectedIds,eligible){
  const id=String(row.matchedPlayerUuid||""),selected=selectedIds.includes(id),name=row.matchedPlayer?.name||row.fantraxApiPlayerId||"Unnamed player";
  return `<tr>${eligible?`<td><input type="checkbox" aria-label="Select ${text(name)}" data-gate4-candidate="${text(id)}" ${selected?"checked":""}></td>`:"<td>—</td>"}<td>${text(name)}</td><td><code>${text(id)}</code></td><td>${text(row.playerIdentityResult)}</td><td>${text(row.currentRosterStatus)}</td><td>${text(row.normalizedRosterStatus)}</td><td>${row.activeManualOverride?"Protected":"None"}</td><td>${text(row.gate4ExclusionReason||"Eligible status-only update")}</td></tr>`;
}

export function renderFantraxGate4Acceptance(state){
  const review=state.gate4Acceptance||{},artifact=review.artifact||{},checkpoints=artifact.checkpoints||{},preview=review.preview,selectedIds=review.selectedIds||[],eligible=review.eligibleRows||[],excluded=review.excludedRows||[],baseline=review.protectedBaseline,manifest=review.manifest,selectedRows=eligible.filter(row=>selectedIds.includes(String(row.matchedPlayerUuid||""))),result=review.persistenceResult;
  const authenticated=checkpoints.authenticatedUser?.evidence||{},league=checkpoints.activeLeague?.evidence||{},audit=checkpoints.auditBaseline?.evidence||{},season=preview?.data?.seasonContextComparison;
  return `<section class="view-panel">
    <h2>Gate 4 Deterministic Acceptance</h2>
    <p class="warning-note">Controlled Gate 4 acceptance only. Status-only persistence requires Preview B, an exact manifest-v2 digest, explicit arming, and the one-call latch.</p>
    <div class="toolbar"><button id="startGate4Acceptance" class="secondary" ${review.status==="RUNNING"||artifact.persistenceCalled?"disabled":""}>${review.stage==="NOT_STARTED"?"Start Gate 4 Acceptance Review":"Restart Acceptance Session"}</button>${review.stage==="Gate A"&&review.status==="PASS"?'<button id="fetchGate4PreviewA" class="primary">Fetch Fresh Preview A</button>':""}${review.stage==="Candidate Review"?`<button id="captureGate4ProtectedBaseline" class="primary" ${selectedIds.length!==10||review.status!=="PASS"?"disabled":""}>Capture Protected Baseline</button>`:""}${review.stage==="Ready for Next Gate"?'<button id="enableGate4ExpandedOptIn" class="primary">Enable Reviewed Expanded Opt-in</button>':""}${review.stage==="PREVIEW B REQUIRED"?'<button id="fetchGate4PreviewB" class="primary">Fetch Fresh Preview B</button>':""}${review.stage==="PREVIEW B PASSED"?'<button id="buildGate4Manifest" class="primary">Build Manifest-v2 Review</button>':""}${review.expandedOptInEnabled?'<button id="disableGate4ExpandedOptIn" class="secondary">Cancel Acceptance and Disable Expanded Opt-in</button>':""}</div>
    ${review.error?`<p class="warning-note" role="alert">${text(review.error)}</p>`:""}
    ${review.armingError?`<p class="warning-note" role="alert">Arming error: ${text(review.armingError)}. The manifest review remains valid; enter the exact current digest to retry.</p>`:""}
    <div class="grid">${metric("Harness state",review.status||"NOT_STARTED")}${metric("Stage",review.stage||"NOT_STARTED")}${metric("Authenticated user",authenticated.email||authenticated.id||"UNAVAILABLE")}${metric("Active league",league.name||"UNAVAILABLE")}${metric("Audit baseline",Number.isInteger(audit.attemptCount)?`${audit.attemptCount} attempts / ${audit.itemCount} items`:"UNAVAILABLE")}${metric("Current period",preview?preview.period||"Current":"UNAVAILABLE")}${metric("Season context",season?.status||"UNAVAILABLE")}${metric("Preview Gate B",review.previewAGateB?.status||"NOT_STARTED")}${metric("Eligible",eligible.length)}${metric("Selected",`${selectedIds.length} / 10`)}${metric("Authority",review.persistenceAuthority?"AUTHORIZED":"NOT AUTHORIZED")}${metric("Persistence",review.persistenceCalled?"USED":review.persistenceAvailable?"ENABLED":"DISABLED")}${metric("Arming",review.armed?"ARMED":"UNARMED")}${metric("Arming Error",review.armingError||"NONE")}${metric("Latch",review.persistenceCalled?"USED":"UNUSED")}</div>
    <h3>Progress</h3><ol>${stages.map(stage=>`<li class="${stage===review.stage?statusClass(review.status):""}">${text(stage)}</li>`).join("")}</ol>
    ${eligible.length||excluded.length?`<h3>Candidate Review</h3><p class="note">Selection is explicit by permanent cloud UUID. The 11th player is blocked and no candidate is substituted automatically.</p><div class="table-wrap"><table><thead><tr><th>Select</th><th>Player</th><th>UUID</th><th>Identity</th><th>Cloud status</th><th>Fantrax status</th><th>Manual override</th><th>Eligibility</th></tr></thead><tbody>${eligible.map(row=>candidateRow(row,selectedIds,true)).join("")}${excluded.map(row=>candidateRow(row,selectedIds,false)).join("")}</tbody></table></div>`:""}
    ${baseline?`<h3>Protected Baseline</h3><div class="grid">${Object.entries(baseline).map(([name,value])=>metric(name,`${value.count} / ${String(value.digest).slice(0,12)}`)).join("")}</div>${review.reviewStale?'<p class="warning-note">Preview A and its write authorization are stale after the opt-in transition. Only a new passing Preview B may continue.</p>':""}`:""}
    ${manifest?`<section class="confirmation-dialog" aria-labelledby="gate4ManifestTitle"><h3 id="gate4ManifestTitle">Final Human Manifest Review</h3><div class="grid">${metric("Manifest version",manifest.version)}${metric("Release tier",manifest.releaseTier)}${metric("Effective cap",manifest.effectiveCap)}${metric("Rows",manifest.rows?.length)}${metric("Exact digest",review.manifestDigest)}${metric("Preview B fetched",preview?.data?.fetchedAt||"UNAVAILABLE")}${metric("Period",preview?.period||"Current")}${metric("Season context",season?.status||"UNAVAILABLE")}${metric("Audit baseline",`${audit.attemptCount} attempts / ${audit.itemCount} items`)}</div><div class="table-wrap"><table><thead><tr><th>Player</th><th>UUID</th><th>Team</th><th>Cloud status</th><th>Fantrax status</th><th>Override</th><th>Release</th></tr></thead><tbody>${selectedRows.map(row=>`<tr><td>${text(row.matchedPlayer?.name)}</td><td><code>${text(row.matchedPlayerUuid)}</code></td><td>${text(row.matchedTeamUuid)}</td><td>${text(row.currentRosterStatus)}</td><td>${text(row.normalizedRosterStatus)}</td><td>${row.activeManualOverride?"Protected":"None"}</td><td>Status only; no release</td></tr>`).join("")}</tbody></table></div>${review.stage==="UNARMED"&&review.persistenceAvailable?`<label>Type the exact manifest digest to arm<input id="gate4ExactDigest" autocomplete="off" spellcheck="false"></label><button id="armGate4ExactDigest" class="primary">Arm Exact Reviewed Digest</button>`:""}${review.stage==="ARMED FOR EXACT DIGEST"&&review.persistenceExecutable?`<div class="warning-note"><strong>One-call persistence boundary armed.</strong> This can update exactly the ten reviewed status/provenance rows once. It cannot retry automatically.</div><button id="persistGate4Once" class="primary">Use One Authorized Status-Only Persistence Call</button>`:""}</section>`:""}
    ${result?`<section><h3>Post-write Evidence</h3><div class="grid">${metric("Attempt ID",result.attemptId||"UNAVAILABLE")}${metric("Lifecycle",result.status)}${metric("Actor",result.actorUserId||"UNAVAILABLE")}${metric("Manifest digest",result.digest)}${metric("Audit items",result.items?.length||0)}${metric("Terminal items",result.terminalCount)}${metric("Recoverable items",result.recoverableCount)}${metric("Replay eligibility",artifact.persistenceCalled?"BLOCKED BY ONE-CALL LATCH":"UNAVAILABLE")}${metric("Post-write Fantrax agreement",result.postWriteAgreement||"NOT_CHECKED")}${metric("Expanded opt-in",result.optInDisabled?"DISABLED":"CLEANUP REQUIRED")}</div><table><thead><tr><th>Player UUID</th><th>Outcome</th><th>Reason</th></tr></thead><tbody>${(result.items||[]).map(item=>`<tr><td><code>${text(item.player_id)}</code></td><td>${text(item.outcome)}</td><td>${text(item.reason||"—")}</td></tr>`).join("")}</tbody></table>${review.stage==="COMPLETED"&&result.postWriteAgreement==="NOT_CHECKED"?'<button id="fetchGate4PostWriteAgreement" class="secondary">Fetch Fresh Post-write Agreement Preview</button>':""}${result.optInDisabled?'<p class="note">Expanded opt-in cleanup is verified.</p>':'<p class="warning-note">Expanded opt-in cleanup is required.</p>'}</section>`:""}
    <h3>Checkpoint Evidence</h3><table><thead><tr><th>Checkpoint</th><th>Status</th><th>Digest</th></tr></thead><tbody>${Object.entries(checkpoints).map(([name,item])=>`<tr><td>${text(name)}</td><td>${text(item.status)}</td><td><code>${text(item.digest)}</code></td></tr>`).join("")||'<tr><td colspan="3">Not started.</td></tr>'}</tbody></table>
  </section>`;
}
