import { importTypes } from "../imports/cloudImportController.js";
import { MLBAM_MATCH_CLASSES, MLBAM_REASON_DESCRIPTIONS, queryMlbamPreviewRows } from "../services/mlbamIdentityBackfillService.js";

const DESCRIPTIONS={
  fantrax:"Canonical player pool, fantasy-team ownership, and roster slots.",
  hkb:"HarryKnowsBall values, ranks, and supplemental player valuation fields.",
  statcastHitters:"Statcast hitter metrics keyed by MLBAM player_id when safely matched.",
  statcastPitchers:"Statcast pitcher metrics keyed by MLBAM player_id when safely matched.",
  trades:"Historical trade records and traded assets for the active cloud league.",
  custom:"Manager intelligence, preferences, and league notes exported from the app."
};

export function renderImports(state,importState={}){
  return `<section class="view-panel"><h2>Cloud Imports</h2>${renderMlbamBackfill(importState.mlbamBackfill)}${renderAutomatedStatcast(importState.statcast)}<p class="note">Every file import requires preview, review confirmation, and writes directly to Supabase in batches for the active league. Choosing a different file invalidates the preview.</p><div class="import-grid">${importTypes.map(item=>{
    const file=importState.files?.[item.key]||null;
    const fileName=file?.name||"No file selected";
    return `<article class="import-card"><h3>${item.label}</h3><p class="note">${DESCRIPTIONS[item.key]||"Cloud source import."}</p><div class="file-picker"><input class="file-picker-input" id="file-${item.key}" data-import-file="${item.key}" type="file" accept="${item.accept}"><label class="secondary file-picker-button" for="file-${item.key}">Choose File</label><span class="file-picker-name" data-import-filename="${item.key}">${fileName}</span><button type="button" class="secondary" data-clear-import-file="${item.key}"${file?"":" disabled"}>Clear</button></div><label class="review-control"><input data-import-reviewed="${item.key}" type="checkbox" ${importState.reviewed?.[item.key]?"checked":""} ${importState.previews?.[item.key]?"":"disabled"}> I reviewed this preview.</label><div class="import-actions"><button type="button" class="secondary" data-preview-import="${item.key}">Preview</button><button type="button" class="primary" data-run-import="${item.key}" ${importState.previews?.[item.key]&&importState.reviewed?.[item.key]?"":"disabled"}>Upload</button></div><p class="note">${importState.previews?.[item.key]?"Preview ready. Confirm review to upload.":"No active preview."}</p></article>`;
  }).join("")}</div><section id="importPreviewPanel" class="panel">${renderImportPreview(importState.preview)}</section><section id="importProgressPanel" class="panel">${renderImportProgress(importState.result)}</section></section>`;
}
function renderMlbamBackfillLegacy(backfill={}){
  const preview=backfill.preview,summary=preview?.summary||{},season=backfill.season||new Date().getUTCFullYear(),sample=(preview?.rows||[]).filter(row=>row.matchClass!=="EXISTING").slice(0,50);
  return `<section class="panel"><h3>MLBAM Identity Backfill</h3><p class="note">MLB Stats API preview. Names are supporting evidence only; writes require one candidate plus authoritative organization and position evidence. Existing MLBAM IDs are never overwritten.</p><div class="toolbar"><label>Season <input id="mlbamBackfillSeason" type="number" min="2000" max="${new Date().getUTCFullYear()}" value="${season}"></label><button id="previewMlbamBackfill" class="secondary"${backfill.running?" disabled":""}>${backfill.running?"Reading…":"Preview MLBAM Matches"}</button></div>${preview?`<div class="grid">${[["Total",summary.total],["Missing",summary.missing],["Existing",summary.existing],["Exact",summary.exact],["Review",summary.review],["Ambiguous",summary.ambiguous],["Unmatched",summary.unmatched],["Duplicate existing",summary.duplicateExisting],["Duplicate proposals",summary.duplicateProposed],["Provider failures",summary.providerFailures]].map(([label,value])=>`<div class="metric"><span>${label}</span><b>${value??"Unavailable"}</b></div>`).join("")}</div><p class="note">${preview.provider} · ${preview.season} · previewed ${preview.createdAt}</p><label class="review-control"><input id="reviewMlbamBackfill" type="checkbox"${backfill.reviewed?" checked":""}${summary.exact>0?"":" disabled"}> I reviewed every exact write recommendation and its MLBAM evidence.</label><button id="applyMlbamBackfill" class="primary"${backfill.reviewed&&summary.exact>0&&!backfill.running?"":" disabled"}>Apply ${summary.exact||0} Exact MLBAM IDs</button>${sample.length?`<details><summary>Review identity evidence</summary><table class="exception-table"><thead><tr><th>Player UUID</th><th>Player</th><th>Fantrax / API</th><th>Stored org / positions</th><th>Existing MLBAM</th><th>Proposed MLBAM</th><th>Candidate org / position</th><th>Class</th><th>Writable</th><th>Evidence / Reason</th></tr></thead><tbody>${sample.map(row=>`<tr><td>${row.playerId}</td><td>${row.playerName}</td><td>${row.fantraxId||""}<br>${row.fantraxApiPlayerId||""}</td><td>${row.mlbTeam||""} / ${(row.positions||[]).join?.("/")||row.positions||""}</td><td>${row.currentMlbamId||""}</td><td>${row.proposedMlbamId||""}</td><td>${row.candidate?.currentTeam?.name||row.candidate?.currentTeam?.parentOrgName||""} / ${row.candidate?.primaryPosition||""}</td><td>${row.matchClass}</td><td>${row.writeRecommended?"WRITE":"NO WRITE"}</td><td>${(row.evidence||[]).join(", ")} ${row.ambiguityReason||""}</td></tr>`).join("")}</tbody></table></details>`:""}`:"<p class='note'>No MLBAM identity preview has run. Opening this page performs no provider read or write.</p>"}${backfill.result?`<p role="status">Backfill completed: ${backfill.result.updated?.length||0} updated, ${backfill.result.skipped?.length||0} skipped.</p>`:""}${backfill.error?`<p class="error" role="alert">${backfill.error}</p>`:""}</section>`;
}
function renderMlbamBackfill(backfill={}){
  const preview=backfill.preview,summary=preview?.summary||{},season=backfill.season||new Date().getUTCFullYear(),review=backfill.review||{},evidence=queryMlbamPreviewRows(preview,review),reasons=Object.keys(summary.reasonCounts||{}),coverage=preview?.hypotheticalStatcast||{};
  const baseline=backfill.protectedBaseline||{},captured=baseline.evidence,domainRows=Object.values(captured?.domains||{}).map(item=>`<tr><td>${item.domain}</td><td>${item.count}</td><td><code>${item.hash}</code></td><td>${item.status}</td></tr>`).join("");
  const baselineHtml=`<section><h4>Protected Baseline Evidence</h4><p class="note">Read-only authenticated evidence for the active league. Profile: <b>MLBAM_BACKFILL</b>. Allowed player changes: <b>mlbam_id, updated_at</b>.</p><button id="captureMlbamProtectedBaseline" class="secondary"${baseline.running?" disabled":""}>${baseline.running?"Capturing…":"Capture Protected Baseline"}</button>${captured?`<p class="note" role="status">${captured.status} · ${captured.capturedAt} · contract ${captured.contractVersion}</p>${domainRows?`<table class="exception-table"><thead><tr><th>Domain</th><th>Rows</th><th>SHA-256</th><th>Status</th></tr></thead><tbody>${domainRows}</tbody></table>`:""}<p class="note">Warnings: ${captured.warnings?.length?captured.warnings.join(" · "):"None"}</p>`:"<p class='note'>No protected baseline has been captured.</p>"}${baseline.error?`<p class="error" role="alert">${baseline.error}</p>`:""}</section>`;
  const pct=value=>summary.total?`${(100*Number(value||0)/summary.total).toFixed(2)}%`:"Unavailable",pctMissing=value=>summary.missing?`${(100*Number(value||0)/summary.missing).toFixed(2)}%`:"Unavailable";
  const metrics=preview?`<div class="grid">${[["Total",summary.total],["Missing",summary.missing],["Existing",summary.existing],["Exact",summary.exact],["Review",summary.review],["Ambiguous",summary.ambiguous],["Unmatched",summary.unmatched],["Duplicate existing",summary.duplicateExisting],["Duplicate proposals",summary.duplicateProposed],["Provider failures",summary.providerFailures]].map(([label,value])=>`<div class="metric"><span>${label}</span><b>${value??"Unavailable"}${["Existing","Exact","Review","Ambiguous","Unmatched"].includes(label)?` · ${pct(value)}`:""}</b></div>`).join("")}</div>`:"";
  const reasonRows=reasons.map(code=>`<tr><td>${code}</td><td>${summary.reasonCounts[code]}</td><td>${pct(summary.reasonCounts[code])}</td><td>${pctMissing(summary.reasonCounts[code])}</td><td>${MLBAM_REASON_DESCRIPTIONS[code]||"Evidence not classified."}</td></tr>`).join("");
  const classOptions=Object.values(MLBAM_MATCH_CLASSES).map(value=>`<option value="${value}"${review.matchClass===value?" selected":""}>${value}</option>`).join("");
  const reasonOptions=reasons.map(value=>`<option value="${value}"${review.reasonCode===value?" selected":""}>${value}</option>`).join("");
  const evidenceRows=evidence.rows.map(row=>`<tr><td>${row.playerId}</td><td>${row.playerName}</td><td>${row.fantraxId||""}<br>${row.fantraxApiPlayerId||""}</td><td>${row.mlbTeam||""} / ${(row.positions||[]).join?.("/")||row.positions||""}</td><td>${row.currentMlbamId||""}</td><td>${row.proposedMlbamId||""}</td><td>${row.candidate?.currentTeam?.name||row.candidate?.currentTeam?.parentOrgName||""} / ${row.candidate?.primaryPosition||""} / ${row.candidate?.active===false?"INACTIVE":row.candidate?"ACTIVE":""}</td><td>${row.matchClass}</td><td>${row.writeRecommended?"WRITE":"NO WRITE"}</td><td>${row.reasonCode}<br>${row.humanReason}</td><td>${(row.conflictingPlayers||[]).map(item=>`${item.playerId} ${item.playerName}`).join("; ")||row.conflictingPlayerIds?.join("; ")||""}</td></tr>`).join("");
  const coverageHtml=coverage.status==="AVAILABLE"?`<div class="grid">${[["Savant rows",coverage.fetched],["Currently matchable",coverage.currentlyMatchable],["Hypothetically matchable",coverage.hypotheticallyMatchable],["Remaining unmatched",coverage.remainingUnmatched],["Coverage",`${coverage.coveragePercent}%`]].map(([label,value])=>`<div class="metric"><span>${label}</span><b>${value}</b></div>`).join("")}</div>`:`<p class="note">Run a read-only Statcast preview to calculate hypothetical coverage.</p>`;
  const diagnostics=preview?`${metrics}<p class="note">${preview.provider} · ${preview.season} · previewed ${preview.createdAt}</p><details><summary>Reason-code breakdown</summary><table class="exception-table"><thead><tr><th>Reason</th><th>Count</th><th>% total</th><th>% missing</th><th>Description</th></tr></thead><tbody>${reasonRows}</tbody></table></details><h4>Hypothetical Statcast coverage</h4>${coverageHtml}<label class="review-control"><input id="reviewMlbamBackfill" type="checkbox"${backfill.reviewed?" checked":""}${summary.exact>0?"":" disabled"}> I reviewed every exact write recommendation and its MLBAM evidence.</label><button id="applyMlbamBackfill" class="primary"${backfill.reviewed&&summary.exact>0&&!backfill.running?"":" disabled"}>Apply ${summary.exact||0} Exact MLBAM IDs</button><details open><summary>Review identity evidence</summary><div class="toolbar"><label>Class <select id="mlbamEvidenceClass"><option value="ALL">All</option>${classOptions}</select></label><label>Reason <select id="mlbamEvidenceReason"><option value="ALL">All</option>${reasonOptions}</select></label><label>Search <input id="mlbamEvidenceSearch" value="${review.search||""}" placeholder="Player, UUID, Fantrax or MLBAM"></label><button id="downloadMlbamEvidence" class="secondary">Download review CSV</button></div><p class="note">${evidence.total} matching rows · page ${evidence.page} of ${evidence.pageCount}</p><table class="exception-table"><thead><tr><th>Player UUID</th><th>Player</th><th>Fantrax / API</th><th>Stored org / positions</th><th>Existing MLBAM</th><th>Proposed MLBAM</th><th>Candidate org / position / active</th><th>Class</th><th>Writable</th><th>Reason</th><th>Conflicts</th></tr></thead><tbody>${evidenceRows}</tbody></table><div class="toolbar"><button id="mlbamEvidencePrevious" class="secondary"${evidence.page<=1?" disabled":""}>Previous</button><button id="mlbamEvidenceNext" class="secondary"${evidence.page>=evidence.pageCount?" disabled":""}>Next</button></div></details>`:"<p class='note'>No MLBAM identity preview has run. Opening this page performs no provider read or write.</p>";
  return `<section class="panel"><h3>MLBAM Identity Backfill</h3><p class="note">MLB Stats API preview. Names are supporting evidence only; writes require one candidate plus authoritative organization and position evidence. Existing MLBAM IDs are never overwritten.</p>${baselineHtml}<div class="toolbar"><label>Season <input id="mlbamBackfillSeason" type="number" min="2000" max="${new Date().getUTCFullYear()}" value="${season}"></label><button id="previewMlbamBackfill" class="secondary"${backfill.running?" disabled":""}>${backfill.running?"Reading…":"Preview MLBAM Matches"}</button></div>${diagnostics}${backfill.result?`<p role="status">Backfill completed: ${backfill.result.updated?.length||0} updated, ${backfill.result.skipped?.length||0} skipped.</p>`:""}${backfill.error?`<p class="error" role="alert">${backfill.error}</p>`:""}</section>`;
}
function renderAutomatedStatcast(statcast={}){
  const season=statcast.season||new Date().getUTCFullYear(),types=statcast.types||{};
  const baseline=statcast.protectedBaseline||{},captured=baseline.evidence,domainRows=Object.values(captured?.domains||{}).map(item=>`<tr><td>${item.domain}</td><td>${item.expectedMutable?"EXPECTED MUTABLE":"PROTECTED"}</td><td>${item.count}</td><td><code>${item.hash}</code></td><td>${item.status}</td></tr>`).join("");
  const baselineHtml=`<section><h4>Statcast Protected Baseline</h4><p class="note">Profile: <b>STATCAST_REFRESH</b>. Protected: players, calculated scores, non-Statcast player metrics, teams, and managers. Expected mutable: Statcast player metrics. Allowed player fields to change: <b>NONE</b>.</p><button id="captureStatcastProtectedBaseline" class="secondary"${baseline.running?" disabled":""}>${baseline.running?"Capturing…":"Capture Statcast Protected Baseline"}</button>${captured?`<p class="note" role="status">${captured.status} · ${captured.capturedAt} · contract ${captured.contractVersion}</p>${domainRows?`<table class="exception-table"><thead><tr><th>Domain</th><th>Contract</th><th>Rows</th><th>SHA-256</th><th>Status</th></tr></thead><tbody>${domainRows}</tbody></table>`:""}<p class="note">Warnings: ${captured.warnings?.length?captured.warnings.join(" · "):"None"}</p>`:"<p class='note'>No Statcast protected baseline has been captured.</p>"}${baseline.error?`<p class="error" role="alert">${baseline.error}</p>`:""}</section>`;
  const typeHtml=playerType=>{const item=types[playerType]||{},preview=item.preview,result=item.result,label=playerType==="hitter"?"HITTERS":"PITCHERS",sources=(preview?.snapshot?.sources||[]).map(source=>`${source.sourceType}: ${source.checksum} (schema ${source.schemaVersion})`).join(" · "),messages=rows=>(rows||[]).map(row=>row?.reason||row?.message||String(row)).slice(0,10).join(" · "),resultStatus=String(result?.status||"").toUpperCase()==="COMPLETED"?"SUCCESS":String(result?.status||"").toUpperCase();return `<section><h4>${label}</h4><button data-preview-statcast="${playerType}" class="secondary"${item.running?" disabled":""}>${item.running?"Reading…":`Preview ${label}`}</button>${preview?`<div class="grid">${[["Fetched",preview.snapshot?.rows?.length],["Matched",preview.resolution?.matched?.length],["Unmatched",preview.resolution?.unmatched.length],["Conflicts",(preview.resolution?.conflicts?.length||0)+(preview.resolution?.invalid?.length||0)],["Insert",preview.plan?.inserted?.length],["Update",preview.plan?.updated?.length],["No-op",preview.plan?.unchanged?.length]].map(([name,value])=>`<div class="metric"><span>${name}</span><b>${value||0}</b></div>`).join("")}</div><p class="note">${preview.snapshot?.provider} · fetched ${preview.snapshot?.fetchedAt} · snapshot ${preview.snapshot?.snapshotId} · ${preview.status}</p><p class="note">Feeds/checksums: ${sources||"Unavailable"}</p><p class="note">Warnings (${preview.warnings?.length||0}): ${messages(preview.warnings)||"None"}</p><p class="note">Errors (${preview.errors?.length||0}): ${messages(preview.errors)||"None"}</p><label class="review-control"><input data-statcast-reviewed="${playerType}" type="checkbox"${item.reviewed?" checked":""}${preview.status==="READY"?"":" disabled"}> I reviewed this exact ${playerType} MLBAM match and write plan.</label><button data-apply-statcast="${playerType}" class="primary"${preview.status==="READY"&&item.reviewed&&!item.running&&!result?"":" disabled"}>Apply ${label}</button>`:`<p class="note">No ${playerType} preview is loaded.</p>`}${result?`<p class="${resultStatus==="SUCCESS"?"note":"error"}" role="status">${label} ${resultStatus}: ${result.matched||0} matched, ${result.inserted||0} inserted, ${result.updated||0} updated, ${result.unchanged||0} no-op, ${result.unmatched||0} unmatched, ${result.failed||0} failed. Warnings: ${result.warningCount||result.warnings?.length||0}.</p>`:""}${item.error?`<p class="error" role="alert">${item.error}</p>`:""}</section>`};
  const bothReady=["hitter","pitcher"].every(type=>types[type]?.preview?.status==="READY"&&types[type]?.reviewed&&!types[type]?.result&&!types[type]?.running);
  return `<section class="panel"><h3>Automated Statcast Refresh</h3><p class="note">Credential-free Baseball Savant CSV sources. Each type retains an independent preview and review. A combined session executes the existing hitter and pitcher persistence paths sequentially and reports partial success.</p>${baselineHtml}<div class="toolbar"><label>Season <input id="statcastSeason" type="number" min="2015" max="${new Date().getUTCFullYear()}" value="${season}"></label><span>Session: <b>${statcast.sessionStatus||"NOT_RUN"}</b></span></div>${typeHtml("hitter")}${typeHtml("pitcher")}<button id="applyReviewedStatcastSession" class="primary"${bothReady?"":" disabled"}>Apply Reviewed Hitters + Pitchers</button></section>`;
}
function renderImportPreview(preview){
  if(!preview)return"<p class='note'>Choose a file and preview it before uploading.</p>";
  const headers=(preview.columns||[]).join(", ")||"JSON file";
  const teams=(preview.fantasyTeamsDetected||[]).join(", ")||"None";
  const tokens=(preview.nonTeamStatusTokensDetected||[]).join(", ")||"None";
  const hkb=preview.previewSchema==="hkb-matching-v1"?`<div class="grid"><div class="metric"><span>Cloud players</span><b>${preview.cloudPlayersLoaded||0}</b></div><div class="metric"><span>Before matched</span><b>${preview.legacyMatchSummary?.matched||0}</b></div><div class="metric"><span>Before unmatched</span><b>${preview.legacyMatchSummary?.unmatched||0}</b></div><div class="metric"><span>Player rows</span><b>${preview.hkbSummary?.playerRows||0}</b></div><div class="metric"><span>Non-player assets</span><b>${preview.hkbSummary?.nonPlayerAssets||0}</b></div><div class="metric"><span>Unique names</span><b>${preview.hkbSummary?.uniqueNormalizedNameMatches||0}</b></div><div class="metric"><span>Normalization repairs</span><b>${preview.hkbSummary?.normalizationMismatches||0}</b></div><div class="metric"><span>Context matches</span><b>${preview.hkbSummary?.contextualMatches||0}</b></div><div class="metric"><span>Ambiguous</span><b>${preview.hkbSummary?.ambiguousRows||0}</b></div><div class="metric"><span>Context conflicts</span><b>${preview.hkbSummary?.contextConflicts||0}</b></div><div class="metric"><span>Absent</span><b>${preview.hkbSummary?.playersAbsentFromCloud||0}</b></div><div class="metric"><span>Invalid</span><b>${preview.hkbSummary?.invalidRows||0}</b></div></div>${preview.hkbDiagnostics?.length?`<details open><summary><b>HKB matching diagnostics</b></summary><table class="exception-table"><thead><tr><th>Row</th><th>Name</th><th>Team</th><th>Position</th><th>Level</th><th>Category</th><th>Candidates</th><th>Resolution</th></tr></thead><tbody>${preview.hkbDiagnostics.map(row=>`<tr><td>${row.csvRow||""}</td><td>${row.playerName||""}</td><td>${row.team||""}</td><td>${row.sourcePosition||""}</td><td>${row.sourceLevel||""}</td><td>${row.diagnosticCategory||""}</td><td>${row.candidateDetails||"None"}</td><td>${row.suggestedResolution||""}</td></tr>`).join("")}</tbody></table></details>`:""}`:"";
  return `<h3>Preview</h3><div class="grid"><div class="metric"><span>Matched</span><b>${preview.matchedRecords||preview.existingCloudMatches||0}</b></div><div class="metric"><span>Inserted</span><b>${preview.newPlayersToInsert||0}</b></div><div class="metric"><span>Updated</span><b>${preview.existingCloudMatches||0}</b></div><div class="metric"><span>Ambiguous</span><b>${preview.identityConflicts||0}</b></div><div class="metric"><span>Skipped</span><b>${preview.unmatchedRows||preview.unmatchedRecords||0}</b></div><div class="metric"><span>Errors</span><b>${preview.blockingErrors?.length||0}</b></div></div>${hkb}<p class="note"><b>Detected headers:</b> ${headers}</p><p class="note"><b>Teams detected:</b> ${teams}</p><p class="note"><b>Status tokens excluded:</b> ${tokens}</p>`;
}
function renderImportProgress(result){
  if(!result)return"<p class='note'>No import has run yet.</p>";
  const details=result.exceptionDetails||[];
  return `<h3>Import Result</h3><div class="grid"><div class="metric"><span>Matched</span><b>${result.matched||0}</b></div><div class="metric"><span>Inserted</span><b>${result.inserted||0}</b></div><div class="metric"><span>Updated</span><b>${result.updated||0}</b></div><div class="metric"><span>Skipped</span><b>${result.skipped||result.unmatched||0}</b></div><div class="metric"><span>Warnings</span><b>${result.warnings||details.length||0}</b></div><div class="metric"><span>Errors</span><b>${result.errors||0}</b></div></div>${details.length?`<details open><summary><b>View Details</b></summary><table class="exception-table"><thead><tr><th>CSV row</th><th>Player</th><th>Fantrax</th><th>MLBAM</th><th>Team</th><th>Action</th><th>Reason</th><th>Suggested resolution</th></tr></thead><tbody>${details.map(row=>`<tr><td>${row.csvRow||""}</td><td>${row.playerName||""}</td><td>${row.fantraxId||""}</td><td>${row.mlbamId||""}</td><td>${row.team||""}</td><td>${row.actionAttempted||""}</td><td>${row.failureReason||""}</td><td>${row.suggestedResolution||""}</td></tr>`).join("")}</tbody></table></details>`:""}`;
}
