import { importTypes } from "../imports/cloudImportController.js";

const DESCRIPTIONS={
  fantrax:"Canonical player pool, fantasy-team ownership, and roster slots.",
  hkb:"HarryKnowsBall values, ranks, and supplemental player valuation fields.",
  statcastHitters:"Statcast hitter metrics keyed by MLBAM player_id when safely matched.",
  statcastPitchers:"Statcast pitcher metrics keyed by MLBAM player_id when safely matched.",
  trades:"Historical trade records and traded assets for the active cloud league.",
  custom:"Manager intelligence, preferences, and league notes exported from the app."
};

export function renderImports(state,importState={}){
  return `<section class="view-panel"><h2>Cloud Imports</h2><p class="note">Every import requires preview, review confirmation, and writes directly to Supabase in batches for the active league. Choosing a different file invalidates the preview.</p><div class="import-grid">${importTypes.map(item=>{
    const file=importState.files?.[item.key]||null;
    const fileName=file?.name||"No file selected";
    return `<article class="import-card"><h3>${item.label}</h3><p class="note">${DESCRIPTIONS[item.key]||"Cloud source import."}</p><div class="file-picker"><input class="file-picker-input" id="file-${item.key}" data-import-file="${item.key}" type="file" accept="${item.accept}"><label class="secondary file-picker-button" for="file-${item.key}">Choose File</label><span class="file-picker-name" data-import-filename="${item.key}">${fileName}</span><button type="button" class="secondary" data-clear-import-file="${item.key}"${file?"":" disabled"}>Clear</button></div><label class="review-control"><input data-import-reviewed="${item.key}" type="checkbox" ${importState.reviewed?.[item.key]?"checked":""} ${importState.previews?.[item.key]?"":"disabled"}> I reviewed this preview.</label><div class="import-actions"><button type="button" class="secondary" data-preview-import="${item.key}">Preview</button><button type="button" class="primary" data-run-import="${item.key}" ${importState.previews?.[item.key]&&importState.reviewed?.[item.key]?"":"disabled"}>Upload</button></div><p class="note">${importState.previews?.[item.key]?"Preview ready. Confirm review to upload.":"No active preview."}</p></article>`;
  }).join("")}</div><section id="importPreviewPanel" class="panel">${renderImportPreview(importState.preview)}</section><section id="importProgressPanel" class="panel">${renderImportProgress(importState.result)}</section></section>`;
}
function renderImportPreview(preview){
  if(!preview)return"<p class='note'>Choose a file and preview it before uploading.</p>";
  const headers=(preview.columns||[]).join(", ")||"JSON file";
  const teams=(preview.fantasyTeamsDetected||[]).join(", ")||"None";
  const tokens=(preview.nonTeamStatusTokensDetected||[]).join(", ")||"None";
  const hkb=preview.previewSchema==="hkb-matching-v1"?`<div class="grid"><div class="metric"><span>Cloud players</span><b>${preview.cloudPlayersLoaded||0}</b></div><div class="metric"><span>Before matched</span><b>${preview.legacyMatchSummary?.matched||0}</b></div><div class="metric"><span>Before unmatched</span><b>${preview.legacyMatchSummary?.unmatched||0}</b></div><div class="metric"><span>Player rows</span><b>${preview.hkbSummary?.playerRows||0}</b></div><div class="metric"><span>Non-player assets</span><b>${preview.hkbSummary?.nonPlayerAssets||0}</b></div><div class="metric"><span>Unique names</span><b>${preview.hkbSummary?.uniqueNormalizedNameMatches||0}</b></div><div class="metric"><span>Normalization repairs</span><b>${preview.hkbSummary?.normalizationMismatches||0}</b></div><div class="metric"><span>Context matches</span><b>${preview.hkbSummary?.contextualMatches||0}</b></div><div class="metric"><span>Ambiguous</span><b>${preview.hkbSummary?.ambiguousRows||0}</b></div><div class="metric"><span>Context conflicts</span><b>${preview.hkbSummary?.contextConflicts||0}</b></div><div class="metric"><span>Absent</span><b>${preview.hkbSummary?.playersAbsentFromCloud||0}</b></div><div class="metric"><span>Invalid</span><b>${preview.hkbSummary?.invalidRows||0}</b></div></div>${preview.hkbDiagnostics?.length?`<details open><summary><b>HKB matching diagnostics</b></summary><table class="exception-table"><thead><tr><th>Row</th><th>Name</th><th>Team</th><th>Position</th><th>Level</th><th>Category</th><th>Candidates</th><th>Resolution</th></tr></thead><tbody>${preview.hkbDiagnostics.map(row=>`<tr><td>${row.csvRow||""}</td><td>${row.playerName||""}</td><td>${row.team||""}</td><td>${row.sourcePosition||""}</td><td>${row.sourceLevel||""}</td><td>${row.diagnosticCategory||""}</td><td>${row.candidateDetails||"None"}</td><td>${row.suggestedResolution||""}</td></tr>`).join("")}</tbody></table></details>`:""}`:"";
  return `<h3>Preview</h3><div class="grid"><div class="metric"><span>Matched</span><b>${preview.matchedRecords||preview.existingCloudMatches||0}</b></div><div class="metric"><span>Inserted</span><b>${preview.newPlayersToInsert||0}</b></div><div class="metric"><span>Updated</span><b>${preview.existingCloudMatches||0}</b></div><div class="metric"><span>Ambiguous</span><b>${preview.identityConflicts||0}</b></div><div class="metric"><span>Skipped</span><b>${preview.unmatchedRows||preview.unmatchedRecords||0}</b></div><div class="metric"><span>Errors</span><b>${preview.blockingErrors?.length||0}</b></div></div>${hkb}<p class="note"><b>Detected headers:</b> ${headers}</p><p class="note"><b>Teams detected:</b> ${teams}</p><p class="note"><b>Status tokens excluded:</b> ${tokens}</p>`;
}
function renderImportProgress(result){
  if(!result)return"<p class='note'>No import has run yet.</p>";
  const details=result.exceptionDetails||[];
  return `<h3>Import Result</h3><div class="grid"><div class="metric"><span>Matched</span><b>${result.matched||0}</b></div><div class="metric"><span>Inserted</span><b>${result.inserted||0}</b></div><div class="metric"><span>Updated</span><b>${result.updated||0}</b></div><div class="metric"><span>Skipped</span><b>${result.skipped||result.unmatched||0}</b></div><div class="metric"><span>Warnings</span><b>${result.warnings||details.length||0}</b></div><div class="metric"><span>Errors</span><b>${result.errors||0}</b></div></div>${details.length?`<details open><summary><b>View Details</b></summary><table class="exception-table"><thead><tr><th>CSV row</th><th>Player</th><th>Fantrax</th><th>MLBAM</th><th>Team</th><th>Action</th><th>Reason</th><th>Suggested resolution</th></tr></thead><tbody>${details.map(row=>`<tr><td>${row.csvRow||""}</td><td>${row.playerName||""}</td><td>${row.fantraxId||""}</td><td>${row.mlbamId||""}</td><td>${row.team||""}</td><td>${row.actionAttempted||""}</td><td>${row.failureReason||""}</td><td>${row.suggestedResolution||""}</td></tr>`).join("")}</tbody></table></details>`:""}`;
}
